### ISSUE TITLE
Add all-contributors to the docs repo

### ISSUE THREAD

**Issue by molebox** [prisma/prisma2-docs#2326]
This is a nice/cool way to make the community feel more involved with the docs project by highlighting their contributions, no matter how large or small, on the projects readme. We can use a bot to automate this process too.

Links: 
- https://allcontributors.org/

**Comment by Swastyy** [comment]
Hi @molebox  , Can I work on this?

**Comment by janpio** [comment]
This technically already happened: https://github.com/prisma/docs#contributors-
It is "just" not used a lot yet, as it should.
