### ISSUE TITLE
How did you make the test example work?

### ISSUE THREAD

**Issue by jtlindsey** [prisma/prisma2-docs#2327]
Hello
How did you make the test example work in [here](https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection)? 

```JavaScript
import { PrismaClient } from '@prisma/client'
import { mockDeep } from 'jest-mock-extended'
import { DeepMockProxy } from 'jest-mock-extended/lib/Mock'

export type Context = {
  prisma: PrismaClient
}

export type MockContext = {
  prisma: DeepMockProxy<PrismaClient>
}

export const createMockContext = (): MockContext => {
  return {
    prisma: mockDeep<PrismaClient>(),
  }
}
```

With `jest-mock-extended` both version 1.0.15 and 2.0.0, `DeepMockProxy` causes an error `Module '"jest-mock-extended/lib/Mock"' has no exported member 'DeepMockProxy'`

If I change setup to `import { mockDeep, mockReset, DeepMockProxy } from 'jest-mock-extended';` to correlate with https://github.com/marchaos/jest-mock-extended/pull/72 I still get no export member error.

Is this a typescript issue?

Here is my tsconfig.json

```
{
   "exclude": [
      "node_modules"
   ],
   "compilerOptions": {
      "lib": [
         "es5",
         "es6"
      ],
      "target": "es6",
      "module": "commonjs",
      "moduleResolution": "node",
      "outDir": "./build",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "sourceMap": true,
      "skipLibCheck": true
   }
}
```

**Comment by molebox** [comment]
hey @jtlindsey could you try updating `jest-mock-extended` to version `2.0.1` please and let me know if you can now import `DeepMockProxy `

**Comment by molebox** [comment]
We have a community PR https://github.com/prisma/docs/pull/2319 that suggests changing the import path, but i need to clarify their version. Testing on `2.0.2-beta2` the solution in the docs works.

**Comment by jtlindsey** [comment]
hey @molebox I'm on `2.0.2-beta2` and get error `Module '"jest-mock-extended"' has no exported member 'DeepMockProxy'`

I noticed i can't even do the following:
somefile.ts
```JavaScript
export default {
 foo: "foo",
 bar: "bar"
}
```

anotherfile.ts
```JavaScript
import { foo, bar } from './somefile';
```

I get error that `somefile` does not have export member foo. Which is making me wonder if my `prisma` project was created differently. Maybe a different `tsconfig.json`? I don't know what to look for because i'm new to `ts`.

**Comment by jtlindsey** [comment]
I still need to investigate my `ts` issues but `import { DeepMockProxy } from 'jest-mock-extended/lib/cjs/Mock';` does work with `"jest-mock-extended": "^2.0.2-beta2",` thank you.
