### ISSUE TITLE
Mention JSON filtering is a preview feature

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2-docs#2329]
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields

We don't mention here that JSON filtering is a preview feature which may confuse people. We need to mention it like we do for other preview flags. 

More context: https://github.com/prisma/prisma/issues/9205#issuecomment-920062993

**Comment by janpio** [comment]
Solved by https://github.com/prisma/docs/pull/2314/files already maybe?

**Comment by zachtil** [comment]
It seems like this has been already resolved. There is [detailed information in the docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filter-on-a-json-field) about in which versions this feature was in preview and when it became generally available.
