### ISSUE TITLE
Test still hit the database.

### ISSUE THREAD

**Issue by jtlindsey** [prisma/prisma2-docs#2334]
Hello,
Test still hit the database when using [`mockResolvedValue`](https://www.prisma.io/docs/guides/testing/unit-testing#mocking-the-prisma-client) from the example.

My `prisma postgresql` schema example

```
model User {
  id         Int          @id @default(autoincrement())
  uuid       String       @db.Uuid
  createdat DateTime     @default(now()) @db.Timestamp(6)
  updatedat DateTime     @updatedAt
  firstname String       @db.VarChar
  lastname  String       @db.VarChar
  email      String       @unique @db.VarChar
  password   String       @db.VarChar
  group      Group[]
}

enum Group {
  USER
  ADMIN
}
```

Then I have the following `jest` test
```
import { Group } from '@prisma/client';
import { create } from '../index';
import { prismaMock } from '../../../../../db/singleton';

test('should create new user ', async () => {
  try {
    const userModel = {
      id: 1,
      email: 'hello@prisma.io',
      uuid: '65sdf5sa4dfs5sdf54ds5f',
      createdat: new Date(),
      updatedat: new Date(),
      firstname: 'jon',
      lastname: 'doe',
      password: '123456',
      group: [Group.USER],
    };

    const demoUser = {
      id: 1,
      email: 'hello@prisma.io',
      uuid: '65sdf5sa4dfs5sdf54ds5f',
      firstname: 'jon',
      lastname: 'doe',
      password: '123456',
      group: [Group.USER],
    };

    prismaMock.user.create.mockResolvedValue(userModel);

    await expect(create(demoUser)).resolves.toEqual({
      id: 1,
      email: 'hello@prisma.io',
      uuid: '65sdf5sa4dfs5sdf54ds5f',
      createdat: new Date(),
      updatedat: new Date(),
      firstname: 'jon',
      lastname: 'doe',
      password: '123456',
      group: [Group.USER],
    });
  } catch (error) {
    console.log('*****', error);
  }
});

```

That results in the following error:
```
       prismaMock.user.create.mockResolvedValue(userModel);
        35·
      → 36 await expect(create(demoUser)).resolves.toEqual(
        Unique constraint failed on the fields: (`email`)]
```

Checking the database I see my previous test runs sent data to the database. I think i'm having the same issue as the following user where test still hit the database: https://stackoverflow.com/questions/67880829/how-to-mock-prisma-via-proxy-in-jest-27

**Comment by jtlindsey** [comment]
Found answer
https://stackoverflow.com/questions/69208189/how-do-handle-enum-values-in-jest-test-with-prisma-group-not-assignable-to-gr/69208810#69208810

**Comment by jtlindsey** [comment]
While that answer did solve my original question. Then I realized that the code really doesn't work anymore. I'm having the same issue as the following user where test still hit the database: https://stackoverflow.com/questions/67880829/how-to-mock-prisma-via-proxy-in-jest-27

**Comment by ankur-arch** [comment]
Hey @jtlindsey 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏. I'm closing this issue as it seems to be outdated, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
