### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by imadatyatalah** [prisma/prisma2-docs#2339]
`Explore on Github` button in [this page](https://www.prisma.io/express) links to a page that is not exists.

**Comment by janpio** [comment]
Thanks for the report.

Should probably be https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-express @nilubava? Please check with who created the page content.

**Comment by imadatyatalah** [comment]
Thanks @janpio, @nilubava 

The link is working now!
