### ISSUE TITLE
How does `$executeRawUnsafe` alone open up the possibility for SQL injection attacks?

### ISSUE THREAD

**Issue by jtlindsey** [prisma/prisma2-docs#2341]
Hello,
How does `$executeRawUnsafe` alone open up the possibility for SQL injection attacks?

In the following [docs](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#executerawunsafe) you have:

> ## <inlinecode>$executeRawUnsafe</inlinecode>
> 
> The `$executeRawUnsafe` method allows you to pass a raw string (or template string) to the database. Like `$executeRaw`, it does **not** return database records, but returns the number of rows affected.
> 
> > **Note**: `$executeRawUnsafe` can only run **one** query at a time. You cannot append a second query - for example, adding `DROP bobby_tables` to the end of an `ALTER`.
> 
> <Admonition type="warning">
> 
> By using this method you open up the possibility for SQL injection attacks. SQL injection attacks can expose your data, be it confidential or otherwise sensitive, to being modified, or even destroyed.
> 
> We strongly advise that you use the `$executeRaw` query instead. For more information on SQL injection attacks, see the [OWASP SQL Injection guide](https://www.owasp.org/index.php/SQL_Injection).
> 
> </Admonition>
> 
> The following example uses a template string to update records in the database. It then returns a count of the number of records that were updated:
> 
> ```ts
> const emailValidated = true
> const active = true
> 
> const result = await prisma.$executeRawUnsafe(
>   `UPDATE User SET active = ${active} WHERE emailValidated = ${emailValidated}`
> )
> ```
> 
> The same can be written as a parameterized query:
> 
> ```ts
> const result = prisma.$executeRawUnsafe(
>   'UPDATE User SET active = $1 WHERE emailValidated = $2',
>   'yin@prisma.io',
>   true
> )
> ```
> 

Is the line "_By using this method you open up the possibility for SQL injection attacks...._" really only focusing on "**Note**: `$executeRawUnsafe` can only run **one** query at a time. You cannot append a second query - for example, adding `DROP bobby_tables` to the end of an `ALTER`."? 

If not, I don't see how `const result = await prisma.$queryRawUnsafe(`SELECT * FROM User`)` is at risk of sql injection. Should "_By using this method you open up the possibility for SQL injection attacks..._" be "_By using this method **with user input**, you open up the possibility for SQL injection attacks..._"?

**Comment by millsp** [comment]
For instance, this would cause to delete everything:
```
const id = `42 OR true` // injected somehow somewhere

$executeRawUnsafe(`DELETE FROM table WHERE id = ${id}`)
```

And this would return everything (sensitive info maybe):
```
const id = `42 OR true` // injected somehow somewhere

$queryRawUnsafe(`SELECT * FROM table WHERE id = ${id}`)
```

**Comment by jtlindsey** [comment]
thanks @millsp ok i see. It's mainly a risk if used with user input (`i.e. ${id}`, `${value}`, etc)

**Comment by janpio** [comment]
Might be worth updating the wording on that page. Feel free to open a PR @jtlindsey - we would appreciate it. Thanks.

**Comment by jtlindsey** [comment]
@janpio PR added https://github.com/prisma/docs/pull/2349
