### ISSUE TITLE
Broken link to "Editor setup" on /docs

### ISSUE THREAD

**Issue by brianlovin** [prisma/prisma2-docs#2359]
Right now under the `More` section on the docs homepage, the `Editor setup` links to https://www.prisma.io/docs/concepts/more/editor-setup when it should probably link to https://www.prisma.io/docs/guides/development-environment/editor-setup.

I tried to figure out where to make this change on my own in the repo, but couldn't quite find it 😊

**Comment by janpio** [comment]
That would probably be fixed by https://github.com/prisma/docs/pull/2363/files - let's see if my colleagues agree.
