### ISSUE TITLE
Add hint that MongoDB connection strings might need `+srv` in the protocol

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2388]
I've set up a MongoDB on Atlas but failed to connect to it when following the docs here https://www.prisma.io/docs/concepts/database-connectors/mongodb#arguments where I used this format: `mongodb://USERNAME:PASSWORD@HOST/DATABASE?ssl=true&connectTimeoutMS=5000&maxPoolSize=50`

Once I added `+srv` to the protocol part, the connection worked: `mongodb+srv://USERNAME:PASSWORD@HOST/DATABASE?ssl=true&connectTimeoutMS=5000&maxPoolSize=50`

This should probably be pointed out in the docs.

Also, in general I think it would be great to show some "real-world" examples of what a connection string might look like for reference.

**Comment by janpio** [comment]
Here is an internal discussion with links about the meaning of the `+srv`: https://prisma-company.slack.com/archives/C013RMLGE72/p1633601502062200?thread_ts=1633594298.052900&cid=C013RMLGE72
