### ISSUE TITLE
Previous and next buttons are rendered with scrollbar

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2389]
It seems that when there's not enough space to render the full buttons, they are shown with a scrollbar which seems a bit strange? I've experienced that on this page for example: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/mongodb/install-prisma-client-typescript-mongodb

![image](https://user-images.githubusercontent.com/4058327/136357810-4fb43aa7-ee76-47c1-9a90-060290112bdc.png)

Here's a screenshot of the full page: 

![image](https://user-images.githubusercontent.com/4058327/136357999-12ecd7e1-14bf-428b-bcb0-605ffde3dbb8.png)

**Comment by janpio** [comment]
Probably platform or OS specific, works for me: 
![image](https://user-images.githubusercontent.com/183673/136375447-8d4b4dab-d754-4a68-854f-27230162d4ab.png)

Any errors in the console or network tab of dev tools?

**Comment by nilubava** [comment]
@nikolasburk Looks like this has been resolved. But in case it happens again, you can reopen this with the steps to reproduce.
