### ISSUE TITLE
Create Deployment guides for GCP/Firebase Cloud functions

### ISSUE THREAD

**Issue by goleary** [prisma/prisma2-docs#2400]
There are examples for both [GCP ](https://github.com/prisma/e2e-tests/tree/dev/platforms-serverless/gcp-functions)& [Firebase Cloud Functions](https://github.com/prisma/e2e-tests/tree/dev/platforms-serverless/firebase-functions) in the [e2e-tests](https://github.com/prisma/e2e-tests/) repo that are super useful for figuring out how to deploy prisma in each of these environments.

That said it took me quite a bit of time to find these examples because they are not linked from docs.

I [proposed ](https://github.com/prisma/docs/pull/2396) linking to these examples from the docs, but was told to instead make an issue here requesting full examples that can be included from the docs (and are not test cases).

The setup in both environments is pretty simple (if you know what to do), so they should be fairly easy to complete.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
