### ISSUE TITLE
Clicking on "Was this Helpful?" is not working

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2426]
Also, where do we see the results of these anyways?

![CleanShot 2021-10-22 at 16 11 47](https://user-images.githubusercontent.com/170299/138523495-2aed7b5a-f0d0-4de9-844a-9c905649cb80.png)

**Comment by tanberry** [comment]
@matthewmueller I'm curious too! :-) @nilubava is this something you can help with?

**Comment by janpio** [comment]
The button triggers a Netlify Serverless functions that writes into a PostgreSQL database. 
I think @2color created a Redash dashboard about these in the past where you can look at them.

**Comment by nilubava** [comment]
Duplicate of #2488

**Comment by meletj** [comment]
Fixed by https://github.com/prisma/docs/issues/2488
