### ISSUE TITLE
Clarify performance benefits of `select` and mention that `id` field is always retrieved

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2440]
When using `select` in the Prisma Client API, the query engine only retrieves the column values from the DB that are specified in the `select` option but _always_ retrieves the `@id` field. That probably should be clarified in the docs to prevent questions like [this](https://twitter.com/orenmizr/status/1452666238442905602) in the future.

![image](https://user-images.githubusercontent.com/4058327/138876586-8783a9a6-1e98-4814-83e1-c749fa4ffd81.png)

**Comment by ankur-arch** [comment]
@nikolasburk, even though an `id` is always retrieved, it doesn’t appear in the logs when we don’t _select_ it. I’m unsure what docs changes we should make for this—could you clarify further?

**Comment by nikolasburk** [comment]
Closing as outdated indeed 🙏
