### ISSUE TITLE
Consider changing title format of help articles to "How do I ..."

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2446]
https://www.prisma.io/docs/support/help-articles/finding-entities-based-on-relation

![image](https://user-images.githubusercontent.com/4058327/139412084-30bc3b09-2545-4a18-ba68-5c8bc899eec1.png)

**Comment by tanberry** [comment]
I do like that title/header of "How do I...?" @nikolasburk. Is your proposal that each of the "Help Articles" would be retitled, for example "Querying models based on their relations existence" becomes "How do I query models based on their relations existence?"

The one thing to be cautious there is that we would end up with a list of articles, all with the first few words at beginning of the title.

An alternative is to name the section header "How DoI...?" and the list the articles beneath that.

**Comment by nikolasburk** [comment]
Not doing this for now. May revisit in larger docs restructure.
