### ISSUE TITLE
Document PlanetScale usage with Prisma

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma2-docs#2448]
We want to have proper documentation for using PlanetScale with Prisma.
Sources of existing content:
 - https://github.com/prisma/prisma/issues/7292
 - https://docs.planetscale.com/tutorials/automatic-prisma-migrations
 - https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity (We need to make sure we mention how PS handles ref integrity, no FKs, etc)

See also: https://github.com/prisma/prisma/releases/tag/3.1.1

 - [x] #2449
 - [x] #2450
 - [x] #2451

**Comment by 2color** [comment]
I would also add another critical point to document when using Prisma with PlanetScale:

**When `referentialIntegrity` is set to `prisma`, foreign keys are not created which means that no index is created for the relation scalar**.

This leads to full table scans when the relations for a query are also fetched as explained in [this blog post](https://briananglin.me/posts/spending-5k-to-learn-how-database-indexes-work/)

To avoid full table scans, it's recommended to add an index on the relation scalars, for example:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Post {
  id       Int       @id @default(autoincrement())
  title    String
  excerpt  String
  content  String?
  views    Int       @default(0)
  likes    Int       @default(0)
  comments Comment[]
}

model Comment {
  id      Int    @id @default(autoincrement())
  comment String
  postId  Int
  post    Post   @relation(fields: [postId], references: [id], onDelete: Cascade)

  // Ensures an index is created for fetching relations quickly
  @@index([postId])
}
```

The index defined by `  @@index([postId])` will ensure that relations are fetched using an index while also reducing the number of **rows read** which impacts the pricing.
