### ISSUE TITLE
Getting Started section for PlanetScale

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma2-docs#2449]
Thoughts for Lucy and Tana to work on:
--where do we add the PS Guide? (Under Getting Started AND Guides, etc?)
--structure of the Guide
--what are the cool features specific to PS that we want to call out?
-- what else?

**Comment by keerlu** [comment]
Found this PR of changes to add SQL Server, which might be a useful reference: https://github.com/prisma/docs/pull/2164/files

**Comment by tanberry** [comment]
These are the pages where the Getting Started section will be modified to add PlanetScale:
-- "[Start from Scratch--> Relational databases" page,](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres) Lucy is adding PlanetScale as one of the options in the "pickers" to upper right on page.
--"Add to existing project -->Relational databases" page
-- Database connectors" page
--others?
