### ISSUE TITLE
Guide for PlanetScale

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma2-docs#2450]
To be defined: where within current doc set do we want to add info about "migrating" (using) to PlanetScale.

Cf. https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate

**Comment by tanberry** [comment]
This issue and Issue #2671 serve same purpose.

**Comment by tanberry** [comment]
Notes form Docs planning meeting:
--be sure to include info about how to "migrate to" i.e.use/integrate with PlanetScale
-- include info about how PlanetScale handles referential integrity

**Comment by tanberry** [comment]
Done! https://www.prisma.io/docs/guides/database/using-prisma-with-planetscale
