### ISSUE TITLE
Revisit the referential integrity guide

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma2-docs#2451]
Will need to edit this doc (and possibly others): https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity

**Comment by tanberry** [comment]
@keerlu let's look again at this one... I don't see PlanetScale mentioned in the Referential Integrity topic.
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity#handling-the-referential-integrity-with-foreign-keys
