### ISSUE TITLE
Document "Expanded Index Capabilities"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2466]
Documentation work for https://github.com/prisma/prisma/issues/9577

**Comment by do4gr** [comment]
Tricky bits are going to be that the length arg is only available on MySql and how Mysql actually calculates the max allowed length (that's data type dependent)

**Comment by keerlu** [comment]
Relevant current documentation:
- Schema reference: update signatures https://www.notion.so/prismaio/Setting-up-your-local-environment-f1101374ff00428a90f97bc7d4590436
- General guide: current information on indexes is here https://www.prisma.io/docs/guides/general-guides/database-workflows/unique-constraints-and-indexes

**Comment by floelhoeffel** [comment]
This was shipped today: https://www.prisma.io/docs/concepts/components/prisma-schema/index-configuration
