### ISSUE TITLE
MongoDB Many to Many docs example generates error

### ISSUE THREAD

**Issue by proevilz** [prisma/prisma2-docs#2470]
On [this docs page](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb), the following is shown as an example

```
model Post {
  id          String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  categoryIDs String[]   @db.Array(ObjectId)
  categories  Category[] @relation(fields: [categoryIDs])
}

model Category {
  id      String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  postIDs String[] @db.Array(ObjectId)
  posts   Post[]   @relation(fields: [postIDs])
}
```
But when I paste that into my Schema file
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Post {
  id          String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  categoryIDs String[]   @db.Array(ObjectId)
  categories  Category[] @relation(fields: [categoryIDs])
}

model Category {
  id      String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  postIDs String[] @db.Array(ObjectId)
  posts   Post[]   @relation(fields: [postIDs])
}
```

I get the following: 

>Error parsing attribute "@relation": The type of the field `postIDs` in the model `Category` is not matching the type of the referenced field `id` in model `Post`.

and 

>Error parsing attribute "@relation": The type of the field `categoryIDs` in the model `Post` is not matching the type of the referenced field `id` in model `Category`.

[![Image from Gyazo](https://i.gyazo.com/d4aae5bc4d8be827830c9b80f6b21361.gif)](https://gyazo.com/d4aae5bc4d8be827830c9b80f6b21361)

Am I doing something wrong here?

**Comment by janpio** [comment]
Thanks @proevilz, that is currently a bug in 3.4.0 that we are working on fixing. See these issues:
https://github.com/prisma/prisma/issues/10071
https://github.com/prisma/prisma/issues/10105

Please follow one of these issues for updates. Thanks.
