### ISSUE TITLE
Index guides seem to miss mongodb and sqlserver sub pages

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma2-docs#2472]
https://www.prisma.io/docs/guides/general-guides/database-workflows/unique-constraints-and-indexes

**Comment by janpio** [comment]
I wonder why we even have these guides? Are they maybe from a time _before_ Migrate?

**Comment by thebiglabasky** [comment]
Exactly what @janpio said: those were there to compensate the lack of migrate support so I believe we should remove them.
Or propose to archive them if we want to keep the traffic they may generate.

**Comment by tanberry** [comment]
Let's research what incoming links there are, and if we need to redirect, and if so, to what page?
