### ISSUE TITLE
Help article: How to programmatically migrate from AWS Lambda

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2487]
Based on this https://prisma.slack.com/archives/CA491RJH0/p1636333306162400 on Slack: 

![image](https://user-images.githubusercontent.com/4058327/140711379-e1ef8574-ea69-437b-b6c4-2678f55c1747.png)

**Comment by Jolg42** [comment]
Would be cleaner to document adding `execa` dependency and then just do
```ts
import execa from 'execa'

await execa.command(`prisma migrate deploy`) // and handle success / error from this 
```

**Comment by Jolg42** [comment]
One more case where it would be good to have a solution for https://github.com/prisma/prisma/issues/4703

**Comment by mateo2181** [comment]
@Jolg42 I tried that but got error 
`
 Error: Command failed with exit code 1: npx prisma migrate deploy
 Error: EROFS: read-only file system, mkdir '/home/sbx_user1051'
 command not found: prisma
`

I also tried without "npx" in the command. I am adding it inside the handler for the lambda function.
Do you know where can be the issue?

Thanks!

**Comment by Jolg42** [comment]
@mateo2181 It looks like your file system is read-only which can be a problem if you didn't install `prisma` CLI before with `npm install prisma` for example.
Because npx tries to install the Prisma CLI and likely fails, then proceeds with downloading it from npm and tries to store it on disk in a temporary directory.

**Comment by mateo2181** [comment]
Thanks for your response @Jolg42! I did it by running the migrations locally and connecting to the RDS. But I will try it anyway.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
