### ISSUE TITLE
Add a doc about Prisma client queries (vs standard SQL queries)

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2490]
Idea from @m-abdelwahab: _maybe we can create a page in the docs that explains what SQL statements each Prisma client query uses under the hood. This way if someone wants to use Prisma they can wrap their head around the API faster?_

https://prisma-company.slack.com/archives/CFK0EFYE8/p1636360509003400?thread_ts=1636359580.002500&cid=CFK0EFYE8

Discussed in Docs team; we propose a shortish topic that introduces the fact that Prisma has our own way of structuring queries, and how those queries "map" to standard SWL queries. Or don't. And then we highlight some of the most common examples, with a description of each.

**Comment by janpio** [comment]
A bit of a "philosophical" view on this: 
Prisma is not a query builder (where you write specific code, to get a specific SQL query that is executed). Prisma is a "give me this data in this form" tool. 
The SQL queries are an implementation detail the user usually should not worry about. Often that shows in the queries not being what a user would have written manually (they are more verbose, sometimes less efficient, sometimes optimized for different things and so on).

Of course does not mean that we should or can not document how some Prisma Client Queries are turned into SQL queries under the hood if this is something users care and worry about.
