### ISSUE TITLE
In left panel, "Prisma CLI" is highlighted when reading "Prisma Client" docs

### ISSUE THREAD

**Issue by yume-chan** [prisma/prisma2-docs#2494]
On all pages under https://www.prisma.io/docs/concepts/components/prisma-client, the left panel shows two highlights:

![image](https://user-images.githubusercontent.com/1330321/141059980-4a4e032e-e618-4688-9a0f-1562b4a85d31.png)

Maybe because the URL of Prisma CLI (https://www.prisma.io/docs/concepts/components/prisma-cli) is a prefix of Prisma Client.

**Comment by janpio** [comment]
I can confirm this bug: 
![image](https://user-images.githubusercontent.com/183673/141146404-43558009-8872-4d21-95bb-4ba8f8bc9da3.png)

**Comment by janpio** [comment]
This got fixed 👍
