### ISSUE TITLE
Rendering issue in code block

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2498]
I believe this code block accidentally renders some lines in red:

![image](https://user-images.githubusercontent.com/4058327/141304511-e86db9e1-efb6-404c-8977-90379246084b.png)

Code block can be found here: https://www.prisma.io/docs/about/prisma-docs/style-guide#introduce-all-code-snippets

**Comment by janpio** [comment]
It does, the `-` from the code block is interpreted as a diff indicator, this should not happen:

![image](https://user-images.githubusercontent.com/183673/141331930-68aae525-0fa4-449a-a9b9-06ee65f841e2.png)
