### ISSUE TITLE
ButtonLink component adds trailing slash to internal links

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2500]
https://github.com/mkrasne2/docs/blob/main/content/100-getting-started/02-setup-prisma/100-start-from-scratch/110-relational-databases/150-using-prisma-migrate.mdx has:

```
<ButtonLink
  color="dark"
  type="primary"
  href="./connect-your-database-node-postgres"
  arrowLeft
>
  Connect your database
</ButtonLink>

```

But on the rendered page https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgres this gets turned into:

```
<a href="/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/connect-your-database-node-postgres/" color="dark" type="primary" class="sc-iBPTik leOajw"><svg width="5" height="8" viewBox="0 0 5 8" fill="none" xmlns="http://www.w3.org/2000/svg" cl ...
```

Note the trailing slash on the URL which is not the canonical link we want.

Problem is probably in the `ButtonLink` component somehow: https://github.com/prisma/docs/blob/f33ade89743e82db488f8b35ef613f12c9d4d6a8/src/components/customMdx/button.tsx#L80-L106

**Comment by nilubava** [comment]
#2512
