### ISSUE TITLE
Catch trailing slashes in internal links

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2512]
https://github.com/prisma/docs/pull/2502 removed a bunch of trailing slashed in links. We should have some tooling that detects these instead and lets you know earlier so these can not even find their way into our codebase in the future.

(Reason why these trailing slashes are bad: SEO (Longer version: We want to have 1 canonical URL for each page, and because of technical reason that is _without_ the trailing slash in our docs))

**Comment by nilubava** [comment]
Confirm: Trailing slashes are removed from docs (in all paths). 
Solution to explore - Adapt Link checker to catch trailing slashes
