### ISSUE TITLE
Right-side menu "auto-expand" not working on Platform doc

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2520]
In the new-ish topic for the [Data Platform](https://github.com/prisma/docs/blob/main/content/200-concepts/100-components/07-prisma-data-platform.mdx)) the menu on the right side for the page's content does not auto-expand as one scrolls through the page. 

This functionality does work on this page: https://github.com/prisma/docs/blob/main/content/400-reference/200-api-reference/200-command-reference.mdx#prisma-migrate

@nilubava let me know if this is something your team can help with. I looked at the raw .mdx file and do not see any special coding or elements that make the auto-expand work, so don't really understand how this auto-expand feature is implemented.

**Comment by janpio** [comment]
The page where this works has this in the frontmatter: `tocDepth: 2` - this might influence how many levels of headlines are rendered in the sidebar.

**Comment by tanberry** [comment]
Resolved with PR [#2522](https://github.com/prisma/docs/pull/2522).
