### ISSUE TITLE
Add `findFirst` to list of batchable functions

### ISSUE THREAD

**Issue by cunisia** [prisma/prisma2-docs#2523]
[Apparently](https://github.com/prisma/prisma/issues/1470), `findFirst` calls are also batched when occurring in the same tick and having the same `where` and `include` parameters. Wouldn't it be good to update the [Query Optimization](https://github.com/prisma/docs/blob/main/content/300-guides/100-performance-and-optimization/085-query-optimization-performance.mdx) article so that users know about that ?

(I only learnt about it because I wanted to check if batching `findMany` calls was a soon to come feature. So I searched for the corresponding [github issue](https://github.com/prisma/prisma/issues/1477) which fortunately included a link to the [issue](https://github.com/prisma/prisma/issues/1470) where `findFirst` got batched)

**Comment by janpio** [comment]
I am not sure this is actually true. `findOne` (now called `findUnique`) and `findFirst` are different things.

**Comment by ankur-arch** [comment]
Hey @cunisia 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay. I'm closing this issue as it seems to be outdated, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
