### ISSUE TITLE
Set the `PRISMA_CLIENT_ENGINE_TYPE` env var to use `dataproxy` 

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2524]
The Prisma Data Proxy requires users to set the env var  `PRISMA_CLIENT_ENGINE_TYPE` to use the value `dataproxy`.

The value of `dataproxy` refers to the PDP Data Proxy, and *can be used in the schema (if the schema is for a PDP project) to define the engineType, but we do not recommend defining it in the schema; instead use the env var. 

SMEs are Jakub, Daniel, Alberto.

Pages impacted include(they might be others):
-- https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_client_engine_type
--https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#defining-the-query-engine-type-for-prisma-client

**Comment by tanberry** [comment]
Just getting back to this. Seems the user will need to add a new line in the .env file, for the `PRISMA_CLIENT_ENGINE_TYPE` environment variable.

**Comment by janpio** [comment]
The user needs to set an environment variable, using the `.env` file is one of multiple supported ways to do that. The current Data Proxy documentation for example sets it manually in the command when running `prisma generate`.

**Comment by ankur-arch** [comment]
Outdated.
