### ISSUE TITLE
Epic: Document CockroachDB database connector

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2539]
Related ticket: https://github.com/prisma/prisma/issues/2523

- [x] #2558
- [x] #2559
- [x] #2557
- [x] #2560
- [x] #2561
- [x] #3044 
- [x] #3099

**Comment by tanberry** [comment]
Refer to Dom's Slack post about this CockroachDB connector being in Preview.

**Comment by matthewmueller** [comment]
Document limitations around known unsupported APIs https://github.com/prisma/prisma-engines/pull/2423/files

(I think what @tanberry mentioned already :-))

**Comment by tanberry** [comment]
Refer to [call notes from Dec 8th](https://www.notion.so/prismaio/CockroachDB-and-Migrations-Team-5c565c5d3d294bbcb32af13f7411f280).

**Comment by janpio** [comment]
Limitations now fully documented at https://www.notion.so/prismaio/Documentation-Differences-of-CockroachDB-to-PostgreSQL-55b953f4f2d74e1d9239a42d6169687c#a7a8a13b0eb94f649c4e0bc8ba798742

**Comment by tanberry** [comment]
Refer to https://github.com/prisma/prisma/issues/10805 for specifics on connection url

**Comment by tomhoule** [comment]
I think we can consider this complete :tada:

**Comment by keerlu** [comment]
Agree, will close now
