### ISSUE TITLE
Document raw query support for MongoDB

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2540]
Update `$queryRaw` and `$executeQuery` docs to include MongoDB

Relevant ticket: https://github.com/prisma/prisma/issues/8270

**Comment by tanberry** [comment]
Impacts following docs:
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#queryraw
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#raw-queries-with-mongodb
?

Also take a look at Dom's reply in this Prisma [Issue](https://github.com/prisma/prisma/discussions/11688)  and [this thread](https://prisma-company.slack.com/archives/C013RMLGE72/p1644433896826199) in Slack.

**Comment by keerlu** [comment]
This has now been done - see PR #2778
