### ISSUE TITLE
Document breaking migration commands into primitives

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2542]
Relevant ticket: https://github.com/prisma/migrations-team/issues/283

This details of this are still being worked out but we should be aware of this as a significant change coming up

**Comment by tanberry** [comment]
Notes from our Docs planning meeting:
-- Procedural/Guides content: we discussed working with Frederik and team to identify the top use cases for each primitive/combination, and then writing task-based docs for each use case, with scenario, why to use each, how to use, etc.
-- for Reference docs, we can use what the team has in Notion... they will use same text for the CLI "man pages". Writers can help edit exact wording and names. Eventually let's look at how we can auto-generate the Reference docs for these.
-- we will want a short overview Concepts topic for this.
-- Hervé pointed out that some existing docs might need to be tweaked, to add additional content about how primitives can now be used to solve migration problems.
