### ISSUE TITLE
Release:

### ISSUE THREAD

**Issue by shaizdragon87** [prisma/prisma2-docs#2547]
## Release

- [x] Merge in new content
- [x] Update 'What's new' page with links to the relase notes and new docs (example: https://www.prisma.io/docs/about/whats-new-in-prisma-docs#april-04-2021)
- [x] Add links to release notes

## After release

- [x] Add the 'What's new' video
- [x] Clean up milestone

**Comment by janpio** [comment]
See https://github.com/nodejs/node/issues/40866
