### ISSUE TITLE
Docs need to be updated

### ISSUE THREAD

**Issue by dborstelmann** [prisma/prisma2-docs#2552]
This is broken: https://www.prisma.io/docs/guides/testing/unit-testing#dependency-injection

See: https://github.com/prisma/prisma/discussions/2083#discussioncomment-1590323

Change
```
import { PrismaClient } from '@prisma/client';
import { mockDeep } from 'jest-mock-extended';
import { DeepMockProxy } from 'jest-mock-extended/lib/cjs/Mock';
```

to
```
import { PrismaClient } from '@prisma/client';
import { mockDeep, DeepMockProxy } from 'jest-mock-extended';
```

**Comment by geromegrignon** [comment]
Hey @dborstelmann,

I already created a related PR #2533
