### ISSUE TITLE
Getting started with CockroachDB

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma2-docs#2557]

**Comment by tanberry** [comment]
@floelhoeffel  has pointed out that there is a need for a page explaining the diffs between PostgresSQL and CockroachDB... what works where, what doesn't work,, etc.

Before we create a separate page, though, I'd love to see how many items are on this list, how big is the delta? If it is only a few diffs, then we should look at simple adding qualifiers to the CockroachDB doc under "Add to an existing project". However, if there are large fundamental/conceptual differences (even if the technical details are not large) then Yes, I would agree a separate page is needed.

**Comment by thebiglabasky** [comment]
Those distinctions would fit well a database connectors page such as this one: https://www.prisma.io/docs/concepts/database-connectors/postgresql (ie add a CockroachDB one there)
The feature matrix would do too: https://www.prisma.io/docs/reference/database-reference/database-features

**Comment by tanberry** [comment]
Done thank you @keerlu ! https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-cockroachdb
