### ISSUE TITLE
Update the Database features matrix

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma2-docs#2560]
https://www.prisma.io/docs/reference/database-reference/database-features

**Comment by tanberry** [comment]
Also need to update "Supported Databases" at  https://www.prisma.io/docs/reference/database-reference/supported-databases

**Comment by tanberry** [comment]
The [Features Matrix page](https://www.prisma.io/docs/reference/database-reference/database-features) has tables that don't mention MongoDB, PlanetScale, nor Cockroach, and the tables are already too big. We need to think on how to represent that info in either smaller table or diff format.

**Comment by keerlu** [comment]
Database features was updated in PR #2815 
Updating other reference docs will be done as part of #2561
