### ISSUE TITLE
Heading should be "Interactive Transactions"

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2-docs#2576]
![image](https://user-images.githubusercontent.com/5013932/143010427-90739f0c-76a1-4914-b161-ab5da7f817b2.png)

I believe the heading should be called "Interactive Transactions" and it should appear in the menu on the right, and then "Example" should be probably a subheading or something

**Comment by janpio** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions-in-preview
https://www.prisma.io/docs/concepts/components/prisma-client/transactions#example

**Comment by ruheni** [comment]
This has been updated and is currently not relevant for now.
