### ISSUE TITLE
Internal links with anchors get a trailing slash added although it is not in the content

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2591]
https://www.prisma.io/docs/concepts/components/prisma-client/crud#include-a-filtered-list-of-relations

Code of first link there is:
```
<p class="paragraph">See <a href="/docs/concepts/components/prisma-client/relation-queries/#filter-a-list-of-relations">Working with relations</a> to find out how to ...
```
Note the trailng slash before the anchor of the link.

But actual Markdown is:
```
See [Working with relations](relation-queries#filter-a-list-of-relations) to find out how to  ...
```

So our link component seems to create a suboptimal link there. We should fix this.

**Comment by janpio** [comment]
(This possibly also applies to the dataguide codebase)

**Comment by janpio** [comment]
Unfortunately not really fixed by the PR.

**Comment by nilubava** [comment]
@janpio I cannot seem to reproduce this. Can you check again?

**Comment by janpio** [comment]
Indeed looking good now.
