### ISSUE TITLE
Please clarify what this means: "Prisma already tests query functions like findMany"

### ISSUE THREAD

**Issue by svg-crstl** [prisma/prisma2-docs#2604]
This line is from the [unit testing docs page](https://www.prisma.io/docs/guides/testing/unit-testing#example-unit-tests)

1. Can you please clarify what "already tests" means in this context? Is it recommended to write cases that check findMany, or is that unnecessary?
2. Should findFirst, findUnique be treated the same as findMany?

**Comment by ruheni** [comment]
Hey 👋

Thanks for raising this. The statement meant we extensively test Prisma Client's query methods to ensure they work correctly. The statement is not necessary, so I'll go ahead and remove it. 🙂

In case you're curious, you can find the tests we run here: https://github.com/prisma/prisma/tree/main/packages/client/tests/functional.

We also have an extensive article series that you might also find useful: https://www.prisma.io/blog/series/ultimate-guide-to-testing-eTzz0U4wwV
