### ISSUE TITLE
Docs DX: Doing a manual copy paste of a schema adds extra blank lines

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#2609]
Here is what happens when doing a copy of a schema from the docs
Here https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgres/
<img width="548" alt="Screen Shot 2021-12-03 at 17 51 43" src="https://user-images.githubusercontent.com/1328733/144641626-f9ddaadb-d86f-4637-8145-977a01d9b0d3.png">

<img width="461" alt="Screen Shot 2021-12-03 at 17 54 20" src="https://user-images.githubusercontent.com/1328733/144641541-f543c060-ee40-40a8-956b-af5f64aebba5.png">

There is one extra blank line after each line, which doesn't show if using the clipboard icon.

It seems many blocks don't have the copy-paste icon, for example
<img width="544" alt="Screen Shot 2021-12-03 at 17 52 07" src="https://user-images.githubusercontent.com/1328733/144641448-e07a1d3a-a56b-497c-8ccd-b73af268184c.png">
https://www.prisma.io/docs/concepts/components/prisma-schema/index-configuration

We should fix if possible or as an alternative have the clipboard icon on all blocks maybe?

Browser/OS: Firefox/macOS

**Comment by Jolg42** [comment]
If I manually remove from dev tools the line number the issue is fixed
Line number element
<img width="681" alt="Screen Shot 2021-12-06 at 12 08 40" src="https://user-images.githubusercontent.com/1328733/144835963-bdc17640-0138-4e14-96a2-6cbce40289ed.png">
Example of what it looks:
<img width="608" alt="Screen Shot 2021-12-06 at 12 08 32" src="https://user-images.githubusercontent.com/1328733/144836011-0aefd00e-e3c2-4780-91f5-6a98d3ce41e6.png">
<img width="467" alt="Screen Shot 2021-12-06 at 12 10 19" src="https://user-images.githubusercontent.com/1328733/144836135-9f0ef6af-7bcc-4b6f-ba07-450afe90d3e6.png">

**Comment by aqrln** [comment]
In Safari it copies the line numbers starting from the second line, like this:

```prisma
model Post {
2  id        Int      @id @default(autoincrement())
3  createdAt DateTime @default(now())
4  updatedAt DateTime @updatedAt
5  title     String   @db.VarChar(255)
6  content   String?
7  published Boolean  @default(false)
8  author    User     @relation(fields: [authorId], references: [id])
9  authorId  Int
10}
```

They don't visually appear selected though:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/4923335/145200970-2fd2ab30-e1b7-40a3-b5f4-7d42370db216.png">

**Comment by nilubava** [comment]
The issues with Firefox and Safari seems to be known issues, and I cannot find any proper solutions online too. So for now, I guess it's better to add 'Copy' functionality to all code blocks. We cannot remove the line numbers too.

@Jolg42 @nikolasburk What do you think?

**Comment by Jolg42** [comment]
👍🏼 I guess it's a good tradeoff for now, could you or someone else do a search / replace everywhere to have the Copy button where it is missing?

**Comment by nilubava** [comment]
I can do that
