### ISSUE TITLE
Update table in DB Ref section to add new DBs

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2611]
https://www.prisma.io/docs/reference/database-reference/database-features

Need to add MongoDB, PS, and Cockroach (soon). The table is already so wide that one has to scroll horizontally; let's consider collapsing all relational/SQL DBs into one column, keeping the markers for special considerations.

**Comment by ObamaTheLlama114** [comment]
Closed because this work has been done elsewhere since this issue was created
