### ISSUE TITLE
Clarify that referential actions do **not** trigger Prisma Client middleware

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma2-docs#2624]
Context: https://github.com/prisma/prisma/discussions/10655

Referential actions may trigger updates on the DB, but do not go through the Prisma Client meaning that Prisma Client middleware will not be called.

Possibly need to update one or both of
- https://www.prisma.io/docs/concepts/components/prisma-client/middleware
- https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions

**Comment by ruheni** [comment]
TODO
- Add a limitations section in the Middleware page that it's not triggered for Referential Actions
- Find a better way to add this in our docs

- Also double check for Prisma Client extensions

**Comment by janpio** [comment]
> * Add a limitations section in the Middleware page that it's not triggered for Referential Actions

Nothing Prisma Client related is triggered for Referential Actions, they are a database only construct (except when using `relationMode=prisma` of course - but then they are also a concept outside of the area tha middlewares are responsible for)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
