### ISSUE TITLE
Styling issues in Safari

### ISSUE THREAD

**Issue by valtism** [prisma/prisma2-docs#2639]
<img width="1060" alt="Screen Shot 2021-12-19 at 11 50 52 pm" src="https://user-images.githubusercontent.com/1286001/146675517-d7f3bada-c1c9-4324-b311-7e4696b1ad0e.png">

Just a note that the sidebar dropdown caret indicator is too low, and if scrollbars are enabled in macOS, the code snippets are unreadable.

Seems to only affect Safari

**Comment by meletj** [comment]
Fixed
