### ISSUE TITLE
Add example for "Prisma Invalidation Middleware" with Reddis

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2645]
In the Redwood community, there's a pretty nice example for a "Prisma Invalidation Middleware" with Reddis: https://community.redwoodjs.com/t/guide-power-of-graphql-caching/2624#prisma-invalidation-middleware-11

Since we have concrete guides for soft delete, logging and session data middlewares, I was wondering if we should maybe include this one as well. If we don't want to include the whole thing as a new page, maybe we could at least link out to it somewhere on the ["Middleware"-page](https://www.prisma.io/docs/concepts/components/prisma-client/middleware)?!

**Comment by ruheni** [comment]
Our community members have created caching middleware, which we also feature on the https://prisma.io/ecosystems page. For now, we'll point community members to the Ecosystems page to play with/ try out packages built by other community members. 

- https://github.com/rouzbehsbz/prisma-cache-middleware
- https://github.com/Asjas/prisma-redis-middleware
