### ISSUE TITLE
Add navigation between pages

### ISSUE THREAD

**Issue by LorenzoLeonardini** [prisma/prisma2-docs#2654]
I've started considering Prisma for one of my projects and therefore I was reading all the "Concepts" section of the website.
I feel like "Previous page"/"Next page" buttons should be added, because now the user experience is kind of bad if you want to read every page. Especially from mobile, where you have to scroll to the top, open the menu, scroll down to the next page link and get back to reading.

**Comment by sampl** [comment]
Sane here! I’m reading the docs front-to-back on mobile before beginning my first Prisma project, and it’s kind of hard to navigate.

**Comment by meletj** [comment]
Fixed by move to Docusaurus
