### ISSUE TITLE
Docs: update "Transactions" to make clear what options we support

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2662]
Add a new section at top that list the options, then break each section down with an example for each. Rename "Limitations" to be the normal Considerations section and list all notes there.

See https://github.com/prisma/docs/pull/2642 for good convo.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
