### ISSUE TITLE
Docs: update "Special Rules for referential actions" page

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2663]
Add a table showing the diff support for ref actions based on 1) which database, and 2) whether Prisma or the DB is managing referential integrity. Do general copy-editing for clarity, etc.

https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions/special-rules-for-referential-actions#self-relation-sql-server-and-mongodb

**Comment by tanberry** [comment]
@Weakky thanks for your help with this topic "last year"... I plan to get back to it and the great able you created this week. Will ask you to review the PR when it is ready.

**Comment by keerlu** [comment]
Closing this one, some will have been covered by general referential actions docs work for referential integrity GA recently and some will be by #4180
