### ISSUE TITLE
Upgrade Percy (snapshot tool) since the current version is deprecated.

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#2665]
Example: https://percy.io/6faef5e0/prisma-docs/builds/14820015/changed/837405415
>Heads up! The SDK used in this build is deprecated and no longer supported.  You can find SDK instructions to upgrade your SDK here.
https://docs.percy.io/docs/migrating-to-percy-cli

<img width="1173" alt="Screen Shot 2022-01-04 at 17 45 12" src="https://user-images.githubusercontent.com/1328733/148093533-bfd1c61c-53c0-4dc7-8251-2a291598fd5f.png">

See for Gatsby plugin
https://github.com/percy/gatsby-plugin-percy#upgrading

Looks like we could upgrade by following the steps mentioned in these links ⬆️

**Comment by peterondesign** [comment]
Thanks for spotting this @Jolg42. I assume we should also use the Gatsby plugin for the website build?

**Comment by Jolg42** [comment]
@peterondesign so the https://github.com/prisma/website-v8 is built using Next.js and I don't know what would be the setup.

**Comment by Robdel12** [comment]
Hey everyone! Percy dev here -- I'd totally recommend using the snapshot CLI command: https://docs.percy.io/docs/percy-snapshot#getting-started you can get _pretty_ far with it as it's fairly flexible.
