### ISSUE TITLE
Guides for Managed Database Services / Database Providers

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2667]
Most will just work, but some have special considerations (connection string, shadow database, foreign keys, ...) and even for the "just works" ones it would be beneficial to make this explicit in the docs.

Some options, alphabetical order:

PostgreSQL:
- Aiven: https://aiven.io/postgresql
- Alibaba Cloud: https://www.alibabacloud.com/help/en/doc-detail/95626.html
- Amazon RDS: https://aws.amazon.com/rds/postgresql/
- Azure: https://azure.microsoft.com/en-us/services/postgresql/
- Citus Data: https://www.citusdata.com/product/cloud
- Crunchybridge: https://www.crunchydata.com/products/crunchy-bridge/
- DigitalOcean: https://www.digitalocean.com/products/managed-databases/
- EnterpriseDB BigAnimal: https://www.enterprisedb.com/products/biganimal-cloud-postgresql
- Google Cloud: https://cloud.google.com/sql/postgresql/
- Heroku: https://elements.heroku.com/addons/heroku-postgresql
- Scalegrid: https://scalegrid.io/postgresql.html
- Scaleway: https://www.scaleway.com/en/database/
- Supabase: https://supabase.com/docs/guides/database

MySQL:
- Planetscale: https://planetscale.com/

And many more.

**Comment by phillvdm** [comment]
Could add:

- Neon (serverless): https://neon.tech/
- Tembo: https://tembo.io/docs
