### ISSUE TITLE
PostgreSQL/CockroachDB connection string

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2668]
https://github.com/prisma/prisma/issues/10805 added another field `options` that can be set and should be documented. Details about how this works in https://github.com/prisma/quaint/issues/338 and via the links in there.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
