### ISSUE TITLE
Data Model: Fix position of native database types

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2673]
Internal discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1641410019262700
Suggestion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1641464154001600?thread_ts=1641410019.262700&cid=C5Z9TH6N9

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
