### ISSUE TITLE
Put version and preview feature information to end of section instead of beginning

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2681]
Currently sections like https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#native-types-mapping start with a mention when the feature was added: `Version 2.17.0 and later supports native database type attributes (type attributes) that describe the underlying database type`.

To deemphasize this information (which usually is not relevant to the users with the latest version) we could instead move it to the end of the section. In this example the section could then start with` Native database type attributes (type attributes) describe the underlying database type: ...` and end with `(This functionality was added with version 2.17.0`). 
(As a side effect this would make it easier to actually include the full story, that it was added in version x with preview feature flag and stabilized in version 2.17.0)

(The wording could even become completely independent from the actual feature, and just be a common template we can activate via a component that takes the versions and preview feature flag as params and then just renders the text automatically - making maintenance of these much easier)

Note: While the feature is still only available via the preview feature (and we need the full instructions how to use the preview feature flag in the schema file), this would probably not be the optimal way to do things. But we could also separate the information about the preview feature and the functionality itself better already, to make it easier to later move to the end.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
