### ISSUE TITLE
Add link to "order by relevance" to full text search

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2682]
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#sort-post-by-relevance-of-the-title should be linked from https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search, optimally in an example similar to https://github.com/prisma/prisma/releases/tag/3.5.0 which shows how to combine order by relevance and full text search properly - the common use case for this.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
