### ISSUE TITLE
Document differences in optional uniques on MongoDB

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2695]
Basically document how null data is treated differently with @unique.

This comment contains context: https://github.com/prisma/prisma-engines/issues/2361#issuecomment-998294734

**Comment by ankur-arch** [comment]
Closing this as from my findings, `null` data can be inserted multiple times in a mongo db optional `unique` field.

**Comment by ankur-arch** [comment]
Closing this as from my findings, null data can be inserted multiple times in a mongo db optional unique field.
