### ISSUE TITLE
Nova editor plugin points to dead link

### ISSUE THREAD

**Issue by aetheryx** [prisma/prisma2-docs#2697]
https://www.prisma.io/docs/guides/development-environment/editor-setup#nova links to https://extensions.panic.com/extensions/robb-j/robb-j.prisma/
![image](https://user-images.githubusercontent.com/25572140/149007630-41138f37-aab7-4750-8472-0b73769a1104.png)

**Comment by janpio** [comment]
Real link is indeed https://extensions.panic.com/extensions/robb-j/robb-j.Prisma/ - which somehow our docs mess up.
