### ISSUE TITLE
Document full text search for MongoDB (Epic 3)

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2711]
Add MongoDB to the [full text search Concepts page](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search).

Related dev issue: https://github.com/prisma/prisma/issues/9413

**Comment by matthewmueller** [comment]
Full-text support for MongoDB isn't happening for GA

**Comment by keerlu** [comment]
Closing this old issue. Currently using #3350 to track the state of full text search and will create new issues as needed.
