### ISSUE TITLE
Document MongoDB embedded types

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2712]
This is a large feature that is coming up - adding an issue to track from the Docs side.

Relevant Client team epic: https://github.com/prisma/prisma/issues/8272

---

Dependencies:

- [x] https://github.com/prisma/docs/issues/2738
- [x] https://github.com/prisma/docs/issues/2729

**Comment by tanberry** [comment]
Some great resources are:
https://github.com/prisma/prisma/issues/6708: Some more ideas and feedback from the community.
[Internal Problem Document](https://www.notion.so/prismaio/MongoDB-Embedded-Documents-c9ad4c3220a946b2b52f2c339414bc1c): Discusses the problem in a bit more detail.
[Internal Solution Document](https://www.notion.so/prismaio/MongoDB-Embedded-Document-Access-4a8a04cd046c4bdf9665008df9c6288c): Discusses the solution in more detail.
(These are listed in the Prisma Issue #https://github.com/prisma/prisma/issues/8272.)

Also see the [Notion doc on using embedded types](https://www.notion.so/prismaio/Using-Embedded-Types-d1a008e84d76415dac9fc1d23432083a)

**Comment by loicnestler** [comment]
Hey there!
Is there any ETA for this feature?
Really looking forward to using prisma with MongoDB in production on a project!

**Comment by janpio** [comment]
Embedded documents were released as preview feature in 3.10.0: https://github.com/prisma/prisma/releases/tag/3.10.0 @loicnestler 
We do not communicate ETA for any features before they happen (as that usually does not end well). But we are looking for as many people as possible to test it, to make sure it is ready for production so any testing and feedback is welcome. Thanks.

**Comment by keerlu** [comment]
Closing this ticket as it's now a duplicate epic, the sub-issues will be tracked in #2905 instead.
