### ISSUE TITLE
Improve error handling documentation

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2713]
Currently we have [this error reference guide](https://www.prisma.io/docs/reference/api-reference/error-reference), and a short [guide to error handling in Concepts](https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors). 

The Client team are currently [working on improving error handling](https://github.com/prisma/prisma/issues/10747), so would be good to revisit as part of that.

Updated client issue: https://github.com/prisma/team-orm/issues/153

**Comment by andrew-walford-prisma** [comment]
I'll investigate this one

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
