### ISSUE TITLE
Improve visibility for the `in` operator 

### ISSUE THREAD

**Issue by TasinIshmam** [prisma/prisma2-docs#2732]
### Problem
The docs could possibly do a better job of showing that Prisma has an `in` operator for filtering/where conditions.

### Details
While this operator is shown in the [client reference](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#in), it's a bit hard to discover organically from there. 

I've come across quite a few questions where users have an appropriate use-case but aren't aware this operator exists ([example question](https://stackoverflow.com/questions/69857000/prisma-how-can-i-find-all-elements-that-match-an-id-list)). 

### Possible solution
We could add a few examples with the `in` operator in appropriate articles in the docs to improve its visibility. Possible locations:

- In the Read section of the [CRUD article](https://www.prisma.io/docs/concepts/components/prisma-client/crud#read). 
- In the [Filtering and Sorting](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting) article

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
