### ISSUE TITLE
`@unique` API reference missing description for `map` argument

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma2-docs#2741]
Brought to my attention in this [discussion](https://github.com/prisma/prisma/discussions/11232).

The user was referring to our [Prisma schema API reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#arguments-3).

![image](https://user-images.githubusercontent.com/32459922/150016622-677b3e81-0d5b-4039-a4ae-456421c02f5d.png)

Was the description left blank on purpose? If not, we should fill in that `map` controls the name of the unique constraint in the database.

**Comment by do4gr** [comment]
Yes, we can add that. That is what this does.

**Comment by morishin** [comment]
I found a description about that here: https://www.prisma.io/docs/concepts/components/prisma-schema/names-in-underlying-database#constraint-and-index-names

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
