### ISSUE TITLE
Add link to Prisma Migrate example for CI/CD

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#2744]
This following example posted on the blog is a good one for using Prisma Migrate in CI/CD
https://www.prisma.io/blog/backend-prisma-typescript-orm-with-postgresql-deployment-bbba1ps7kip5

Do you know where we can add it to Migrate docs?

I think later we would need a dedicated section and not only a link to the blog post. As it's quite an important part of using Migrate.

Example of user question
https://github.com/prisma/prisma/discussions/11131

**Comment by ruheni** [comment]
TODO:

- [x] Update https://www.prisma.io/docs/guides/deployment/deploy-database-changes-with-prisma-migrate with the example from the tutorial from Daniel
