### ISSUE TITLE
Document how you can use GENERATED to also compute fields

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2746]
Update https://www.prisma.io/docs/concepts/components/prisma-client/computed-fields to include https://github.com/nikolasburk/generated-columns as an alternative.

Context: https://prisma-company.slack.com/archives/C016KUHB1R6/p1642596993052200

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
