### ISSUE TITLE
Document how to escape SQL Server connection string parts

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2750]
See https://github.com/prisma/prisma/issues/11276#issuecomment-1017989820

**Comment by nadilas** [comment]
Hi, coming from the other issue I tried enclosing the special characters in `{}`, but it doesn't work. How is the documentation coming along?

**Comment by janpio** [comment]
If using `{...}` does not work, that is worth a real issue as that is indeed the way to do it.

**Comment by nadilas** [comment]
Actually it does work... sorry about that. I just needed to find the **correct** characters to escape 🤦‍♂️

**Comment by sweleck** [comment]
I'm sorry that I have to come here from the original issue as well. But with the {} escaping method, I still get a rejected connection. 
My URL looks like this.

`sqlserver://sqlserver;database=database;username=MyDomain{\}User;password={?}password{:}{!};trustServerCertificate=true
`
Is it correct to escape the backslash in the username as well?

**Comment by nadilas** [comment]
@sweleck i can take a look later but I think we’re using an sql user not a domain one. If only I documented the link for the list of characters… 🤓

**Comment by cmoscosoz** [comment]
Hey,
I'm having the same issue, trying to connect to a database,
sqlserver://database.windows.net:1433;database=database;user=username;password=P@$ssword123;trustServerCertificate=true 
but still getting an error.

I tried: `password={P%40%24ssword123}`, `password=P{%40}{%24}ssword123` , `password=P%40%24ssword123` and still doesn't work.

**Comment by cmoscosoz** [comment]
solved my case doing `password={P@\$ssword123}` I had to add `\` to scape `$` in the env variable in nextjs.
