### ISSUE TITLE
Prisma + Electron

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2751]
(Low priority)

Seems Prisma is a good solution for DB access in Electron. We have a bunch of issues where users share how they made it work for them (and also the problems they hit), so having a guide that collects that information and possibly shows an example could be quite useful to deepen that position.

Here are all the related issues: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+electron%22+sort%3Aupdated-desc (also check the closed ones potentially)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
