### ISSUE TITLE
Update Prisma schemas created via Introspection from provided SQL

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2752]
In some pages we provide the SQL, and then the supposed Introspection result. Example: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/introspection-typescript-postgres 

We should revisit all of these to make sure the introspected schema actually represents the SQL that is provided. The example above for examples seems to be missing the referential actions definitions a user would see if they follow this tutorial. 

Small differences like these can cause confusion and make it harder to build a mental model you can trust during the tutorial.

(Searching for `CREATE TABLE` might be a good way to find all ways in the docs where we have SQL to create a table to later be introspected)

**Comment by ruheni** [comment]
Validate SQL is proper for different dbs & update them
