### ISSUE TITLE
MySQL: Document limitation around `0000-00-00 00:00:00`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2755]
Context: https://github.com/prisma/prisma/issues/5006

1. Limitation and reasoning
2. Suggestion on how to fix/workaround/change

Information: 
https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
