### ISSUE TITLE
Some of the relations links are returning 404

### ISSUE THREAD

**Issue by shmuelsochet** [prisma/prisma2-docs#2756]
The following 3 links in the [relations](https://www.prisma.io/docs/concepts/components/prisma-schema/relations) section are returning a 404.

![image](https://user-images.githubusercontent.com/26887125/150661751-86f35d98-152a-42d9-ba8d-02c8918675bc.png)

https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/self-relations

**Comment by EmmanuelDemey** [comment]
I can access to those pages.

**Comment by janpio** [comment]
Same here. Can you share a screenshot of the 404 you are getting please @shmuelsochet?

**Comment by shmuelsochet** [comment]
Thank you. I have access now. It looks like it was due to a filter setting, my apologies.

Here's the page I was getting 

![Uploading image.png…]()
