### ISSUE TITLE
Redirects for link anchors

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2757]
Example why this would be useful: https://github.com/prisma/prisma/pull/11338

**Comment by tanberry** [comment]
> Currently you can not redirect anchor links. The part behind # is never sent to the server... we definitely need to be able to redirect from a specific anchor link. 

Example: https://github.com/prisma/website-v8/pull/432

**Comment by janpio** [comment]
Related: https://github.com/prisma/docs/issues/1648

**Comment by tanberry** [comment]
@nilubava met with Docs team to discuss; proposal is that she creates a new Typescript component to handle this.We will have to also add the redirect to the config.js file, as well. So a different way to handle redirects that normal(website-v8) but it is what we have for now.

Example file with anchor that we need to redirect: 
FROM: /concepts/components/prisma-data-platform#prisma-data-proxy
TO: /concepts/data-platform/data-proxy
