### ISSUE TITLE
Add info about friction points when using a DB hosted via Supabase (maybe even write Guide)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2762]
I [learned from a user](https://twitter.com/TjChear/status/1485611260817252355) that there a some special things to be aware of when hosting your DB with Supabase, I think it would be great to mention these friction point somewhere in the docs:

1) supabase db has grants/privileges/etc setup 
2) prisma wipes them out when migrate reset/dev. 
3) postgresql auto lower cases table name in query 
4) no logs from local supabase - hard to debug failing triggers
5) prisma doesn't use uuid_generate_v4

It might even be worth to write a guide about hosting a DB on Supabase and how to use Prisma with it.

**Comment by janpio** [comment]
Related: https://github.com/prisma/docs/issues/1864 + https://github.com/prisma/docs/issues/2667

**Comment by ruheni** [comment]
TODO: Add content contained in https://supabase.com/docs/guides/integrations/prisma#troubleshooting to our docs.
