### ISSUE TITLE
MDBGA: Document an upgrade path for P1 MongoDB users (Epic 3)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2767]
- Does introspection work for P1 users?
- Did P1 make any assumptions about relations that are invalid for P2 users?

**Comment by matthewmueller** [comment]
Start with basic documentation covering how to upgrade from Prisma 1's MongoDB implementation to Prisma 2's MongoDB implementation. Might need to be expanded as more people ask questions.

We should start working on this after we have Embedded Documents in Preview: https://github.com/prisma/prisma/issues/8272

**Comment by janpio** [comment]
Note:
- P2 Introspection will definitely miss comments and some embedded types names as they are not represented in the MongoDB database

**Comment by do4gr** [comment]
Many to many relations were implemented as one-way embedded in Prisma 1 and I believe we allowed relations emanating from embedded types to non-embedded ones.  So these would be two types of relations we could currently not handle.

**Comment by Jolg42** [comment]
TODO

Once docs are done, reminder to update this PR and merge it to have the short link active
https://github.com/prisma/pris.ly/pull/47

**Comment by matthewmueller** [comment]
I'll be taking this one
