### ISSUE TITLE
Link to `#prisma-data-platform` Slack channel is broken

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2775]
In the docs here: https://www.prisma.io/docs/concepts/components/prisma-data-platform#feedback-and-support

![image](https://user-images.githubusercontent.com/4058327/151370355-0befb12a-b8e5-4823-b6b6-ebfe682bb16b.png)

Related Slack convo: https://prisma.slack.com/archives/CA491RJH0/p1643290256069900

![image](https://user-images.githubusercontent.com/4058327/151370414-c0b309f8-e779-4121-8f43-3166764f7773.png)

**Comment by zachtil** [comment]
This has already been resolved. Closing.
