### ISSUE TITLE
Section "Concepts" is closing unexpectedly!!

### ISSUE THREAD

**Issue by valerii15298** [prisma/prisma2-docs#2783]
https://user-images.githubusercontent.com/44531564/151677088-e326c166-dc2e-4310-8f97-c9b6a3257adf.mp4

Very annoying problem, cannot read docs normally. Using phone, open https://www.prisma.io/docs/ , then click docs->concepts and try to scroll, and it will be automatically be closed. Very uncomfortable user experience!
I'm using Redmi note 8, chrome 97.0...., Android 11

**Comment by tanberry** [comment]
Oooof, yes, that was very rude of the docs mobile site. Thank you @valerii15298 for bringing this to our attention! @nilubava let's we add this to our next chat. :-)

**Comment by valerii15298** [comment]
@tanberry Another bug: when open section "guides" or "reference" and continue to scroll, it unexpectedly closes open section and opens "concepts". In general I see, when scrolling, it opens section "concepts" unexpectedly every time.
