### ISSUE TITLE
Document how to migrate and deal with inconsistent data when your schema changes in MongoDB (Epic 3)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2794]
How you migrate old data to new schemas is more complicated than SQL. In SQL, the integrity is maintained throughout all your past data, (e.g. if your zip code is an int column, all stored zip codes are ints). 

In MongoDB, this is not the case. You could start sending zip codes as strings and MongoDB will be happy as a clam. There's a number of strategies for dealing with this "feature":  https://github.com/prisma/prisma/issues/7305

We should document a few common scenarios that people will face and guide them through it.

**Comment by dgradwell-ams** [comment]
MongoDB has built-in json schema support. Perhaps this could be used to check consistency.

**Comment by tanberry** [comment]
Covered this topic in https://github.com/prisma/docs/pull/3017

**Comment by matthewmueller** [comment]
Closed by: https://github.com/prisma/docs/pull/3017
