### ISSUE TITLE
Add note to SQLite connector docs why no native type mappings are available

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2803]
This question came up on Slack: https://prisma.slack.com/archives/CA491RJH0/p1643709456587499

![image](https://user-images.githubusercontent.com/4058327/151954928-da6c9a6e-cd05-4ddc-8a11-e7f40582e11e.png)

Related internal convo: https://prisma-company.slack.com/archives/CEYCG2MCN/p1643711920045469

**Comment by Nathy-bajo** [comment]
Thanks.

**Comment by tanberry** [comment]
Link to SQLite docs here: https://www.sqlite.org/datatype3.html ... though not 100% sure that we should link to it. We want to keep external links to a minimum.

**Comment by Nathy-bajo** [comment]
I see, alright then.

**Comment by janpio** [comment]
The posted link is the correct SQLite documentation to explain and show that there are not additional types to support.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
