### ISSUE TITLE
CockroachDB doc updates needed

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2805]
This issue is for collecting additional content we need to add to the Cockroach docs. (Please edit this section to add new items.)

1.  Add information about the default behaviour of `autoincrement`  starting at a high number by default (example: 732823402838327297) when doing a Prisma Client query or manual insert.
[Link to relevant CockroachDB docs. ](https://www.cockroachlabs.com/docs/stable/serial.html#generated-values-for-modes-rowid-and-virtual_sequence)
For details, see [this Slack convo.](https://prisma-company.slack.com/archives/C02K246T9RQ/p1643710981051909)
2. <tbd>

**Comment by ruheni** [comment]
Closed via https://github.com/prisma/docs/pull/2830
