### ISSUE TITLE
Replace `@default(dbgenerated())` with `@default(auto())` for MongoDB

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2816]
This will involve

- Replacing `@default(dbgenerated())` with `@default(auto())` in MongoDB examples
- Updating the schema reference to include `auto()` as well as `dbgenerated()`

See Slack thread [here](https://prisma-company.slack.com/archives/C4GCG53BP/p1643819603958069) 

Related dev issues:  https://github.com/prisma/prisma-engines/pull/2648 and https://github.com/prisma/prisma/issues/11552

**Comment by pimeys** [comment]
Also document what it does. See what @tomhoule wrote in the issue.

**Comment by keerlu** [comment]
> Also document what it does. See what @tomhoule wrote in the issue.

Yes, this will be covered in the schema reference, right?

**Comment by matthewmueller** [comment]
This one is ready to be documented: https://github.com/prisma/prisma/issues/11552#issuecomment-1033012569
