### ISSUE TITLE
Document `--transpile-only` flag for seed script

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#2823]
Thanks to Chris for mentioning that https://github.com/prisma/docs/pull/2787

`--transpile-only` see https://github.com/TypeStrong/ts-node#transpilers
>In transpile-only mode, we skip typechecking to speed up execution time.

Chris mentions that
> Failing to use the --transpile-only flag in some contexts is a catastrophic mistake that consumes massive amounts of RAM when typechecking the seed script(s) unnecessarily, in addition to transpiling them, thereby completely crashing Node in any container with limited RAM i.e. Docker, Heroku, etc. when trying to seed.

After discussing with @aqrln we came to the conclusion that we would like this to be documented but would not make it the default command like in the original PR.

This issue is then about mentioning ts-node's flag `--transpile-only` on seeding page https://www.prisma.io/docs/guides/database/seed-database#seeding-your-database-with-typescript-or-javascript

**Comment by Jolg42** [comment]
Maybe this would do
```
ts-node does transpiling and typechecking by default, typechecking can be disabled with `--transpile-only` if you want to have a faster and less resource (CPU/RAM) intensive seeding script. 
```

**Comment by tanberry** [comment]
Oh, I do like that wording, @Jolg42 . I didn't see it until after I edited Chris' PR... with my own wording. I might go back and add yours in.

I'm closing this Issue since we agreed to use Chris' [edited] PR.
