### ISSUE TITLE
2-way Embedded Many-to-Many Relations in MongoDB

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma2-docs#2847]
In Prisma 3.10.0 we will change a bit how m:n relations work in MongoDB databases. Previously we had a bit hacky solution with no defined rules that kind of worked:

```prisma
model A {
  id    String   @id @map("_id") @default(auto()) @db.ObjectId
  b_ids String[] @db.ObjectId
  bs    B[]      @relation(fields: [b_ids])
}
    
model B {
  id    String   @id @map("_id") @default(auto()) @db.ObjectId
  a_ids String[] @db.ObjectId
  as    A[]      @relation(fields: [a_ids])
}
```

This assumes we implicitely refer to the `id` field on the referenced model and we had no validation or rules how they actually work. From 3.10.0 on we finalize the design, test it thoroughly and we should reflect that in our documentation. The new design looks like this:

```prisma
model A {
  id    String   @id @map("_id") @default(auto()) @db.ObjectId
  b_ids String[] @db.ObjectId
  bs    B[]      @relation(fields: [b_ids], references: [id])
}
    
model B {
  id    String   @id @map("_id") @default(auto()) @db.ObjectId
  a_ids String[] @db.ObjectId
  as    A[]      @relation(fields: [a_ids], references: [id])
}
```

As you can see the m:n `@relation` attribute got a new mandatory argument `references`. This syntax is only allowed on MongoDB and we validate it with the following rules:

-   Both sides of the relation must be arrays (in the data model the fields `as` and `bs`).
-   The `@relation` attribute must define `fields` and `references` arguments
-   The `fields` argument must have only one scalar field defined, this scalar field must be of an array type.
-   The `references` argument must have only one scalar field defined, this scalar field must exist on the referenced model and must be of the same type as the scalar field in the `fields` argument, but singular (no array).
-   The scalar field where `references` points to must be an `id`.
-   No referential actions are allowed in this kind of relations (yet, support only after GA)
-   The implicit m:n relations as seen in SQL databases are not allowed with MongoDB.

Pull request where this was merged: https://github.com/prisma/prisma-engines/pull/2671
Issue where this was requested: https://github.com/prisma/prisma/issues/11553

If any questions, mainly direct them to @pimeys or if not available, to @tomhoule.

**Comment by tanberry** [comment]
Thank you @pimeys !

**Comment by tanberry** [comment]
Docs to be updated:
1. The tab for MongoDB needs to be updated here: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/self-relations#many-to-many-self-relations
2.  This section on MongoDB doesn't yet mention `references` https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb - done in PR 2917
3. https://www.prisma.io/docs/concepts/components/prisma-schema/relations#relation-fields
