### ISSUE TITLE
where clause confusing

### ISSUE THREAD

**Issue by pkellner** [prisma/prisma2-docs#2862]
on the page where you explain filtering of nested tables, you really should have a where clause for the nested relation. Took me a long time to figure it out.

That is this:

```
const result = await prisma.user.findMany({
  where: {
    email: {
      contains: 'prisma.io',
    },
  },
  select: {
    posts: {
      where: {
        published: false,
      },
      orderBy: {
        title: 'asc',
      },
      select: {
        title: true,
      },
    },
  },
})
```

should include a

```
const result = await prisma.user.findMany({
  where: {
    posts: {
      title: {
        contains: 'im lost'
      }
    }
    email: {
      contains: 'prisma.io',
    },
  },
  select: {
    posts: {
      where: {
        published: false,
      },
      orderBy: {
        title: 'asc',
      },
      select: {
        title: true,
      },
    },
  },
})

**Comment by ruheni** [comment]
👋

Thanks for the suggestion. Each example or concept on the page is isolated and you can combine some of them together. The example you've suggested is a combination of [relation filters](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#relation-filters) and a [filters on a list of relations](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#filter-a-list-of-relations).

We also recently updated the examples on the page to remove filters that were not relevant to the example.

Please feel free to reopen the issue or create another one if you have any more feedback for the page. 🙂

**Comment by pkellner** [comment]
I'd suggest having a "combination" page.  May be obvious to you they combine (and me now), but not to new users of the tech.

**Comment by ruheni** [comment]
Much appreciate the feedback. I've created an issue to track it — #4793
