### ISSUE TITLE
Integration testing with an in-memory database

### ISSUE THREAD

**Issue by nukeop** [prisma/prisma2-docs#2863]
I'm referring to this page: https://github.com/prisma/docs/blob/main/content/300-guides/150-testing/150-integration-testing.mdx

It describes integration testing using a docker image which the tests write to and read from. It works but it's cumbersome and resource-intensive. A simpler approach would be to use an in-memory database (such as https://www.npmjs.com/package/mongodb-memory-server for Mongo). I could document this and open a pull request - would it be helpful?

**Comment by janpio** [comment]
If that indeed works, that might be an interesting approach indeed. 
A writeup here in the issue would be a good first step before we make changes to the docs.

**Comment by nukeop** [comment]
I looked into it but it's hard (or impossible) to set up a replica set using mongodb-memory-server that will also satisfy Prisma's requirements.

I will revisit this once Prisma support is implemented in pg-mem: https://github.com/oguimbal/pg-mem/issues/27

**Comment by AryanJ-NYC** [comment]
> I'm referring to this page: https://github.com/prisma/docs/blob/main/content/300-guides/150-testing/150-integration-testing.mdx
> 
> It describes integration testing using a docker image which the tests write to and read from. It works but it's cumbersome and resource-intensive. A simpler approach would be to use an in-memory database (such as https://www.npmjs.com/package/mongodb-memory-server for Mongo). I could document this and open a pull request - would it be helpful?

Did this documentation ever get posted or written?

**Comment by nukeop** [comment]
I could never get this to work, so there was nothing to write.

**Comment by ruheni** [comment]
👋

Thanks for looking into this @nukeop. In the meantime, I'll go ahead and close the issue. In the event you make progress, your contribution to the docs will be welcome. Feel free to reopen the issue then. 🙂
