### ISSUE TITLE
Duplicate content in Prisma schema -> Relations

### ISSUE THREAD

**Issue by hymair** [prisma/prisma2-docs#2864]
"Terminology" and "Relation fields" have some duplicated content which is confusing.

https://www.prisma.io/docs/concepts/components/prisma-schema/relations#terminology
https://www.prisma.io/docs/concepts/components/prisma-schema/relations#relation-fields-1

**Comment by ruheni** [comment]
👋

Could you clarify what the duplicated content on the page is? That would be much appreciated. 🙂

**Comment by hymair** [comment]
From the looks of it content changed a lot since I opened this ticket and I don't even see the anchors I linked. Closing.
