### ISSUE TITLE
`PRISMA_CLIENT_ENGINE_TYPE=dataproxy npx prisma generate` doesn't work with Powershell

### ISSUE THREAD

**Issue by katungi** [prisma/prisma2-docs#2868]
Hello, 

When going through the documentation to deploy to [cloudflare workers](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers), running `PRISMA_CLIENT_ENGINE_TYPE=dataproxy npx prisma generate` on Windows Powershell (and possibly CMD) fails with the following error:

![image](https://user-images.githubusercontent.com/33921841/154291402-6b1602f7-6783-452e-8fe6-31d844180b50.png)

A possible fix to this, as discovered by @ruheni, would be to use this command when using Powershell( or CMD):

```powershell
$env:PRISMA_CLIENT_ENGINE_TYPE='dataproxy'; npx prisma generate
```

**Comment by janpio** [comment]
The command mentioned there is generally not compatible with Windows at all.
In `Cmd` you would need to `set PRISMA_CLIENT_ENGINE_TYPE=dataproxy && npx prisma generate`.

**Comment by ruheni** [comment]
I think adding more tabs for Windows in the docs would help. :)

**Comment by ruheni** [comment]
The guide has been updated to use `npx prisma generate --data-proxy` instead of setting an environment variable.

I did a quick search in our docs and we're not using that pattern anymore to generate Prisma Client for Data Proxy. I'll go ahead and close this issue.
