### ISSUE TITLE
Reusable MDX snippets with variables

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#2869]
https://www.notion.so/prismaio/Reusable-content-single-sourcing-58dfb435d8544a558662a6e8c19f01b6

**Comment by jharrell** [comment]
IIUC, this task was about being able to re-use snippets of content on multiple pages. 

Docusaurus supports [importing markdown](https://docusaurus.io/docs/3.5.2/markdown-features/react#importing-markdown) which should mean this is no longer required.
