### ISSUE TITLE
Clipping in Headline

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma2-docs#2870]
<img width="575" alt="Screen Shot 2022-02-16 at 15 24 57" src="https://user-images.githubusercontent.com/16278407/154289806-5e36209c-484d-4534-86bf-d173d408d271.png">

https://www.prisma.io/docs/guides/database/production-troubleshooting

Comment from Peter: Looks like we need to increase the line-height of h2.

**Comment by nilubava** [comment]
Check after tailwind is removed in lens
