### ISSUE TITLE
MongoDB: No more `@db.Array`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2871]
`@db.Array` is no more, but we now also just use the list indicator on the scalar type and the native type stays in its singular form.

![image](https://user-images.githubusercontent.com/183673/154297060-5ae696e4-25ac-4345-935b-0f013880bc81.png)

**Comment by keerlu** [comment]
i.e.:
`String @db.Array(String)`  or `String[] @db.Array(String)` goes to `String[]`
`String @db.Array(ObjectId)`  or `String[] @db.Array(ObjectId)` goes to `String[] @db.ObjectId`

**Comment by janpio** [comment]
PR that covers some of the cases found via search: https://github.com/prisma/docs/pull/2824

**Comment by keerlu** [comment]
Closed via PR https://github.com/prisma/docs/pull/2824
