### ISSUE TITLE
Remove or reword Admonition about Prisma Migrate not supporting MongoDB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2876]
It _is_ supported via `db push`, just works different via `db push`.
We should present that in a much better way, especially as people understand `db push` to be part of "Prisma Migrate" as well.

Wrong:
https://www.prisma.io/docs/guides/database/prototyping-schema-db-push
https://www.prisma.io/docs/concepts/components/prisma-migrate/db-push

Unclear:
https://www.prisma.io/docs/concepts/overview/what-is-prisma/data-modeling#using-prisma-client-and-prisma-migrate
https://www.prisma.io/docs/concepts/components/prisma-migrate/supported-types-and-db-features
https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database
https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#mongodb-connector-not-supported
https://www.prisma.io/docs/concepts/components/prisma-migrate

**Comment by janpio** [comment]
Also: https://prisma.io/docs/concepts/database-connectors/mongodb#known-limitations

And also:
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/team-development
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/enable-native-database-functions
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/include-unsupported-database-features
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations
https://prisma.io/docs/guides/database/developing-with-prisma-migrate/troubleshooting-development
https://prisma.io/docs/guides/database/developing-with-prisma-migrate
https://prisma.io/docs/guides/deployment/deploy-database-changes-with-prisma-migrate

**Comment by keerlu** [comment]
This looks to have been fixed via #2937
