### ISSUE TITLE
Update MongoDB m:n relation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2877]
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb

- Typo: include => including
- No more `@db.Array`
- Requires a `@relation attribute on each side` (already in the text) with `fields` and `references` (currently missing in text and example)

Also: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/self-relations#many-to-many-self-relations

**Comment by ruheni** [comment]
This has already been updated. I'll go ahead and close the issue.
