### ISSUE TITLE
Clarify documentation for the `$on` method

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma2-docs#2888]
The wording for the `prisma.$on` method could be improved. [This user](https://github.com/prisma/prisma/discussions/11580) was confused and tried to use it to subscribe to a custom Postgres event.

[Docs currently read like this](https://github.com/prisma/prisma/discussions/11580):

> The $on() method allows you to subscribe to events. With those you can subscribe to [logging events](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#log) or the [exit hook](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-management#exit-hooks).

We could mention those are the only two instances where you can use `$on` and maybe provide the examples inline.

**Comment by ruheni** [comment]
(Add Note: Check out Pulse for subscribing to database events)
