### ISSUE TITLE
Incorrect redirection in Raw database access links for executeRaw, queryRaw, runCommandRaw 

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#2893]
In this section of [Prisma Client API reference](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#executeraw), Raw database access links doesn't redirect to correct section and instead jumps to end of the page.

The issue is in the casing of the links due to which appropriate section is not found on page.
Example - Clicking on Raw Database Access link in executeRaw redirects to

https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#executeRaw

but actually it should redirect to

https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#executeraw

(capitalised `R` needs to be replaced with smallercase `r`)

Similar issue is in queryRaw and runCommandRaw. 

<img width="732" alt="Screenshot 2022-02-17 at 5 00 21 PM" src="https://user-images.githubusercontent.com/13049676/154473346-5a1fafc2-50be-4ddd-88bb-1d0d28e8ecb9.png">

**Comment by keerlu** [comment]
This one was fixed by #2894
