### ISSUE TITLE
Confirm default databases are documented

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2896]
For relational databases Prisma defaults to specific database names if non is provided in the connection string:
- MySQL: `mysql`
- PostgreSQL: `postgres`
- SQL Server: `master`
- SQLite: n/a

We should make sure that is documented on the connector pages, similar to the default schema `public` for PostgreSQL.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
