### ISSUE TITLE
MongoDB: update supported versions

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2903]
We have tested and support version 4.2 and later. Will need to update several places in docs.

**Comment by nurul3101** [comment]
- [ ] Remove all references of MongoDB versions from docs

**Comment by janpio** [comment]
That sounds a bit overly eager. We do not support older versions, so we have to mention those or which versions we start supporting MongoDB.

**Comment by jharrell** [comment]
This was already completed https://github.com/prisma/docs/blob/c573724bb66638b71ea59e9b23adc8f278ab4279/content/400-reference/300-database-reference/03-supported-databases.mdx#L31-L32
