### ISSUE TITLE
MongoDB docs: Epic 2

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2905]
This epic covers MongoDB docs work that needs to be completed as soon as possible, because the code has already been released or will soon be.

Issues in this epic are:

 - [x] #2738 
 - [x] #2540
 - [x] #2475
 - [x] #2780
 - [x] #2939

Lucy edit 30 Jun: removed #2729 from the checklist. This will be tackled later as part of full text work.

**Comment by keerlu** [comment]
Closing as #2729 has been moved out of this epic and everything else is done.
