### ISSUE TITLE
Inconsistent code highlighting in many-to-many relations code snippet  

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#2911]
In model `Post` field `categoryIds` should not be highlighted and instead data type `string[]` should be highlighted to make formatting consistent with other code examples/snippets.

Similarly In model `Category` field `postIds` should not be highlighted and data type `string[]` should be highlighted.

<img width="768" alt="Screenshot 2022-02-21 at 1 22 56 PM" src="https://user-images.githubusercontent.com/13049676/154911534-508d3794-7f97-4e59-9575-85d62b1d541e.png">

Here is a link to [documentation section](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb)

**Comment by keerlu** [comment]
We've ended up with a couple of duplicates of this issue, so I'll close this one and it can be tracked under #2476  - I've also added a comment asking if we can bump this one up the list a bit!
