### ISSUE TITLE
Document that we're using Cloudflare's DNS (1.1.1.1) to resolve MongoDB connection strings on Windows

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2915]
We fixed windows connection slowness by hardcoding Cloudflare's DNS in the driver. We should document this somewhere. I'm less sure of the potential pitfalls of doing this and not even sure those pitfalls should be documented, but ask @pimeys for details there.

More Details around the issue itself: https://github.com/prisma/prisma-engines/pull/2694

**Comment by janpio** [comment]
Good location would be the MongoDB connector page, some new headline "Notes" or similar that lists thigns that are special/werid/worth to know here.

I think this is scoped to a specific type of connection string, that is becoming more and more common though and is standard on MongoDB. 

Here is the upstream issue that describes it in the library repo it: https://github.com/bluejekyll/trust-dns/issues/1636 There is now also movement, so might not be a problem for long but just go away.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
