### ISSUE TITLE
Suggestions for MongoDB "Getting Started Guide"

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2916]
I have a few suggestions for the MongoDB "Getting Started Guide"

### Improve the Prisma schema

The Prisma schema that's currently used looks as follows:

```prisma
model Post {
  id       String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  slug     String    @unique
  title    String
  body     String
  comments Comment[]
  user     User      @relation(fields: [userId], references: [id])
  userId   String    @db.ObjectId
}

// Comments contain a comment string and connect back to the post.
// postId must have @db.ObjectId to match up with Post's id type
model Comment {
  id      String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  post    Post   @relation(fields: [postId], references: [id])
  postId  String @db.ObjectId
  comment String
}

model User {
  id    String  @id @default(dbgenerated()) @map("_id") @db.ObjectId
  email String  @unique
  name  String?
  posts Post[]
}
```

I have two main suggestions to improve this.

#### Remove the `Comment` model

IMO, the `Comment` model doesn't add much value compared to the [canonical `User`/`Post` models](https://www.prisma.io/docs/about/prisma-docs/about-the-docs#the-user-and-post-data-model) we typically use in our schema examples. It doesn't introduce any new concepts because it also only shows a one-to-many relationship which readers can already learn by looking at the `User`<->`Post` relation. So in its current form, it seems to add noise without providing educational value. Note that this would be different if the model would show how to use a 1-1 relation or m-n relation.

#### Add an embedded document

With today's release, Prisma introduces support for MongoDB's embedded documents. Since embedded documents are a fundamental concept in MongoDB, I think it might make sense to include them in the "Getting Started Guide" already. This could for example be an `Address` type that's being added to the `User` model.

### Remove the initial warning box

We currently have a warning on top of the guide that looks as follows:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/4058327/155091987-07776710-a576-4890-a7b9-fb09a1205611.png">

It should probably be updated to remove the note that we don't support introspection on MongoDB. Further, I wonder if we need to  point out that _migrations_ are not supported. Mostly because the _concept_ of migrations doesn't really apply to MongoDB in the first place (unless we're talking about _data migrations_, but these are currently not possible with Prisma Migrate either) and it's questionable what Prisma Migrate support for MongoDB actually would look like. So we can probably get rid of the entire warning box?

### Remove `await prisma.$connect()` ƒrom script

The initial, empty script that will show how to send Prisma Client queries currently uses `prisma.$connect()`. IMO, this doesn't provide any value and according to the ["progressive disclosure of complexity"](https://www.jason.af/progressive-disclosure-of-complexity/) principle should be removed. iirc, we used to have an internal conversation about this already and decided against showing `prisma.$connect()` in any "getting started code".

**Comment by janpio** [comment]
> It should probably be updated to remove the note that we don't support introspection on MongoDB. Further, I wonder if we need to point out that _migrations_ are not supported. Mostly because the _concept_ of migrations doesn't really apply to MongoDB in the first place (unless we're talking about _data migrations_, but these are currently not possible with Prisma Migrate either) and it's questionable what Prisma Migrate support for MongoDB actually would look like. So we can probably get rid of the entire warning box?

Big +1 on that - I _think_ I had actually created a PR to do that or started a discussion to do that.

**Comment by tanberry** [comment]
I'd also like to either clean up or remove the screenshots of Compass in the Introspection page (https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/mongodb/introspection-typescript-mongodb). If we chose to keep them, we need to remove the border showing the desktop, and just show the Compass UI.
