### ISSUE TITLE
Improve docs for Prisma Migrate workflows in CI/CD

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2918]
Based on this internal conversation: https://prisma-company.slack.com/archives/CGMCB82N8/p1645634453060249

<img width="397" alt="image" src="https://user-images.githubusercontent.com/4058327/155366119-a6b5e786-228a-4af2-8f25-cd66895f56cd.png">

<img width="881" alt="Screen Shot 2022-02-23 at 10 49 46" src="https://user-images.githubusercontent.com/5479270/155366781-cbd5a68a-ffb9-4155-bd74-b194c3dc96bd.png">

**Comment by ruheni** [comment]
Closing this in favor of #2744
