### ISSUE TITLE
Document use of new primitives in squashing and managing migrations

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2920]
This needs to be documented in a similar way to the recent documentation of using `migrate diff` and `db execute` to fix failed migrations: https://www.prisma.io/docs/guides/database/production-troubleshooting#fixing-failed-migrations-with-migrate-diff-and-db-execute

Need to think about where to put it - doesn't seem like enough for a top-level guide.

For more info on squashing migrations see the Notion docs [here](https://www.notion.so/prismaio/Squashing-Migrations-1947da0ede5347508c7f953805a0004b#a57c7cb581f14e4880c1581343120c7a).

Prisma Issue[ #12136](https://github.com/prisma/prisma/issues/12136)

[Docs drafts in Notion](https://www.notion.so/prismaio/Squash-commands-draft-for-docs-5f0a9661c6714683bcb9bfeb730561bb).

**Comment by tanberry** [comment]
![squash-notes-1](https://user-images.githubusercontent.com/9368837/158402928-105096f3-bca5-4f44-b489-dfbbfb8cbc9b.jpg)
![squash-notes-2](https://user-images.githubusercontent.com/9368837/158402940-2fa73bf4-b892-4c5f-8321-fca1cad597ab.jpg)
![squash-notes-3](https://user-images.githubusercontent.com/9368837/158402945-a4191de7-587a-4684-9166-783ba2a4e24c.jpg)
