### ISSUE TITLE
Add info on how interactive transactions work under the hood

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2922]
Twitter asked the question of what is the magic under the hood: https://twitter.com/alexdotjs/status/1496620630346711040

Impacted docs include:
--https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions-in-preview

See details in this thread: https://prisma-company.slack.com/archives/C1FPU5FPT/p1645711076911939

**Comment by garrensmith** [comment]
The code documentation I wrote for interactions is very in-depth and very much subject to change over the life of interactive transactions. But there are some things that should stay the same. So a more broader overview of how interactive transactions work is below:

Interactive transactions work by creating or acquiring a database connection and assigning a transaction id (itx) to that connection. That connection is kept open for the lifetime of the interactive transaction and dedicated to only that specific interactive transaction. Each database query for the specific interactive transaction will be routed to go through that connection. Once the interactive transaction is finished either by committing or rolling back, the connection will be returned back to the connection pool to be used for the next database operation. 

Some things to consider when using interactive transactions: 
- If you have a connection pool of say 10, and you run 15 interactive transactions at once, 10 will be processed immediately and the other 5 will wait until there is an available connection. 
- If there isn't an available connection with in the set timeout time, the interactive transaction will fail.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
