### ISSUE TITLE
Document views workaround for MongoDB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2923]
https://www.prisma.io/docs/guides/database/advanced-database-tasks/sql-views-postgres should also exist for MongoDB (at least if https://github.com/prisma/prisma/discussions/12021#discussioncomment-2251376 is not lying)

When the page is available, make sure to update https://github.com/prisma/prisma/issues/678 to mention it as well.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
