### ISSUE TITLE
Consider adding a "Production Checklist" page to the docs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2930]
Inspired by Supabase and Vercel ([Twitter convo](https://twitter.com/caro_fyi/status/1498361880716455938)):

<img width="472" alt="image" src="https://user-images.githubusercontent.com/4058327/156303438-39620f17-0242-42f1-b77e-28d2c9c45bfd.png">

- Vercel: https://vercel.com/docs/concepts/production-checklist
- Supabase: https://supabase.com/docs/going-into-prod

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
