### ISSUE TITLE
Document `orderBy` for composite types

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2941]
Add `orderBy` to the [Composite types page](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types).

See the [design document](https://www.notion.so/prismaio/Composite-OrderBy-f442231e19194f72a10e03079e3d05c7) for more information.

**Comment by Jolg42** [comment]
@tanberry @keerlu randomly found this during a search, it looks like it was moved to "Done" but the issue is still open, I guess it can be closed now?

**Comment by keerlu** [comment]
Yep, this got done in #2958.
