### ISSUE TITLE
single-line block quotes are not vertically centered

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2947]
![image](https://user-images.githubusercontent.com/183673/156625043-86b79cd8-b5f2-4619-8480-0b70290b2554.png)

(from https://prisma.io/docs/reference/api-reference/command-reference#db-execute)

**Comment by meletj** [comment]
Not applicable to admonitions with the new admonition component. Still hapening when using **Note** aka blockquote

![Image](https://github.com/prisma/docs/assets/70962362/ea06100b-8f9f-41d6-a781-9795bc48dd46)
