### ISSUE TITLE
MongoDB tabs for "Schema prototyping with db push"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2949]
https://www.prisma.io/docs/guides/database/prototyping-schema-db-push
- ["Prototyping a new schema"](https://www.prisma.io/docs/guides/database/prototyping-schema-db-push#prototyping-a-new-schema) should also be possible with MongoDB
- ["Prototyping with an existing migration history"](https://www.prisma.io/docs/guides/database/prototyping-schema-db-push#prototyping-with-an-existing-migration-history) does not and might need an admonition

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
