### ISSUE TITLE
Improve docs re connection pooling

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2956]
--what exactly happens when `pgbouncer = true`... one of the insights that Matt shared was with a fellow who said he was unsure what setting this flag actually did...
--more guidance around how to configure these different environments. There seems to be a lot of confusion around how to configure Prisma properly right now for larger companies (from Matt)

**Comment by tanberry** [comment]
@matthewmueller and @albertoperdomo at some point, it wold be very helpful if the docs team could get a draft of 2 to 3 typical large environments... like a reference architecture. If we want to document "how to configure these different environments" we should frame the docs around what we think those large environments look like. What do you think? Or am I over-thinking it? :-)

**Comment by tanberry** [comment]
https://docs.rs/mobc/latest/mobc/

**Comment by janpio** [comment]
Note: PgBouncer (an external connection pooler) is not related to our Prisma internal connection pooling. Those are two different concepts with different goals that unfortunately got the same name, as they use the same underlying mechanism.

**Comment by ankur-arch** [comment]
I'm closing this issue as our connection pooling docs has had several [improvements](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool)🙏
