### ISSUE TITLE
Clarify `setupFilesAfterEnv` prerequisite for singleton unit testing guide

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma2-docs#2961]
In our [unit testing guide](https://www.prisma.io/docs/guides/testing/unit-testing), we offer a singleton approach to mocking the Prisma Client. This approach only works if you have put the `singleton.ts` file in the `setupFilesAfterEnv` option of your `jest.config.js`.

We make this note under the `Add Jest to your project` dropdown, but it's easy to miss and the guide will not work without this extra piece of configuration.

We could add another note about `setupFilesAfterEnv` later down where we mention creating `singleton.ts` or remove the the Jest setup from the dropdown entirely.

see: https://github.com/prisma/prisma/discussions/12057

**Comment by ruheni** [comment]
TODO:
- [ ] Ensure Prerequisites are correct, if any
- [ ] Clarify respective prerequisites for each guide
- [ ] Clarify shared prerequisites for the guides
