### ISSUE TITLE
Linkable tabs

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2967]
I'd like to link to the MongoDB logging tab, but it doesn't currently seem to be possible:

https://deploy-preview-2962--prisma2-docs.netlify.app/docs/concepts/components/prisma-client/working-with-prismaclient/logging

This makes it hard for me to point people to the MongoDB-specific docs.

**Comment by ankur-arch** [comment]
Hey there 👋 , the [page](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging) has undergone significant changes, hence I'm closing the issue for now. Feel free to reopen if you find new ways to improve our docs.
