### ISSUE TITLE
Add information how comments from PSL/AST are added to Prisma Client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2968]
https://www.prisma.io/docs/concepts/components/prisma-schema#comments

This section mentions how some comment make it to the AST, but there is no example how this is used. Instead there is a note that they are _not_ used:

> Note: /// comments are not present of the generated Prisma Client, but are present in the internal Data Model Meta Format (DMMF).

Per https://github.com/prisma/prisma/pull/10248 these are actually added to Prisma Client (please confirm @millsp), so we could use that as an example here (and this way also document that feature of Prisma Client generation)

**Comment by millsp** [comment]
Yes, comments are now visible on the property/column level and on the type level, but are not being reflected in `prisma.<model>`.

**Comment by janpio** [comment]
> comments are now visible on the property/column level and on the type level, but are not being reflected in prisma.<model>.

Sorry, what exactly does that mean? Can you add examples?

**Comment by millsp** [comment]
I left a similar explanation here https://github.com/prisma/prisma/issues/5070#issuecomment-1066601301

**Comment by janpio** [comment]
I hope the example we produce for the docs will help me understand.

**Comment by ankur-arch** [comment]
@millsp I think this [section](https://www.prisma.io/docs/orm/prisma-schema/overview#comments) is sufficient on explaining how comments are displayed.

I'm closing this, we can create a new issue if needed.
