### ISSUE TITLE
Get Started/add to existing guides: add migration as an option in the flow

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2975]
Currently, the "Add to existing" guides only cover Introspection as a way to evolve the DB; we need to add migration as an option. (See this [slack convo](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1647261578710779?thread_ts=1647255503.726199&cid=C5Z9TH6N9).)

We will need to rework the flow, and probably introduce a new landing page that briefly explains both options then allows user to click a to go to whichever they want. Then the Next step from both of those pages (Introspection and Migration) would connect to "Install Prisma Client", the next step in the flow.

![Screen Shot 2022-03-14 at 1 26 09 PM](https://user-images.githubusercontent.com/9368837/158237117-33a146b3-c74e-44c0-bf14-ef5a8787526b.png)

**Comment by tanberry** [comment]
See also Issue #2747 as this work impacts that.

**Comment by ruheni** [comment]
We added a new section on "Evolving your schema" which includes updating the data model & migrating the database 

https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/evolve-your-schema-typescript-postgres
