### ISSUE TITLE
Document deploying Prisma with AWS Lambda and Webpack

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2977]
It's about this issue: https://github.com/prisma/prisma/issues/2303. Might be some details within this too: https://github.com/prisma/docs/issues/1471. It looks like the Lambda + Webpack issue didn't actually get documented last go around.

_(Talk to @millsp for more context, feel free to edit this with details)_

**Comment by d3r3nic** [comment]
https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda

**Comment by ruheni** [comment]
This is currently documented here: https://www.prisma.io/docs/guides/deployment/deployment-guides/use-prisma-with-serverless-framework (using webpack and the serverless framework)
