### ISSUE TITLE
Release: Informationen Important 

### ISSUE THREAD

**Issue by Aminadad27** [prisma/prisma2-docs#2978]
## Release

- [ ] Merge in new content
- [ ] Update 'What's new' page with links to the release notes and new docs (example: https://www.prisma.io/docs/about/whats-new-in-prisma-docs#april-04-2021)
- [ ] Add links to release notes

## After release

- [ ] Add the 'What's new' video
- [ ] Clean up milestone

**Comment by ruheni** [comment]
We don't maintain this page in the docs anymore. It currently doesn't exist anymore
