### ISSUE TITLE
Document permissions required to run Introspection, Migration or Prisma Client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2982]
Example: https://github.com/prisma/prisma/discussions/2375#discussioncomment-2361544

**Comment by ruheni** [comment]
We've documented the permissions required to run Migrations (shadow database) here: https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#shadow-database-user-permissions

We'll look into the rest — Prisma Client and Migrate (including introspection)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
