### ISSUE TITLE
Clean up definition and use of the term "field" in schema reference and elsewhere

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2984]
We use the term "field" too broadly, sometimes referring to anything in the blocks as fields. We need to be more specific about "field" versus "value" versus "enum", etc.

See thread here: https://prisma-company.slack.com/archives/C01TM7UM83Y/p1646385986791359

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
