### ISSUE TITLE
Remove or fix note about `dotenv-expand`

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2985]
Using this dotenv-expand only works if users have one of our .env files. The note needs to make this clear... or just remove the note.

See this thread: https://prisma-company.slack.com/archives/C016KUHB1R6/p1643669852467339

**Comment by janpio** [comment]
It might be that this note needs to be on a different page that is more about our `.env` files (if it does not exist there yet already).

**Comment by Jolg42** [comment]
Looks like a duplicate of https://github.com/prisma/docs/issues/2835
I didn't read the Slack thread mentioned here, but I made this PR
https://github.com/prisma/docs/pull/4189

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
