### ISSUE TITLE
Remove preview feature labels from interactive transactions

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#2987]
Will need to remove preview feature labels when interactive transactions go to GA:
- https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions-in-preview
- https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#interactive-transactions-in-preview
- https://www.prisma.io/docs/concepts/data-platform/data-proxy#about-the-prisma-data-proxy

Also remove from list of preview features: 
- https://www.prisma.io/docs/concepts/components/preview-features/client-preview-features

**Comment by zachtil** [comment]
Resolved with [PR 4102](https://github.com/prisma/docs/pull/4102)
