### ISSUE TITLE
add quotes around raw queries in docs

### ISSUE THREAD

**Issue by aidantorrence** [prisma/prisma2-docs#2991]
would be nice to see quotes around raw sql queries in docs.  was confusing to a new user like me when they didn't work for the default tables that prisma generates like "Post" and "User"

https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
