### ISSUE TITLE
Document usage of `NODE_EXTRA_CA_CERTS`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2996]
For people that have a company proxy that uses a self signed certificate to resign TLS traffic, it might be necessary to make Node accept that certificate to be able to download our Prisma Engines from binary.prisma.sh/S3. Example: https://github.com/prisma/prisma/issues/12162

The solution is to use `NODE_EXTRA_CA_CERTS` before you start Node: https://nodejs.org/api/cli.html#node_extra_ca_certsfile (make sure to scroll up a bit, the design tends to hide the actual headline and content you link to)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
