### ISSUE TITLE
Clarify "Special characters" section for Connection URLs

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3002]
https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters

- This also applies to MongoDB.
- Does it maybe also apply to other databases? If not, is no escapaing necessary there? Is the escaping different? Both could be mentioned here for clarity.
- What "special characters" does this refer to? Optimally we would be able to list them out.
- (Super bonus: A small tool where you can paste your connection string and it is adapted correctly to work with Prisma)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
