### ISSUE TITLE
MongoDB: Document "undefined" behavior

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#3005]
We're making some changes in 3.11.1 around how records with undefined are queried

This [internal document](https://www.notion.so/prismaio/MongoDB-GA-effcea80826544ab9948f6425777e953#b778622fc3af40df983e781827ddbf11) has the details.

I asked Dom for a bit of clarity:

<img width="845" alt="CleanShot 2022-03-23 at 14 46 19@2x" src="https://user-images.githubusercontent.com/170299/159783275-a4e1789e-234e-417e-8a0a-8bf100f734f6.png">

Suggestion:
- Release notes or small docs page on breaking changes in the upgrade (undefineds are now ignores)
- Document `isSet` as a new query operation
- Document that undefined values in MongoDB are not matched by default, you use isSet to match them.

**Comment by tanberry** [comment]
Docs impacted by 3.11.1 patch release:
ASAP:
--https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined ([PR #3009](https://github.com/prisma/docs/pull/3009))
-- https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting
--https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#filter-conditions-and-operators

Later polishing:
-- https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#event-types ("Note that for MongoDB, the params and duration fields will be undefined.")
-- a lot of the troubleshooting topics

**Comment by matthewmueller** [comment]
Closed by: https://github.com/prisma/docs/pull/3017
