### ISSUE TITLE
MongoDB: Composite type indexes, new syntax with dot

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3007]
In order to be able to introspect and migrate MongoDB indexes on embedded documents, we are introducing a new syntax using a dot (".") to combine multiple fields.

Refer to this [thread](indexes on embedded documents) and this [Notion doc](https://www.notion.so/prismaio/Proposal-Composite-Type-Indices-03baf2ea1865417684fdab7fda2ee007#433bb15156004a76bbaf1f444b72dc77) for details.

Timeline (from Notion doc): we are releasing it in 2 steps: PSL, Introspection and Migrations first with MongoDB GA, later Client & Query Engine (with or without preview feature flag - see the “[Preview Feature](https://github.com/03baf2ea1865417684fdab7fda2ee007#83c42e38b4f84d95be5a43a474ce3af3)” section).

**Comment by Jolg42** [comment]
I could not find any information about this in our docs and found this tracking issue.

I think these 2 pages (maybe more?) would need to say something about it?
- https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#index
- https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-composite-types

**Comment by Jolg42** [comment]
What is currently communicated from the release notes https://github.com/prisma/prisma/releases/tag/3.12.0

> ### Index support on composite type fields
> 
> We also added support for adding indexes on embedded document fields in MongoDB. This means that you can now define a normal, unique, or full-text index in your schema.
> 
> ```prisma
> type Address {
>   street String
>   number Int
> }
> 
> model User {
>   id      Int     @id
>   email   String
>   address Address
> 
>   @@index([email, address.number])  /// normal index
>   @@unique([email, address.street])  /// unique index
>   @@fulltext([email, address.street]) /// full-text index
> }
> ```
> 
> > Note: Prisma Client does not yet fully support the feature for now. This will be rolled out in a future release.
>

**Comment by keerlu** [comment]
> I could not find any information about this in our docs and found this tracking issue.
> 
> I think these 2 pages (maybe more?) would need to say something about it?
> 
> * [prisma.io/docs/reference/api-reference/prisma-schema-reference#index](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#index)
> * [prisma.io/docs/concepts/components/prisma-schema/data-model#defining-composite-types](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-composite-types)

Yes, this didn't quite make it in last sprint - on our list to catch up this sprint! Agree that these look like the right places to include it
