### ISSUE TITLE
Design approach for multiple repetitive warnings re MongoDB

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3011]
Throughout the docs there are many places where we need to let users know that using Migrate, and certain related commands, is not supported on MongoDB. The problem is, even though these repetitive Notes can be wearying and disruptive, we do need to account for the fact that some readers will look only at the docs for a single command (say `migrate dev`) and not look at the higher-level topic about using Migrate. So... we do need a warning by each command.

This challenge needs a proper examination: design input, user testing, maybe a dynamic widget. From Jan: "What we talked about in the past was a small "box" somewhere on the top right for example that lists the supported databases for features/pages and you can click it to land on the big feature matrix page you mentioned."

**Comment by tanberry** [comment]
@matthewmueller no rush but I'd be interested to get your feedback on how important you think it is for us to heavily warn MongoDB users about not using any of the Migrate commands... are warnings needed by each command, in the Reference section? Any ideas of how to solve this challenge, or other thoughts?

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
