### ISSUE TITLE
Document `strict: true`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#3018]
@do4gr ran into a rather obscure bug that took us both by surprise: https://github.com/prisma/prisma/issues/12088

It turns out that a missing `"strict": true` in your `tsconfig.json` causes some of the the Prisma Client to miss some type-checks, leading to validation errors at runtime.

I suppose this is the intent of `"strict": true`, where it tightens the type-checking, but I guess I'm surprised that it affects the Client API.

I think we should at least tell people that the Prisma Client's type-safety is affected by this flag (specifically: `"strictNullChecks": true`). It is part of the default config, when initializing a typescript project with `npx tsc --init`.

I'm also wonder if we should say this a System Requirement for our Typescript users. You can technically use Prisma without it, but you probably shouldn't.

**Comment by matthewmueller** [comment]
Internal context: https://prisma-company.slack.com/archives/CUXLS0Z6K/p1648483521236509

Seems most likely that we'll solve this during `prisma generate`.

https://github.com/prisma/prisma/issues/12556

**Comment by jharrell** [comment]
Closing in favor of https://github.com/prisma/prisma/issues/12556

**Comment by Jolg42** [comment]
@jharrell I think we should keep this issue open, we could document how things are affected by this setting in the docs (implementing https://github.com/prisma/prisma/issues/12556 or not doesn't change this to me, and the warning could actually point to the docs?)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
