### ISSUE TITLE
MongoDB (post-GA); add links to new Guide

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3030]
At the end of the Getting Started Guides (from scratch and add to), this block needs to be edited to link to the new Prisma with MongoDB guide:

"There are also a number of subtle differences in how the schema is setup when compared to relational databases like PostgreSQL.

For example, the underlying ID field name is always _id and must be mapped with @map("_id").

For more information check out the [MongoDB schema reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#mongodb-2)."

**Comment by ruheni** [comment]
This is documented as part of the Getting Started guide
