### ISSUE TITLE
Content about relations tables is confusing

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3056]
When trying to understand the conventions for creating relations tables (i.e. join tables), it is confusing what conventions apply to implicit m:n relations and what to 1:1 relations, etc.

[This topic](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#conventions-for-relation-tables-in-implicit-m-n-relations) has a section that says "...following Prisma's conventions for relation tables..." but then it links to itself. Is there some other topic that explains conventions for non-n:m relations tables??

Furthermore, the example relations table shown in [this section](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#relation-tables) doesn't have an underscore in front of name... even though the convention (at least for n:m) says it is required.

Also, is there any requirement about the names of the columns in the relations table being A and B?

Docs where we might need to do some rewording:
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#relation-tables
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#conventions-for-relation-tables-in-implicit-m-n-relations

**Comment by janpio** [comment]
Naming conventions (actually requirements) for relation tables only apply to **implicit** many-to-many relations.

- They are documented here: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#conventions-for-relation-tables-in-implicit-m-n-relations
- **Explicit** relation tables can be named any way you want, e.g. shown in https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#relation-tables
- The naming conventions/requirements for columns of **implicit** m:n relations is also described here: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#columns and indeed is `A`and `B`.

I think technically the docs are correct here (except for that weird self link), but as your confusion (and you are def not the first one) shows, this could be made clearer. One additional factor to the confusion is probably that both the implicit m:n and the explicit m:n relation table use a similar/same example. (Of course this is for the reason to show when an implicit is fine, when an explicit is fine [when you want to add more information manually] - but maybe that point is lost anyway.)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
