### ISSUE TITLE
Verify integration with JetBrains IDE

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3062]
This [video ](https://www.youtube.com/watch?v=hAUE-gK80f0)states that our plugin for working with JetBrains' IntelliJ doesn't work.

We need to research and make sure it now works; if not, either get with Engineering to see if we want to fix this issue, or remove mention of this support from our Docs.

https://www.prisma.io/docs/guides/development-environment/editor-setup#jetbrains-ide

**Comment by ruheni** [comment]
Jetbrains released the official plugin for Prisma
