### ISSUE TITLE
Conflicting Information on Adding Indexes to Database 

### ISSUE THREAD

**Issue by amir-beheshty** [prisma/prisma2-docs#3064]
I'm using Prisma's new [Full Text Search](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#adding-indexes) and noticed in [The Adding Indexes](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#adding-indexes) section it is recommend to add index(es) to the database using SQL since:
> Prisma schema and Prisma Migrate currently don't support defining and creating PostgreSQL search indices.

However, in the [@@indexes api reference page](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#index) it looks like we can add indexes to the database, albeit it's not a [GIN Index type](https://www.postgresql.org/docs/12/textsearch-indexes.html).

This is lead to some confusion and not sure if I'm misunderstanding something or the docs need to be updated.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
