### ISSUE TITLE
Add link to RDS article from Getting Started Guide

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#3067]
Not sure how to get a connection URL? Read [this guide](https://www.prisma.io/dataguide/postgresql/setting-up-postgresql-on-rds) on how to provision a PostgreSQL database on AWS.

**Comment by tanberry** [comment]
Topics where we could possibly add links from our tech docs to the Data Guide about setting up a PS DB on AWS:
--- Static IPs: https://www.prisma.io/docs/concepts/data-platform/static-ips#about-static-ip-addresses (maybe)
-- Getting Started,  Relational databases, Prerequisite section and Connect your database. (though there is already one link to PS docs, so will have to look at how to add this link to the Data Guide)
-- ?
