### ISSUE TITLE
Sidebar in Concepts page highlights incorrect selected section

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#3081]
On the [concepts](https://www.prisma.io/docs/concepts/components/prisma-client) page, when selecting the Prisma Client section sidebar incorrectly highlights the Prisma CLI section as well.

In the below image Prisma Client section is selected but the Prisma CLI section gets highlighted as well.
Doesn't happen when selecting Prisma CLI, only happens when selecting Prisma Client.
<img width="1454" alt="Screenshot 2022-04-22 at 3 10 06 PM" src="https://user-images.githubusercontent.com/13049676/164681399-d1b3352e-0a4c-436f-af84-bf7e16d15155.png">

**Comment by janpio** [comment]
Related: https://github.com/prisma/docs/issues/2691 + https://github.com/prisma/docs/issues/2494
PR potentially fixing this: https://github.com/prisma/docs/pull/2692

**Comment by meletj** [comment]
Fixed by #2692
