### ISSUE TITLE
Copy + Pastable Replica Set example for MongoDB

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#3082]
There was a bit of misinformation that Prisma + MongoDB only supports Atlas: https://twitter.com/MaxProgramming1/status/1516985001388113920 

I tried correcting this first by looking in the docs for a link, but then I couldn't find it so I posted the Github issue from @Jolg42. 

After Usman, from the twitter thread, mentioned it should be in the docs, I looked again in the docs and was able to find a small section in **Differences to Consider**

> https://www.prisma.io/docs/guides/database/using-prisma-with-mongodb#differences-to-consider

Problems:
- Can't link directly to the replica set configuration
- MongoDB guides are a wall of text that makes it seem more complicated to setup than it is.

Proposed changes:
- We create a sub-section or make the bullet point itself linkable because this will be a re-occuring issue that we are going to want to be able to copy + paste
- Add @Jolg42 solution as the primarily solution.
- Link to MongoDB's documentation for details

**Comment by Jolg42** [comment]
See https://github.com/prisma/docs/issues/3040 for the docker-compose solution

**Comment by ankur-arch** [comment]
Closing this as:

- The mongo guide is easier to [follow](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb-typescript-mongodb).
- We can link to the replica set [config](https://www.prisma.io/docs/orm/overview/databases/mongodb#replica-set-configuration) and it's copy pastable.
