### ISSUE TITLE
Docs navigation annoyance: scrolling to open mini-toc on right

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3084]
[A user has stated](https://prisma-company.slack.com/archives/C601F4CF8/p1650522451072709) that it's annoying to have to scroll into a section in order to get the mini-toc on the right to expand and display the subsections. Many of us here agree. Let's look at how the ToC can either be static or... any other solution?

We do need to be careful about having a very long "mini"-toc. 

Possible solutions:
-- adding rotating arrows just like the left-side nav 
-- add a "landing page" that is titled something obvious, so they know to click it to get each of the sub-pages
-- ??

UPDATE 7th July: Webdev, Design, and Docs met and defined [this solution](https://www.notion.so/prismaio/Table-of-Contents-redesign-b454eb8236094fc086fc052ae7303962#76666f947f604d6c99396d6844ed3bf0).

**Comment by janpio** [comment]
Additional option: Include the Table of Content in the page before the content (hidden by default, but fully uncollapsible with 1 click)

It might make sense to use different strategies depending on the content. A short guide probably has different usage than a multi dozen headline reference page.

**Comment by nilubava** [comment]
@tanberry @peterondesign I think I might need more clarity on the behavior of TOC here. Do we need to brainstorm on ideas ?

**Comment by tanberry** [comment]
Yes @Nilu we probably do need to brainstorm on ideas... the "jumping around" of the mini-ToC's elements is a problem, and is listed in this [article](https://www.nngroup.com/articles/top-10-ia-mistakes/) as one of the top 10  UI mistakes to avoid ("Uncontrollable Navigation Elements").

**Comment by nilubava** [comment]
TODO (discussed in the call on 07.07.22)

- [x] Remove the jumping of the H3 headings when H2 is scrolled to
- [x] Work on the paddings and spaces @peterondesign 
- [x] 'Content' -> 'On this page'
