### ISSUE TITLE
Search results should not include link URL or other source code

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3092]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/183673/165181073-f18b76e7-30eb-4f8e-9cd5-840c6aac4e89.png">

**Comment by Jolg42** [comment]
After the merge 💚 
<img width="822" alt="Screen Shot 2022-07-18 at 11 18 10" src="https://user-images.githubusercontent.com/1328733/179481410-4f22a1bc-fc55-4ccd-8ebc-f01ba0dbb3a0.png">
