### ISSUE TITLE
New sequence types for CockroachDB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3099]
CockroachDB will be getting a new `sequence()` attribute function for the `@default` attribute that can take a number of arguments (`virtual`, `cache`, `increment`, `minValue`, `maxValue`, `start` and `noCycle`, that correspond to the [CockroachDB sequence parameters](https://www.cockroachlabs.com/docs/v21.2/create-sequence#parameters).

Example: `@default(sequence(minValue: 10, maxValue: 909090)`.

The existing `@default(autoincrement())` syntax will only be able to be used on `BigInt` fields.

Docs to update:
- Schema reference: add to [`@default` attribute](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default) reference and also add `sequence()` to the [attribute functions](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#attribute-functions) reference
- A section in the [CockroachDB connector page](https://www.prisma.io/docs/concepts/database-connectors/cockroachdb) would explain how the PSL concepts map to the cockroachdb concepts. Since they would map very closely, we can redirect curious users to the cockroachdb docs. The limitation that `@default(autoincrement())` is only possible on BigInt columns should be mentioned.

Related to https://github.com/prisma/prisma/issues/12239

See notes here: https://www.notion.so/prismaio/Proposal-CockroachDB-autoincrement-columns-2d0a0d46a350429da503ca29824dd7c8

**Comment by tomhoule** [comment]
closed by https://github.com/prisma/docs/pull/3129
