### ISSUE TITLE
Content on Prisma in your Stack page feels outdated

### ISSUE THREAD

**Issue by peterondesign** [prisma/prisma2-docs#3101]
### Description

Could we update the content on this page? In this section, it would be great to include Prisma with: Next.js, Typescript, GraphQL, Apollo, NestJS, Express, hapi, Planetscale, MongoDB, Fastify, React Server Components etc.

### Additional Context
<img width="594" alt="Screenshot 2022-04-27 at 15 47 40" src="https://user-images.githubusercontent.com/36060650/165545977-036ab419-2309-4a8e-9be9-a23b9d72f51f.png">

**Comment by meletj** [comment]
Content requested is coverd in sub-pages within the Docs and by the new page on website: prisma.io/stack
