### ISSUE TITLE
Filtering on Null requires use of `equals`

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3103]
Per [this Slack thread](https://prisma-company.slack.com/archives/C016KUHB1R6/p1651006022206219) a user got errors trying to use `anyNull` based on the [code examples in our documentation](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values). 

We need to change the code example in docs FROM this:
```
import { Prisma } from '@prisma/client'

prisma.log.findMany({
  where: {
    data: {
      meta: Prisma.AnyNull,
    },
  },
})
```

TO this (using `equals`):
```
prisma.log.findMany({
  where: {
    data: {
      meta: {
        equals: Prisma.AnyNull
      }
    },
  },
})

```

Let's add a note in the "Filtering on null values" section of the doc (to the existing Notes), and move the whole block of Notes up higher, right before the "For example" line.

New Notes block draft:
```Notes:
* When filtering using any of the `null enums` you must use the `equals` operator, as shown in the example below.
* These null enums do not apply to MongoDB because there the difference between a JSON null and a database NULL does not exist.
*They also do not apply to the array_contains operator in all databases because there can only be a JSON null within a JSON array. Since there cannot be a database NULL within a JSON array, { array_contains: null } is not ambiguous.

**Comment by tanberry** [comment]
@austincrim our existing code example has a comma after `Prisma.AnyNull` ... should it? Please carefully review the proposed new code example. ;-)

**Comment by austincrim** [comment]
@tanberry The trailing comma shouldn't be an issue, more of a stylistic choice, I think. I would just go with whatever we do most frequently in our other code snippets.

The code example looks good to me!

**Comment by tanberry** [comment]
See also https://github.com/prisma/docs/issues/3114, which is a dupe but has good info in it. We will close both Issues after the work is complete.
