### ISSUE TITLE
Add guide on sharing the Prisma Client with an NPM package

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma2-docs#3117]
[internal discussion](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1651182653805309).

Some users want to share a single Prisma Schema/Client with multiple projects by packaging it up into its own NPM module. We could document the steps required to do this given the unique way we interact with `node_modules` and the engine binaries.

**Comment by jharrell** [comment]
Closing as duplicate of #442
