### ISSUE TITLE
Update docs to reflect change in `references` arg for m:n relations

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3122]
Per work done by the PSL Working Group, the use of `references` as an argument on many-to-many will no longer be allowed. (See exceptions for MongoDB.)

For details, and the exact error message users will get if they try to use `references`, see the [Notion doc by Tom](https://www.notion.so/prismaio/Proposal-Forbid-the-references-argument-in-relation-attributes-in-implicit-many-to-many-relations-5851708905324e6c8fb8b581e359717b). 

Note that this is a breaking change ⚠️. Schemas that are currently valid will become invalid when the validation is introduced.

**Comment by janpio** [comment]
Replaced by https://github.com/prisma/docs/issues/3214
