### ISSUE TITLE
Update docs to cover new Postgres index types (GIN, GiST, SP-GiST and BRIN)

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3125]
Per work by the PSL Working Group, we need to update the docs to add these new index types and explain tier usage. For details see [Julius' proposal docs in Notion](https://www.notion.so/prismaio/Proposal-More-PostgreSQL-index-types-GiST-GIN-SP-GiST-and-BRIN-e27ef762ee4846a9a282eec1a5129270).

These new index types will be part of the current Preview feature called `extendedIndexes`.

**Comment by janpio** [comment]
Earlier issue that already has a PR: https://github.com/prisma/docs/issues/3102
