### ISSUE TITLE
Do the docs reflect usage of `set` operation?

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3127]
Refer to this convo for details, but it seems we need to increase our docs about 1set``, use it in more examples, etc.

https://prisma-company.slack.com/archives/C02JV0K2Q31/p1651505158811669

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
