### ISSUE TITLE
Add JavaScript code samples for Guides > Performance and optimizations > Connection management

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3134]
Request coming from [twitter](https://twitter.com/flaviocopes/status/1522253732116934657) to add JavaScript code samples in [Connection management](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prevent-hot-reloading-from-creating-new-instances-of-prismaclient).

More specifically in the section **Prevent hot reloading from creating new instances of `PrismaClient`**.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
