### ISSUE TITLE
Integration test page references unused jest-mock-extended

### ISSUE THREAD

**Issue by isaacbatst** [prisma/prisma2-docs#3135]
[This topic](https://www.prisma.io/docs/guides/testing/integration-testing#prerequisites) advertises the usage of `jest-mock-extended`. But, it's not used on this guide, since it's a integration test including a real database access.

**Comment by isaacbatst** [comment]
To fix if this is correct, I have opened #3136 removing the advertise

**Comment by tanberry** [comment]
Thanks @isaacbatst . When you say that the [unit testing guide](https://www.prisma.io/docs/guides/testing/unit-testing)) doesn't use `jest-mock-extended` I am not sure what you mean. Do you mean that one can skip the "Mocking the Prisma client"section, and connect to a real DB, and thus not use jest?

**Comment by isaacbatst** [comment]
Hey @tanberry ! Actually, the unit testing guide mentions and uses the jest-mock-extended as it is meant to be.

For the other side, the[ integration testing guide ](https://www.prisma.io/docs/guides/testing/integration-testing#prerequisites)does not uses the mock, since it is a test that is meant to reach a testing database.

This integration guide has a warning suggesting the moking lib is being used, but it is not. So, I think this warning should be removed.
