### ISSUE TITLE
Consider clarifying the intro to our What's new in Prisma docs page

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3152]
IMO we should consider changing the intro paragraph on our What's new in Prisma docs page.

https://www.prisma.io/docs/about/prisma-docs/whats-new-in-prisma-docs

At first glance, it's not clear that this is referring to improvements to the docs *feature set*, rather than the docs content. To me, it initially looked like we were saying that we haven't updated the Prisma documentation since September 2021.

**Comment by janpio** [comment]
It actually was meant and used to document the documentation changes.
It was just stopped to be used and not updated to reflect that.

**Comment by ruheni** [comment]
The "What's New in Prisma docs" was dropped.
