### ISSUE TITLE
Add Replibyte as a database seed option in the Prisma doc

### ISSUE THREAD

**Issue by evoxmusic** [prisma/prisma2-docs#3156]
Hi, I am the creator of [Replibyte](https://github.com/Qovery/Replibyte), an open-source tool to seed a development database with a production database while hiding sensitive data. 

We have developers using Replibyte to seed their database with Prisma. Is it possible to add a section [here](https://github.com/prisma/docs/blob/main/content/300-guides/050-database/300-seed-database.mdx) to explain how to do it? 

Coupling Replibyte to Prisma can help your users to better leverage Prisma.

**Comment by ruheni** [comment]
Hey 👋

Thank you for the suggestion. We don't intend to create more guides on how to seed a database with other tools, such as Replibyte, but we're open to adding a section that mentions and links out to other tools in the docs. I'll take care of  this very soon. 🙂
