### ISSUE TITLE
[Bug] Prisma Docs claim DateTime type is mapped to timestamp in MongoDB

### ISSUE THREAD

**Issue by Haimchen** [prisma/prisma2-docs#3157]
I believe there are some errors in the documentation about `DateTime` in MongoDB:

#### Schema Reference:

According to the docs the `DateTime` type is using MongoDB's `Timestamp`. 
Source: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#mongodb-6

#### MongoDB connector

The docs on the MongoDB connector also mention that `DateTime` from Prisma is mapped to `timestamp`.
Source: https://www.prisma.io/docs/concepts/database-connectors/mongodb#mapping-from-prisma-to-mongodb-types-on-migration

#### What is actually happening

From what I can observe: Fields typed in the Prisma schema as `DateTime` are stored as MongoDB `Date`.

---

This gets more confusing as the [dataguide](https://www.prisma.io/dataguide/mongodb/working-with-dates#the-mongodb-date-and-timestamp-types) mentions the MongoDB `Date` type, but also a Prisma `Date` type that is missing in the schema reference. (It is mentioned in the MongoDB connector docs though).

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
