### ISSUE TITLE
Update Wrangler section of Deploying to Cloudflare Workers doc

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3188]
Our CloudFlare Workers doc has a [section on Wrangler](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers#2-set-up-wrangler), but this covers Wrangler version 1. Wrangler 2.0 is now the current version. We should update the doc to support this.

@millsp  identified this docs issue, and can provide the technical information about this.

**Comment by ObamaTheLlama114** [comment]
The current instructions work perfectly. I got a worker up and accessing the database without any problems

**Comment by millsp** [comment]
What do you mean @ObamaTheLlama114? Have you got it working with wrangler 2 as well?

**Comment by Jolg42** [comment]
Note: differences between v1 and v2 
https://developers.cloudflare.com/workers/wrangler/compare-v1-v2/

**Comment by Jolg42** [comment]
It seems that with Prisma Client Edge, environment variables are not working with the "new" "Module Syntax" (to be confirmed)
https://github.com/prisma/prisma/issues/15958

**Comment by Jolg42** [comment]
Probably we can switch the docs to use wrangler v2 only but recommend the `Service Worker` syntax for now

**Comment by ObamaTheLlama114** [comment]
https://github.com/prisma/docs/pull/4014

**Comment by ObamaTheLlama114** [comment]
I removed a couple steps because wrangler handles those on its own now. Webpack is no longer necessary, and typescript is supported out of the box.

**Comment by Jolg42** [comment]
Had a quick look. this looks great, love how it got simpler with wrangler v2
