### ISSUE TITLE
Add all CRUD examples or links to dbcommand page

### ISSUE THREAD

**Issue by reslear** [prisma/prisma2-docs#3209]
Add links to page https://github.com/prisma/docs/blob/main/content/200-concepts/100-components/02-prisma-client/090-raw-database-access.mdx for syntax guide how to use all CRUD commands:
we have only `insert`, and need add other - example for **update**: 
https://www.mongodb.com/docs/manual/reference/command/update/#mongodb-dbcommand-dbcmd.update
https://www.mongodb.com/docs/manual/reference/command/update/#std-label-update-statement-documents

or add all examples how to use any CRUD commands with types: 

```ts
import type { UpdateStatement } from 'mongodb'

prisma.$runCommandRaw({
  update: '',
  updates: [
    // @ts-ignore
    {
      q: {},
      u: {
        $set: {
          address: { $toLower: '$address' },
        },
      },
      multi: true,
    } as UpdateStatement,
  ],
}),
```
sorry for my Eng )

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
