### ISSUE TITLE
Docs: tracing completion

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3212]
Engineering issue: 
https://github.com/prisma/client-planning/issues/21

Engineering discussion:
https://www.notion.so/prismaio/Tracing-completion-7b2d995de37542dd8b9a5e0cb4222d31

**Comment by tanberry** [comment]
Yay, finally tracing will become a public feature! @Andrew, can you add a sentence or two in the Description to explain what the docs are... are the Docs to cover everything about tracing, or... how to know when tracing is complete, or...? :-)

Maybe a draft ToC to show what you need to cover, like:
--About tracing <noun> in Prisma
--How to configure tracing
--Monitoring tracing

Something to provide a picture of what docs you want to write about this feature. This will help with scoping too.
Thanks!

**Comment by andrew-walford-prisma** [comment]
@tanberry Sure - when I know more, I'll add this information. The ticket right now is a placeholder.

**Comment by andrew-walford-prisma** [comment]
This looks like a dupe. I'm going to investigate, and if so, bring any info here into the other ticket.

**Comment by andrew-walford-prisma** [comment]
Yep, I'm closing this one - it's a dupe.
