### ISSUE TITLE
Remove `references` syntax from implicit many-to-many relations

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3214]
Currently Prisma allows the following syntax for implicit many-to-many relations, with `id` as the only valid value for `references` :

```
model First {
    id Int @id
    seconds Second[] @relation("my-relation", references: [id])
}

model Second {
    id String @id
    firsts First[] @relation("my-relation", references: [id])
}
```

This use of `references` is no longer going to be allowed, to make it clearer what can be changed – see [this PSL proposal](https://www.notion.so/prismaio/Proposal-Forbid-the-references-argument-in-relation-attributes-in-implicit-many-to-many-relations-5851708905324e6c8fb8b581e359717b). 

These three alternatives will still be valid:

```
model First {
    id Int @id
    seconds Second[]
}

model Second {
    id String @id
    firsts First[]
}
```

```
model First {
    id Int @id
    seconds Second[] @relation
}

model Second {
    id String @id
    firsts First[] @relation
}
```

```
model First {
    id Int @id
    seconds Second[] @relation("my-relation")
}

model Second {
    id String @id
    firsts First[] @relation("my-relation")
}
```

It looks like the current docs on [how to use implicit many-to-many relations](https://prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#rules-for-defining-an-implicit-m-n-relation) don't use the deprecated syntax anyway. So only need to check docs for any examples that use it and fix them.

**Comment by janpio** [comment]
Also we need to document that this is _not_ allowed and needed (vs. other relations which allow `fields` and `references` to define certain things)
