### ISSUE TITLE
Move remaining docs functionality rewrite into docs repository from website repo

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3217]
https://github.com/prisma/website-v8/blob/e96e4fc8b6e8034f0876edb7e7cac3008ffca156/public/_redirects#L147
```
/docs/feedback-api/    https://prisma2-docs.netlify.app/.netlify/functions/index 200!
```

This is the last remaning rewrite in the website repo that was not migrated over to the docs repo. It in theory should also be able to be moved to this repository here to make the docs fully self contained. (It should be covered by the main rewrite that makes sure all requests to `/docs` land on the docs deployment: https://github.com/prisma/website-v8/blob/e96e4fc8b6e8034f0876edb7e7cac3008ffca156/public/_redirects#L148 `/docs/*                https://prisma2-docs.netlify.app/docs/:splat 200!
`)

**Comment by meletj** [comment]
@nilubava can you pls double check if this is still accurate/relevant based on v9 and Vercel setup?

**Comment by nilubava** [comment]
@meletj Closing this since this is no longer relevant.
