### ISSUE TITLE
Adding workflow to allow creating initial migrations for baselining without resetting development database

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#3219]
In the Baselining documentation, we have a requirement that it's necessary to reset the development database: [Documentation Link](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#update-the-development-environment). 

In certain cases, users cannot reset their development database as well. 

To address this concern, I came across this [comment](https://github.com/prisma/prisma/issues/11555#issuecomment-1027242342) on one of the related issue which suggests using `migrate diff` commands to create initial migration without needing to reset the development database.

Should we add these commands in docs or maybe add a workflow in docs which would allow generating initial migrations without needing to reset the database?

**Comment by janpio** [comment]
The actual problem is this here? https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#apply-the-initial-migrations

**Comment by nurul3101** [comment]
Yes, the actual problem is that to generate initial migrations we require a reset of the development database.

**Comment by austincrim** [comment]
[Here's another instance](https://github.com/prisma/prisma/discussions/15700#discussioncomment-3825285) of this issue cropping up. The user tried to follow our baseline docs but was wary of resetting their DB.

The `prisma migrate diff` workflow is really useful and should be added to the docs when possible, in my opinion.

**Comment by nurul3101** [comment]
Another [instance](https://prisma.slack.com/archives/CA491RJH0/p1673293142838789) of community slack user running into this.

**Comment by janpio** [comment]
Our getting started has already been changed to use `migrate diff`, we can do the same here (although we need to figure out in which use cases `migrate dev --create-only` is actually better).

**Comment by ruheni** [comment]
Done: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/baseline-your-database-typescript-postgres
