### ISSUE TITLE
Adding link to `db.runCommand` MongoDB documentation from `$runCommandRaw` section

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#3220]
In the section of `$runCommandRaw` in our [documentation](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#runcommandraw) should we add that the object that could be passed while invoking the query should follow the syntax of `db.runCommand` from MongoDB Docs: https://www.mongodb.com/docs/manual/reference/command/

Right now it's not clear what are the possible parameters we could pass while invoking the `$runCommandRaw` query.

**Comment by ruheni** [comment]
This should be sufficiently documented here. Feel free to reopen it if we could add any additional information. :)

<img width="477" alt="CleanShot 2023-05-25 at 11 22 34@2x" src="https://github.com/prisma/docs/assets/33921841/63ea42d3-29ac-477e-bcc6-f9673bc5c46b">
