### ISSUE TITLE
Replace/update query engine diagram 

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3221]
The current diagram has old names (that have been updated in text above diagram) and need several other fixes. See [Jan's Slack post](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1654095653879989) for details.

https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#the-query-engine-at-runtime (the one with the flow):

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
