### ISSUE TITLE
Percy + Cookie Banner

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3227]
The cookie banner should be made invisible for Percy, similar to how we did for some images and other things.

Reason: https://github.com/prisma/docs/pull/3226#issuecomment-1145929931

**Comment by tanberry** [comment]
So @Jan to make sure I understand, you are saying that we need to configure Percy to ignore (during docs builds) the new[ish]Cookies banners and consent forms that are now part of the Docs site?

That is, these cookie banners should not trigger a warning by Percy, about "visual diffs" . Agreed.

**Comment by tanberry** [comment]
@nilubava and @carlagn I'm not sure which label to use to "Ask politely may we please consider this one for next sprint?"  :-)

**Comment by jan** [comment]
@tanberry thanks for bringing this to my attention. I think you are doing a great job here. Keep up the good work!

**Comment by Jolg42** [comment]
I opened a small PR to hide the cookie banner here https://github.com/prisma/docs/pull/3331
