### ISSUE TITLE
Data Proxy docs: remove "early access feature" admonition

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3231]
On June 15th, PDP goes GA. At this point, we should remove the "early access feature" admonition from the Data Proxy docs page

https://www.prisma.io/docs/concepts/data-platform/data-proxy

**Comment by zachtil** [comment]
@andrew-walford-prisma thanks for adding this. I can assign this one to me.

**Comment by zachtil** [comment]
This was resolved at GA.
