### ISSUE TITLE
Highlighting in Docs menu bar

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3232]
From [Jan's Slack post](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1654277104214629):
Bug report: https://www.prisma.io/docs/concepts/data-platform/about-platform
Seems our navigation highlighting can also be triggered by the names of subpages.

We are having quite a few issues with our highlighting, within the content of the pages, where there are code snippets. 

But this one is hopefully an easy fix, if it is possible to just remove the menu form any impacts of triggers?

**Comment by tanberry** [comment]
Hi @nilubava and @carlagn ... I *think this is something your team can help with, but if it should be a Docs Issue please let me know.

**Comment by janpio** [comment]
See https://github.com/prisma/docs/pull/3239#issuecomment-1150478878
