### ISSUE TITLE
Consider improving step 5 of the Data Proxy doc

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3246]
Suggestion from Jan

We possibly need to improve the explanation about how to use the Data Proxy with Worker/Edge environments in [Step 5](https://www.prisma.io/docs/concepts/data-platform/data-proxy#step-5-import-and-instantiate-prisma-client-in-your-code). At the moment, we only provide an example. I'm personally not sure if we need to do this.

**Comment by zachtil** [comment]
To come back to this if we decide we need to make further changes. Current content is looking good. Closing for now.
