### ISSUE TITLE
PDP: Data Proxy: Add Windows instructions for the "migrate" command

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3247]
Suggestion from Jan

In the [Data Proxy doc](https://www.prisma.io/docs/concepts/data-platform/data-proxy), and probably other docs (we'll need to check), we mention a "migrate" command that will not work on Windows.

The command suggested for migrate usage will not work on Windows: "migrate": "DATABASE_URL=\"$MIGRATE_DATABASE_URL\" prisma migrate deploy".

**Comment by zachtil** [comment]
It is very likely that this improvement will not be necessary with the improvements from #4297

**Comment by ruheni** [comment]
The guide has been updated, recommending usage of the new `directUrl` property to distinguish the connection pooler connection string and the connection string with a direct connection to the DB

https://www.prisma.io/docs/data-platform/data-proxy/prisma-cli-with-data-proxy#set-a-direct-database-connection-url-in-your-prisma-schema
