### ISSUE TITLE
Update minimum supported Node.js version [ Prisma 4 ]

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma2-docs#3254]
Part of the Prisma 4 effort: Node.js 12.x support is dropped, minimal supported Node.js version is now 14.x

We need to update:
* https://www.prisma.io/docs/reference/system-requirements
* https://www.prisma.io/docs/getting-started/quickstart
* https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/upgrade-from-mongodb-beta

This is a breaking change - this needs to go in the upgrade guide.

This is ready to merge when Prisma 4 goes live - Jan has OKayed the PR.

**Comment by andrew-walford-prisma** [comment]
Thanks @aqrln !
