### ISSUE TITLE
Make docs on updating to latest version easier to find

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3258]
It's not easy to find docs on using the following commands to update Prisma to the latest version:
npm i --save-dev prisma@latest                    
npm i @prisma/client@latest  

The output of `npx prisma generate` does explain this, but I was looking for this info in the docs, and couldn't find it.

Note: we might want to link to upgrade guides (which explain breaking changes).

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
