### ISSUE TITLE
Prisma deployment Examples:  keep Netlify and Vercel examples and docs up-to-date

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3280]
Two of our deployment guides ([Netlify](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-netlify) and [Vercel](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-vercel)) rely on code from Prisma Examples repos ([Netlify](https://github.com/prisma/deployment-example-netlify), [Vercel](https://github.com/prisma/deployment-example-vercel)). When the examples are out of date, so are the docs.

Considerations:
-- automated testing of the examples, with ways to trigger Docs updates (a la  https://github.com/prisma/prisma-examples/tree/latest/.github/tests)
-- ?

For details see this [Slack thread](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1655317005919569).

Docs and the Dev Advocacy team could co-own this work. Hi @ruheni . :-)

**Comment by Jolg42** [comment]
There is a related issue for Netlify for the guide
https://github.com/prisma/docs/issues/3139

**Comment by jharrell** [comment]
Closing this as no longer relevant. We're moving in a direction that the examples will no longer be necessary.
