### ISSUE TITLE
Update code snippet in documentation about long running process with Next.js

### ISSUE THREAD

**Issue by Emnalyeriar** [prisma/prisma2-docs#3295]
Link to docs provided below doesn't have the updated code snippet mentioned in the referenced issue.

@trentprynn Thanks for the code snippet, it works great. The documentation link you provided shows the updated code but the example code shown in section "[Prevent hot reloading from creating new instances of PrismaClient](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prevent-hot-reloading-from-creating-new-instances-of-prismaclient)" still shows the old code.

_Originally posted by @Emnalyeriar in https://github.com/prisma/docs/issues/1391#issuecomment-1159389984_

**Comment by Emnalyeriar** [comment]
Link to the code snippet from other issue: https://github.com/prisma/docs/issues/1391#issuecomment-932810642

**Comment by ruheni** [comment]
This is done. Feel free to reopen the issue if anything else needs to be addressed.
