### ISSUE TITLE
Consider qualifying the raw query data conversion types table

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3303]
In [this section](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#raw-query-type-mapping) of the raw database access doc, the table is perhaps too simple, because the details are not true for all database engines.

Flavian pointed out that there are small differences in the raw mapping type, depending on the database engine. For example, MariaDB stores JSON as a string, so it's coerced as a string on the JavaScript side. SqlLite always defaults to BigInt when there's no column information (e.g. with SELECT 1 + 1), unless there's a type case.

We might want to either add these exceptions to the table or add a qualification to the text above or below the table.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
