### ISSUE TITLE
MongoDB: clean up links to Atlas in Get Started docs

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3306]
In both of our Get Started docs (scratch and add) we have two links to Atlas... we should reconsider having just one link.

Should new link go to [the high-level page Getting Started with Atlas (UI or CLI)](https://www.mongodb.com/docs/atlas/getting-started/)
OR
should it go to [a very specific page about how to use the Atlas CLI to create your cluster](https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-quickstart/)?

[Slack convo](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1655839738552839)

**Comment by TasinIshmam** [comment]
I realize now that we actually have two links already, one of which provides instructions for *both* the UI and CLI. I previously incorrectly thought that both were the same link to the Atlas landing page. 

In that case, it seems fine as it is as users have the option to use whichever they prefer (GUI or CLI). Perhaps in that case, no change is necessary? 

Sorry for the confusion in slack 😅
