### ISSUE TITLE
Isolate code snippets that show how not to do something

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3313]
[[Slack convo](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1655920057953199)] Our docs contain a few code snippets that illustrate how not to do something. If readers are skimming quickly, they might copy the wrong sample and try to use it. We need to decide how to handle this:

-- remove any examples that are wrong, and instead write "in-line" about things to avoid not to do
--leave them, but somehow brand with red box or something to indicate they should not be copied (and remove the copy icon)
-- ??

Examples in our docs:
https://www.prisma.io/docs/concepts/components/prisma-schema/relations#disambiguating-relations

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
