### ISSUE TITLE
Update admonitions to include CockroachDB

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3320]
In our Reference docs, and likely elsewhere, we need to add CockroachDB to several admonitions that currently say "Available only in PostgreSQL and MongoDB" or  "This feature is available from version 3.5.0 onwards in PostgreSQL only."

For example in this [Prisma Issue](https://github.com/prisma/prisma/issues/13892#issuecomment-1164968200), a auser notes that the [Prisma client's docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#push) it says that `push` method is "Available for PostgreSQL and MongoDB only."

A helpful guideline: We can [generally assume that] everything that works on PostgreSQL, also works on CockroachDB, unless we explicitly mentioned it in the limitations page of the CockroachDB connector.

**Comment by janpio** [comment]
(Note that this is probably not only in thigns explicitly mentioned as admonitions, but also just in text or tables)
