### ISSUE TITLE
Search in Docs improvement: results list

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3323]
Currently in our Docs, if you search for a term, then click on a link of one of the returned results, you lose that list of results. 

It would be great to have a way to return to the search results. As it is right now, you have to re-enter the search and start over.

**Comment by nilubava** [comment]
@tanberry This seems to be the default behaviour in almost all the documentation websites that I checked. This requires some work, so can I get some example sites with this behaviour?
