### ISSUE TITLE
Add guide for converting from existing implicit many-to-many relation to an explicit many-to-many relation

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma2-docs#3325]
Converting from an implicit to explicit m-n relation is a fairly common use case that is not trivial, but we lack any guidance in our docs. It would be helpful to have a comprehensive guide that shows an example of how to do this.

[Slack convo #1](https://prisma-company.slack.com/archives/CGMCB82N8/p1655416373649939)
[Slack convo #2](https://prisma-company.slack.com/archives/C02FNFLDUS3/p1642767948119800)
[Frederik's repo](https://github.com/floelhoeffel/prisma-implicit-explicit-relations/tree/main) outlining a potential workflow

**Comment by serg06** [comment]
It would be great to learn how to do this backwards as well.

I'm adding Prisma to an existing DB schema; I did `prisma db pull` and it's full of explicit relations; I'd like to convert them to implicit ones.

**Comment by nikolasburk** [comment]
Quick update: The PR is still being worked on

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
