### ISSUE TITLE
Search results: returning <html> markup

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3329]
Search results sometimes expose html markup, even though the markup is not rendered on the actual page. @Zach said this might be caused by the search engine indexing the markup... it should exclude any html markup. 

[Slack convo here](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1656105199444979).

**Comment by tanberry** [comment]
From Jan: "If I remember correctly we had a function to clean our content before we send it to Algolia for indexing and already have quite a few "sanitization" steps in there. Nilu used to tweak those when we got the search until it became usable."

**Comment by andrew-walford-prisma** [comment]
I found another example: if you search for `terminal`, it returns the following:

![image](https://user-images.githubusercontent.com/105220540/179227386-e1ab2159-a4f4-449b-a08c-df95e0eb7165.png)

**Comment by tanberry** [comment]
Closing this as a duplicate of https://github.com/prisma/docs/issues/3092
