### ISSUE TITLE
Docs: Prisma no longer exports Prisma.dmmf.schema into the generated Client (breaking change for upgrade guide)

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3334]
Add note to upgrade guide that:

From version 4.0.0, Prisma no longer exports Prisma.dmmf.schema into the generated Prisma Client. This makes the generated Prisma Client much more efficient, and also avoids some memory leaks with Jest.

Note:
- This change does not affect the DMMF that Prisma passes to the generators.
- You can use getDmmf()from @prisma/internals to access the schema property.
- We still export Prisma.dmmf.datamodel into the generated Prisma Client.

**Comment by janpio** [comment]
Please note here:
- Nothing about `@prisma/internals` should be documented. It is an internal package.
- `Prisma.dmmf` also is not something that should be officially documented.

**Comment by Jolg42** [comment]
So nothing to do here. This issue can be closed?
