### ISSUE TITLE
docs: prisma generate post install

### ISSUE THREAD

**Issue by schalkneethling** [prisma/prisma2-docs#3339]
The docs at https://github.com/prisma/docs/blob/main/content/100-getting-started/02-setup-prisma/100-start-from-scratch/120-mongodb/200-install-prisma-client.mdx states that `prisma generate` is automatically run after running `npm install @primsa/client`.

I ran the `npm` command using both Node v16.x and v18.x and with neither was `prisma generate` automatically run afterward. I do have a schema file at `prisma/schema.prisma`.

**Comment by schalkneethling** [comment]
Just found this on a different page: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#the-prismaclient-npm-package:

> This command also runs the prisma generate command, which [generates the Prisma Client into the node_modules/.prisma/client directory](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#the-prismaclient-npm-package).

I checked and `node_modules/.prisma/client` does indeed exist. Again though, running the install command only shows the following output:

```bash
❯ npm i @prisma/client 

added 2 packages, and audited 60 packages in 859ms

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by schalkneethling** [comment]
Apologies for all the comments 😄, I keep finding other pieces and putting it all together.

What I did in the end is install `prisma` using:

```bash
❯ npm i --save-dev prisma

added 2 packages, and audited 62 packages in 12s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I added the following to `scripts` in `package.json`:

```json
"prisma:generate": "prisma generate",
```

Running the script target now gave me this output:

```bash
❯ npm run prisma:generate

> artic-sidekick-api@0.0.1 prisma:generate
> prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.0.0 | library) to ./node_modules/@prisma/client in 54ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

**Comment by janpio** [comment]
`npm` does not output `postinstall` script's output any more since a few versions.
If you start with an empty project (but a schema.prisma file) and then isntall `prisma` and `@prisma/client` you should have a generated Client in `node_modules/.prisma/client` which indicates that `prisma generate` was indeed run under the hood.

**Comment by schalkneethling** [comment]
> `npm` does not output `postinstall` script's output any more since a few versions. If you start with an empty project (but a schema.prisma file) and then isntall `prisma` and `@prisma/client` you should have a generated Client in `node_modules/.prisma/client` which indicates that `prisma generate` was indeed run under the hood.

Thank you for the reply, I got everything working. It might be useful to update the docs to reflect this change. Happy to do it if you agree.

**Comment by janpio** [comment]
I am not sure what there is to update, but of course a PR would make that clear - so go ahead and link to it here.

**Comment by ruheni** [comment]
TODO
- [ ] Clarify postinstall step is run and shouldn't expect any output because it generation happens silently
