### ISSUE TITLE
Fulltext search docs improvement

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3350]
Currently we have the following docs for full text search/indexes:

- Indexes concepts page has a section on [Full-text indexes](https://www.prisma.io/docs/concepts/components/prisma-schema/indexes#full-text-indexes-mysql-and-mongodb) for **MySQL** and **MongoDB**
- [Full-text search concepts page](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search) for **PostgreSQL** and **MySQL**
- [Client API reference entry for`search`](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#search) for **PostgreSQL** and **MySQL**
- Filtering and sorting concepts page has a [Sort by relevance](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-by-relevance-postgresql) section for **PostgreSQL**

Missing:
- documentation of `@fulltext` in the [schema reference attributes section](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#attributes)
- document index limitation for MongoDB - see prisma/prisma#2729 
- MongoDB full text search?
- PostgreSQL full text indexes?
- links to index configuration docs from client full text search docs - see comment [here](https://github.com/prisma/prisma/issues/13562#issuecomment-1142088653)

**Comment by janpio** [comment]
Current state:

> MongoDB full text search?
Not implemented yet.

> PostgreSQL full text indexes?
Not adequately implemented yet to be worth documenting.

**Comment by janpio** [comment]
Note that `_relevance` is related to `fullTextSearch` and has a docs issue as well: https://github.com/prisma/docs/issues/5045

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
