### ISSUE TITLE
Add new page front matter tag:  `search`

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3358]
Can we have a new page front matter tag: ~`excludeFromSearch`~ `search`?

Update, 21-july-2022: the docs team would like to change the proposal slightly, so I've edited this ticket.

- This would be a boolean value.
- If the tag is set to false (`search: false`), then the page would be excluded from
   - our internal site search
   -  external searches (e.g. Google)
- If the tag is omitted, then it will default to true (in other words, the page will be included in search results).

This would be useful for pages we don't want to pollute the search results, such as style guide pages.

If a page has this tag set to `false` in conjunction with the [hidePage](https://www.prisma.io/docs/about/prisma-docs/style-guide/frontmatter#hidepage) tag, then it would be completely invisible to users (except if they know the URL). This could be useful to let the docs team publish draft pages.

This would be really useful to the docs team, so if it's viable to implement we'd appreciate it!

**Comment by tanberry** [comment]
The ability to hide pages from search (and not have them returned in results) wold be very useful for when PMs/Devs want to  do an early Beta of some feature/functionality that is not yet officially released, and we want early feedback on the Docs in parallel to feedback on the feature. @Nilu if possible can we fit this one into the next sprint? Or the over-next one. :-)

**Comment by nilubava** [comment]
@andrew-walford-prisma Is this still relevant?
