### ISSUE TITLE
Style guide: resolve terminology list

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3359]
Agree terms to use - e.g. for product names.

Determine how we express these - e.g. what capitalization we use, whether we use articles.

Examples:
- Prisma schema
- Schema
- Prisma Schema
- The Prisma Schema
- The schema

**Comment by tanberry** [comment]
We can use the [Terminology page in Notion](https://www.notion.so/prismaio/Terminology-and-Usage-WIP-8f763e861d4f4114b17b1210eb3b6d99) as a place to collect and gain consensus. This page has been shared widely with Engineering and other teams, so let's keep it as the source of truth, for now, until we have final decisions and can then move terms into Style Guide.

**Comment by ankur-arch** [comment]
Closing this as we already have a guide for [this](https://www.prisma.io/docs/about/style-guide/prisma-product-names).
