### ISSUE TITLE
Get started: clarify role of schema

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3368]
https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/install-prisma-client-typescript-postgres

In my opinion, we should more clearly explain in our get started guide - probably in the above file - that when a user changes their schema, this doesn't change the database - it's just the model that Prisma uses to build the client.

**Comment by ruheni** [comment]
Improve this 
> Whenever you make changes to your Prisma schema in the future, you manually need to invoke `prisma generate` in order to accommodate the changes in your Prisma Client API.
