### ISSUE TITLE
Consider clarifying connection URL/database URL

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3373]
See discussion here: https://prisma-company.slack.com/archives/C02F5A44DE2/p1657010203699989

The conversation is still ongoing at the time of writing this ticket, so I won't add any more details until it becomes clear what, if anything, we need to change.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
