### ISSUE TITLE
Document package.json generation in custom paths

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3377]
SME is Serhii

This has been pushed back. Also, the error is covered in the CLI, so it might not need docs as well.

The solution, if any, hasn't been decided on - it's pending more information.

Tech spec: https://www.notion.so/prismaio/package-json-generation-for-custom-output-paths-b264a29549434121978d0571305150fa

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
