### ISSUE TITLE
Prisma 1: add historical information about the release and links to docs

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3382]
- Add information about Prisma 1 and its history in a separate page
- Add links to existing Prisma 1 docs: https://v1.prisma.io/docs/1.34

This new docs page also should also cover the use case of users being able to find Prisma 1 information after the removal of the **Prisma 1 Docs** top-level link.

**Comment by ruheni** [comment]
We've sunset Prisma 1 and currently not maintaining it.
