### ISSUE TITLE
When navigating any of the getting started sections via left navigation, state of language/db user choice is lost

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma2-docs#3392]
## Reproduction

1. Go to: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/connect-your-database-typescript-postgres
2. use right hand drop down to change database from `postgres` to anything else (here: `mysql`)
3. hover over any of the links (siblings) and note in the status bar how the link points to `postgres` instead of the choice of the user `mysql`
4. click and note how you are now looking at step 2 of the guide but for the wrong database

**Comment by floelhoeffel** [comment]
Demo: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1657199361608959

**Comment by meletj** [comment]
Related to https://github.com/prisma/docs/issues/2167

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
