### ISSUE TITLE
PDP: List supported db connection string arguments

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3401]
We support a different set of db connection string arguments, depending on the database. Should be documented as a reference separate of configuring/setting the db connection string.

Slack conversation: https://prisma-company.slack.com/archives/C01UR43BV6W/p1656354831111829

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
