### ISSUE TITLE
Google Analytics: add exclusion for Percy diff tool

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#3403]
The code impacted would probably be the following (TODO check if we need to update anything else): 
https://github.com/prisma/docs/blob/main/src/utils/stats.js

[Related Slack thread](https://prisma-company.slack.com/archives/CC59J6VEY/p1657530002810279?thread_ts=1657522801.326979&cid=CC59J6VEY)

We discovered that when Percy runs a diff, it pollutes Google Analytics by sending events for all the pages it captures, and they do not start with `/docs/`.

We want to make it so that Percy doesn't trigger Google Analytics events anymore.

Potential solution: do not initialize the Google Analytics script if `host.includes('localhost')`

**Comment by janpio** [comment]
Percy happens via https://github.com/prisma/docs/blob/d11dd026ec6efae72094b9fa6db11154f563a775/.github/workflows/ci.yml#L10-L22 We could probably define an env var there that then has as a result that we do not include Google Analytics.
