### ISSUE TITLE
Remove "preview" pill from navigation on indexes

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma2-docs#3404]
Indexes is not in preview anymore (note the pill in the menu on the right). Please remove.

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/6864947/178251987-18814c0c-eefa-4f57-be26-a0f433f09b1e.png">

**Comment by keerlu** [comment]
Sorry, completely missed this. Just created a PR.
