### ISSUE TITLE
Consider separating return type from thrown exception in API docs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#3406]
I just noticed that we're "bundling" the type of the exception that's thrown with the return type of a method, e.g. for [`delete`](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#delete):

<img width="472" alt="image" src="https://user-images.githubusercontent.com/4058327/178307066-48585426-77ad-4f79-b143-9ac4c36f308b.png">

 IMO, this is not quite accurate because the exception doesn't impact the return type. E.g. in this snippet:

```ts
const x = await prisma.user.delete({ where: { id: 1 } });
```

`x` is just typed to `User`, so the return type of the entire method is just `User`, it _never can_ return anything else:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/4058327/178307444-fbf8bef4-1125-44a6-b811-9819577b6f22.png">

It _can_ however _throw_ an exception, which in my understanding is different than a return type and therefore probably should be treated separately in the docs as well.

**Comment by tanberry** [comment]
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#delete

**Comment by tanberry** [comment]
Thanks, @nikolasburk thanks for catching this. Question: can one ever actually get a return value (an output) of `RecordNotFound`?

It might "just"  be semantics... but in general I agree with you that exceptions/errors are not really return types, and so it should not be included in that table, nor the column labeled "Return type". There could be a H3 section below for exceptions.

**Comment by nikolasburk** [comment]
> can one ever actually get a return value (an output) of RecordNotFound?

afaik the only way to obtain an object of type `RecordNotFound` is by using `try` / `catch` and catching the exception of that type.


> There could be a H3 section below for exceptions.

I think it might be worth looking at how other API docs handle such cases and how they're pointing out whether method throws an exception or not.

**Comment by janpio** [comment]
The obvious/naive solution would be a headline "Exceptions" - but there are a lot more. This is just a special one of this kind of method I guess, so it might need to be "Method specific Exceptions" or similar. (Not sure that is actually true)

**Comment by nikolasburk** [comment]
>  This is just a special one of this kind of method I guess, so it might need to be "Method specific Exceptions" or similar.

I had in mind something similar as well. I also wonder whether there _are_ already any best practices for this, e.g. in JSDoc you can use the [`@throws`](https://jsdoc.app/tags-throws.html) annotation which would be appropriate here I guess.
