### ISSUE TITLE
Add documentation for client tracing

### ISSUE THREAD

**Issue by garrensmith** [prisma/prisma2-docs#3414]
Add documentation for client tracing. This should include:
* How to enable it with a collector
* How to log to console (if this is possible)
* What information it provides

**Comment by garrensmith** [comment]
For the documentation, we need to make a mention around tracing and performance. Below is a rough idea of what I think we need to say:

Tracing gives deeper insight into what is happening in an application. But it can also affect the performance of your application. If the application generates a lot of spans and they need to be send to a collector, this will slow down the application. Here are some recommendations to try and avoid affecting the performance of your application

## Use the bulk exporter
When using the application use the `BulkSpanExporter` to send the spans to a collector in batches rather than one at a time. The `BulkSpanExporter` waits and collects a number of spans before sending them to the collector. This isn't always useful when doing development. So in testing and development rather use the `SimpleSpanProcessor`. You can consider a setup as below:

```js
import {
  
  SimpleSpanProcessor,
  BatchSpanProcessor,
} from '@opentelemetry/sdk-trace-base'


if (process.env.NODE_ENV === 'production') {
  provider.addSpanProcessor(new BatchSpanProcessor(otlpTraceExporter))
} else {
  provider.addSpanProcessor(new SimpleSpanProcessor(otlpTraceExporter))
}
    
```

## Send only a sample of the spans

Another way to avoid a performance penalty with tracing is to (use probability sampling)[https://opentelemetry.io/docs/reference/specification/trace/tracestate-probability-sampling/]  and send less spans to the collector.
This will reduce the collection cost of tracing but still give a good representation of what is happening in the application. 
An example implementation would look like this:

```js
import { TraceIdRatioBasedSampler } from '@opentelemetry/core'

const provider = new BasicTracerProvider({
    sampler: new TraceIdRatioBasedSampler(0.1),
    resource: new Resource({
      // we can define some metadata about the trace resource
      [SemanticResourceAttributes.SERVICE_NAME]: 'test-tracing-service',
      [SemanticResourceAttributes.SERVICE_VERSION]: '1.0.0',
    }),
  })

```

**Comment by andrew-walford-prisma** [comment]
Ah, thanks @garrensmith  I'll bring your notes into my PR tomorrow.

**Comment by andrew-walford-prisma** [comment]
Note: there's a separate docs ticket for this, where I've been putting updates. [Docs ticket](https://github.com/prisma/docs/issues/3342)
