### ISSUE TITLE
Clarify `migrate resolve --rolled-back` only works with failed migrations

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#3420]
API Reference: https://www.prisma.io/docs/reference/api-reference/command-reference#migrate-resolve

The `prisma migrate resolve --rolled-back <migration_name>` only works with failed migrations. When run against a database with no migration history issues, it leads to the following error:

```
❯ npx prisma migrate resolve --rolled-back 20220714121901_add_profile
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "schema-prototyping", schema "public" at "localhost:5435"
Error: P3012

Migration `20220714121901_add_profile` cannot be rolled back because it is not in a failed state.
```

**Comment by tanberry** [comment]
Ah, thank you @ruheni ! This is an excellent bit of info to add to the Reference docs about `migrate resolve`, and quite likely elsewhere where we write about "rollbacks".
