### ISSUE TITLE
Wrong Example: `.$on('query')`, query is not a valid argument

### ISSUE THREAD

**Issue by ogroppo** [prisma/prisma2-docs#3424]
This example is reported but only `beforeExit` is allowed 

```
prisma.$on('query', (e) => {
  console.log('Query: ' + e.query)
  console.log('Params: ' + e.params)
  console.log('Duration: ' + e.duration + 'ms')
})
```

<img width="692" alt="Screenshot 2022-07-15 at 11 31 08" src="https://user-images.githubusercontent.com/4820803/179196217-70b0c4d7-3a54-4908-b128-7a088adabaa7.png">

**Comment by janpio** [comment]
Did you enable logging of queryies in your Prisma Client constructor? The types usually only allow using the different events when they are actually available.

**Comment by ogroppo** [comment]
tried as string and object yes
<img width="384" alt="Screenshot 2022-07-15 at 12 11 08" src="https://user-images.githubusercontent.com/4820803/179203070-1dca1fff-afdc-4cfa-86d2-5f1707d55910.png">
<img width="372" alt="Screenshot 2022-07-15 at 12 10 56" src="https://user-images.githubusercontent.com/4820803/179203076-28844b3d-6ddc-44be-9a8f-eff280b0c5a6.png">

**Comment by Jaysok** [comment]
After 5 min delving in, I found a way to make it work. You can do this like below. 

```typescript
export const prisma = new PrismaClient<Prisma.PrismaClientOptions, 'query'>({
  log: [
    {
      emit: 'stdout',
      level: 'query',
    },
  ],
});
```

I think the typing of `PrismaClient` should support the code in the document.

And before doing that, the document should notice that the code raises TSError and provide a solution to make it work.
```
error TS2345: Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.
```

**Comment by ogroppo** [comment]
Great, Thank you!

**Comment by nikelborm** [comment]
Might be fixed in https://github.com/prisma/prisma/pull/24133
