### ISSUE TITLE
Broken syntax highligthing

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#3439]
Seems like the coloring of the fields and types are mixed up in several MongoDB snippets, e.g. on this page: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4#enforced-use-of-unique-or-id-attribute-for-one-to-one-and-one-to-many-relations-mysql-and-mongodb

<img width="523" alt="image" src="https://user-images.githubusercontent.com/4058327/179550956-adf22fb5-f1ef-4347-a841-0481adebb8dd.png">

**Comment by keerlu** [comment]
It looks like we already have #2476 for this. I'll close as a duplicate but will bring that one up again as a good website issue to get fixed
