### ISSUE TITLE
Get Started guide for MongoDB, clarify connection string

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3442]
The content  about connection URLs in the Get Started guides (both from scratch and existing) for MongoDB is a confusing mishmash of Atlas-centric commands and examples with non-Atlas commands.

Let's figure out a way to present the proper instructions and examples for both, but keep them separate on that page. Maybe a tabbed section? Or a tech switcher?

See this [Slack thread ](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1658160357427289)for an issue about needing to append `?authSource=admin` to their connection string if NOT using Atlas.

See this [Slack thread](https://prisma-company.slack.com/archives/C02FZENHD4N/p1658178831451219) for some info about the error that one gets with Atlas, if you simply copy/paste the connection string from the MongoDB UI (without adding in the database name).

See this[ Prisma issue](https://github.com/prisma/prisma/issues/13647) where a user ran into the problem of not knowing to add the database name in (if using Atlas).

**Comment by keerlu** [comment]
Linked to #3306
