### ISSUE TITLE
Data proxy post GA

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3451]
SME: Alexey and Garren

This doesn't need docs yet. If it does in future, Alexey will message us (or of course we can check later in the sprint).

**Update 16-aug-22:** They are implementing query logging and doing data proxy tests with MiniProxy. As of writing, no docs needed for this work.

- Eng ticket: https://github.com/prisma/client-planning/issues/24
- Notion page: https://www.notion.so/prismaio/Data-Proxy-Post-GA-a51f78ac2c34437fa62cfa920fc6ab34

**Comment by jharrell** [comment]
Our new [Accelerate docs](prisma.io/docs/data-platform/accelerate) most likely supersede this issue.

**Comment by janpio** [comment]
The work in 5.2 to make the usage of DataProxy/Accelerate simpler actually is the "post GA post GA" that finishes what got started here.
