### ISSUE TITLE
doc 404 issue

### ISSUE THREAD

**Issue by KimGenius** [prisma/prisma2-docs#3472]
hello!

i showing all page to 404 page... 😢 

![스크린샷 2022-07-21 오후 6 05 59](https://user-images.githubusercontent.com/29722636/180175587-2acd983d-c922-44a1-8b19-4d40a0064d66.png)

**Comment by alovega** [comment]
Hello what's up with your docs?

**Comment by KimGenius** [comment]
oh this issue solved !
Sorry, and Thank you!

Have a good day
