### ISSUE TITLE
Issue with Docs site

### ISSUE THREAD

**Issue by alovega** [prisma/prisma2-docs#3473]
Your documentation site has an issue I was using it and it went down I can't navigate 

![Screenshot from 2022-07-21 12-13-43](https://user-images.githubusercontent.com/38653871/180177311-e6710750-65da-4b35-ab08-75a0ee93e57a.png)

**Comment by alovega** [comment]
It was restored but I can't follow through with the docs is like you have removed the follow-through steps in the docs

**Comment by alovega** [comment]
> 



> It was restored but I can't follow through with the docs is like you have removed the follow-through steps in the docs

are you guys making changes on the live branch or what is happening?

**Comment by nilubava** [comment]
This is resolved.
