### ISSUE TITLE
Placeholder issue - GIS schema documentation

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3477]
This is placeholder issue to keep track of information about the upcoming GIS work. May get turned into an epic when there is more knowledge of exactly what docs this will need.

Information:

- [Discovery document on spatial types](https://www.notion.so/prismaio/Discovery-Spatial-Types-Indices-and-Queries-in-Prisma-e259f2fb180648b0b1ad1a3262f75830) 

Thoughts about where docs are likely to go:
- Schema reference: 
  - new types e.g. `Geography`, `Geometry`, `Point`, `Polygon`. See [list of database types](https://www.notion.so/prismaio/Discovery-Spatial-Types-Indices-and-Queries-in-Prisma-e259f2fb180648b0b1ad1a3262f75830#942b2f0057794bb48d98402cf4c12010) in the discovery doc.
  - any new native type attributes
  - new index options. See [Spatial indices](https://www.notion.so/prismaio/Discovery-Spatial-Types-Indices-and-Queries-in-Prisma-e259f2fb180648b0b1ad1a3262f75830#259962e1a6fe44faa49d2d17392432f5) in the discovery doc
- New guide on how to use GIS schema features
  - how to use geometry vs geometry
  - how to use types like `Point` or `Polygon`
  - how to configure indexes
- What about client side? will this be done by the Client team?
  - New guide to common queries: see [list in the discovery doc](https://www.notion.so/prismaio/Discovery-Spatial-Types-Indices-and-Queries-in-Prisma-e259f2fb180648b0b1ad1a3262f75830#cd4c904bd17e4ef5b80d5f0db72de505): e.g. within, intersects, find within given distance...

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
