### ISSUE TITLE
Add content in Docs about how to reduce bundle size

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3500]
For serverless users, we need to make sure they understand that using the Data Proxy will reduce the size of the Prisma bundle, and thus improve performance.

The engineering team is working on further ways to reduce the bundle size, via Lambda layers, that doesn't necessarily require DP. Niko might do a stream or blog etc about it...

**Proposed structure of doc(s)**: start with the task of "Reduce bundle size", then explain the diff ways to achieve this. Make this the main, task-centric guide. Then, elsewhere iin the Docs we can link to it as needed. For example, in the Data Proxy docs, we can mention it and say "To learn more about using the data proxy in a serverless environment to increase performance even more, refer to our documentation about optimizing bundle sizes."

Based on above, the topic would likely live under Performance & Optimization section, but we will figure that out when we start writing.

Note: We need to be cautious to not make it sound like we are "heavy".

Resources:
https://www.notion.so/prismaio/Reducing-Size-of-node_modules-for-Lambda-Serverless-Users-9648c7b39a094bd4be44e2b2d443d262

**Comment by andrew-walford-prisma** [comment]
This one feels like a candidate for us to work on.

**Comment by ankur-arch** [comment]
Outdated.
