### ISSUE TITLE
Deployment guides: add steps for enabling the Data Proxy

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3523]
Review all Deployment guides and see which ones need to have the steps included to have the Data Proxy enabled.

**Comment by zachtil** [comment]
This one feels like a duplicate of #3509.

**Comment by janpio** [comment]
There are some where it is _needed_ (e.g. Cloudflare workers where you can not talk to the database directly), but those should have the steps in already.

**Comment by zachtil** [comment]
The one about CFW seems to be the only one. In this case, this issue does not make sense in terms of the current content. 

In terms of the new content on the serverless initiative, if the guide requires PDP, I am sure we will document that.

Should we continue having this issue then?

**Comment by zachtil** [comment]
Closing this issue as it is a duplicate of #3509.
