### ISSUE TITLE
terminology: 'records' vs 'entries'

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3532]
There's the need to reevaluate the use of the term 'records' to indicate a row of data in a database table because this has worked great for relational databases, but perhaps is not as accurate in the context of MongoDB.

Similar to how we have umbrella terms, such as 'models' (for 'tables' in rel. databases and 'collections' in MongoDB) and 'fields' (for 'columns' in rel. databases and 'document field' in MongoDB), we could instead use 'entries' to denote 'records' in rel. databases and 'documents' in MongoDB.

So far (Jul 29, 2022), we're have the following stats across the docs:

* "records" - 568 instances
* "record" - 340 instances
* "entries" - 14 instances
* "entry" - 7 instances

This could be explained by the fact that MongoDB was the last database to be added which might be why 'record' has been the dominant term across the docs.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
