### ISSUE TITLE
Prepend `npx` to our example commands

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3538]
Since most of our users install Prisma locally (not globally), they will need to use `npx` with their commands.

Most of the commands in our CLI Reference section need `npx` prepended to them, and there are probably many scattered around elsewhere.

For details, see this Slack thread: https://prisma-company.slack.com/archives/C02JV0K2Q31/p1654595286707199

Let's also add more info, where appropriate (like in the CLI Reference?) about Prisma installed locally (need to prepend `npx`) versus globally (no need to use `npx`). We can link to this topic as appropriate: https://nodejs.dev/learn/npm-global-or-local-packages

**Comment by ObamaTheLlama114** [comment]
I have found that all across the docs we use npx pretty inconsistently. We could either use it everywhere, or use it nowhere and in the cli reference section, inform the user about prepending npx.
