### ISSUE TITLE
Old topics need to be archived/redirected

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3540]
There are several topics that our users get via Search (need to clarify here), that are no longer relevant. These topics need to be removed/archived, and redirected to whatever the current parallel topic is.

https://www.prisma.io/docs/guides/general-guides/database-workflows

See details in [this Slack convo](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1659343222228289).

**Comment by janpio** [comment]
Old related issue I found about this: https://github.com/prisma/docs/issues/789 (The PR resolving it looks super weird though, not sure what was going on there)

**Comment by tanberry** [comment]
@nilubava , can we use a 410 http header to really show that we are deleting these, not just redirecting?

**Comment by ruheni** [comment]
The guide seems to be gone now. I'll go ahead and close the issue.

**Comment by janpio** [comment]
That the old link is a 404 nicely shows how we failed at actually achieving the original goal.
