### ISSUE TITLE
Vercel issues

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3545]
This ticket is to track the various challenges with the Vercel deployments.

-- A large number (majority) of builds are failing, and writer has to redeploy 
-- Need a Slack channel (#feed-vercel-docs)
-- GitHub Actions bot not fully working
-- Sometimes get a 404 on Vercel page when you click on the link to "Inspect" a failed build.

**Comment by tanberry** [comment]
Strange date of Sept 1, 2022 on Vercel UI:
![Screen Shot 2022-08-02 at 7 19 50 AM](https://user-images.githubusercontent.com/9368837/182377251-267b4314-f5ad-4a8d-bcb6-69d2d2587d2a.png)

**Comment by nilubava** [comment]
@tanberry Can you give me an example for "GitHub Actions bot not fully working"
