### ISSUE TITLE
Tab for switching code samples does not work on Chrome and Firefox

### ISSUE THREAD

**Issue by eemmiillyy** [prisma/prisma2-docs#3549]
When visiting https://www.prisma.io/docs/concepts/components/prisma-schema/relations#terminology on Google chrome (Version 103.0.5060.134 (Official Build) (x86_64)) clicking the `MongoDB` tab does not switch the code sample.  

Firefox also is not working (103.0.1 (64-bit))

Safari (Version 13.1.3 (15609.4.1)) seems to work. 

<img width="665" alt="Screenshot 2022-08-03 at 10 08 18" src="https://user-images.githubusercontent.com/55739812/182557544-70495feb-109f-410b-b465-18237d34a9fb.png">

**Comment by janpio** [comment]
Working on Chrome (Version 103.0.5060.134 (Official Build) (64-bit)) on Windows.

**Comment by eemmiillyy** [comment]
I just checked again and now it's working 🤨 Well that was weird! Never-mind then.

**Comment by janpio** [comment]
Best bugs are the ones that go away by itself :D
