### ISSUE TITLE
PDP: Data Browser - closing a tab with unsaved changes and filtered views requires confirmation

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3551]
Linear: CP-2184
Add a sentence or a note that when you close a model view tab in the Data Browser, it will require confirmation in these 2 cases:

* filters are applied.
* unsaved changes to added or edited records

Size: S

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
