### ISSUE TITLE
link in docs & code comment is broken

### ISSUE THREAD

**Issue by liesislukas** [prisma/prisma2-docs#3575]
### Bug description

Here:
https://github.com/prisma/prisma/blob/main/packages/client/src/generation/generateClient.ts#L349

and here:
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#naming-conventions

also on docs site imo it should open in new tab and have that little external link icon

![image](https://user-images.githubusercontent.com/2733862/183309711-5c6561c9-88fa-444f-9ea7-5224e44a3577.png)

![image](https://user-images.githubusercontent.com/2733862/183309762-6166ea56-66c0-4d19-90e2-40050cf7782b.png)

### How to reproduce

-

### Prisma information

-

### Environment & setup

web

### Prisma Version

newest

**Comment by ruheni** [comment]
The links should be functional now. 🙂 

I'll update the labels for adding icons for external links, which should open in a new tab. Here's a related issue that's actively being worked on: https://github.com/prisma/docs/issues/530

**Comment by meletj** [comment]
Links are functional, and external links icons have been implemented.
