### ISSUE TITLE
Document multi-schema support (client side)

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3581]
Client team are adding functionality to allow multi-schema support.

I am not sure yet if there are any user-facing changes on the client side, so I'm making this issue as a placeholder. I will research this in the coming days.

SMEs: Flavian, Pierre

**Comment by janpio** [comment]
There will be no user facing changes from the Client side. All changes are for PSL, Introspection and Migration.

(Schema team owns and runs the project)

**Comment by andrew-walford-prisma** [comment]
There are no customer-facing changes on the Client side, as per Jan's note, so I'm closing this issue.
