### ISSUE TITLE
Add mental model conceptual guide to Migrate docs

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3586]
Add some conceptual information/diagrams giving a high level overview of different Migrate commands

See @ruheni's PR: #3749

**Comment by Jolg42** [comment]
PR https://github.com/prisma/docs/pull/4214

**Comment by ruheni** [comment]
Merged in https://github.com/prisma/docs/pull/4214

**Comment by Jolg42** [comment]
https://www.prisma.io/docs/concepts/components/prisma-migrate/mental-model
