### ISSUE TITLE
Deploy on Vercel: add instructions to explicitly run `npx prisma generate` on Vercel.

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3590]
Typically, our deploy operation will trigger `npx prisma generate` behind the scenes, using a post-install hook. However, Vercel caches dependencies, so the hook doesn't get called on re-deploys.

Solution/workaround is to explicitly run `npx prisma generate` when deploying to Vercel. @sabinadams or @millsp can you add a bit of detail in a comment below about when exactly in the deployment workflow does the user run this command?

Impacted Docs (there might be others): https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-vercel

There is a Note in this topic that says:
"Note: The build step defined in package.json as the vercel-build script, will run prisma generate && prisma migrate deploy && next build to generate Prisma Client, apply migrations, and build the Next.js project."

This note needs to be edited....

**Comment by sabinadams** [comment]
Just ran through the steps in that tutorial and it actually seems `npx prisma generate` is being run when deployed to Vercel via its automatic `build` script detection.

In general, however, the `npx prisma generate` step would need to be added to the `build` step when deploying to Vercel.

**Comment by janpio** [comment]
The Vercel situation is _very_ complicated, there is unfortunately currently not one state that can be documented that works in all situations. We know that sucks for our users.
