### ISSUE TITLE
Missing `@map` for fields example

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3593]
Add `@map` for fields to schema data model page to match `@map` for models

From @janpio:

> I think we are missing an `@map` for fields example on https://www.prisma.io/docs/concepts/components/prisma-schema/data-model
> (We do have https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#mapping-model-names-to-tables-or-collections for tables/models)
> (We also have something for fields here: https://www.prisma.io/docs/concepts/components/prisma-schema/names-in-underlying-database#map-field--column-names)

Slack link: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1655967600496789

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
