### ISSUE TITLE
Update error code Python script

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3595]
Currently we have [this Python script](https://github.com/mhwelander/doc-tools/blob/master/error_code_parser.py) that pulls in error codes from the prisma-engines repo and formats them for our [Error Reference page](https://www.prisma.io/docs/reference/api-reference/error-reference).

At a minimum it would be nice to have a forked version of this script that is nicely commented with informative variable names, so it's easy to read and maintain.

There was also some discussion in [this old PR](https://github.com/prisma/docs/pull/2938) (which I never finished, oops) about some information that is currently missing from the script and getting manually added, so if this is also easy to automate it would be good to include it.

Relevant old discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1646209993731929
Some instructions on running the script [here](https://www.notion.so/prismaio/Generating-reference-docs-8b414ab78bdc470fa3da745cf32e2495)

**Comment by tanberry** [comment]
Yay for code comments. ;-)

**Comment by tanberry** [comment]
Can we tweak the script to make it pull in PDP error codes, which are in private repo.

**Comment by ObamaTheLlama114** [comment]
https://github.com/prisma/docs-tools/pull/41

**Comment by ObamaTheLlama114** [comment]
The error code script has been rewritten. Closing this issue.
