### ISSUE TITLE
Fix 'Developing with Prisma Migrate' guide loose ends

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3601]
There are a few oddities in [Developing with Prisma Migrate](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate) that broke the flow when I tried to follow it:
- There's [an intentional typo](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate#:~:text=biograpy%20String%20//%20Intentional%20typo!) in the schema, but it isn't fixed anywhere (this example does get used on a [different page](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations#renaming-a-field))
- There’s a section on [configuring the shadow database](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate#configure-the-shadow-database) that isn’t really used in the how-to content (also it’s not that clear on exactly which situations need the shadow database, the instructions worked fine for me without it)
- There’s a subsection on [refining your schema with native type attributes](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate#refine-your-schema-with-native-type-attributes) that also feels oddly placed, should be integrated better or moved elsewhere as a more 'advanced' topic

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
