### ISSUE TITLE
Make baselining guide more self-contained

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3602]
Currently the [Baselining a database](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining) guide sends you off to [these instructions on updating the development environment](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#update-the-development-environment) for creating your initial SQL migration. I found this pretty confusing when trying to follow the instructions.

It would be better to have all the information on the same page, and make it clearer what is run in development and what is run on production.

Further Slack discussion: https://prisma-company.slack.com/archives/CGMCB82N8/p1660243344816489

**Comment by ruheni** [comment]
Taken care of in this PR
