### ISSUE TITLE
Explain migration histories terminology

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3603]
Currently we have [this subsection](https://www.prisma.io/docs/concepts/components/prisma-migrate#migration-history) on migration histories.

Would be good to clarify the difference between the migration files and the migration table, and use consistent terminology to refer to each of them.

Also we may want to pull this out into its own separate page as part of a general reorganisation of the information in this page.

Slack discussion here: https://prisma-company.slack.com/archives/CGMCB82N8/p1659705786802819

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
