### ISSUE TITLE
Does Vercel support the 410 HTTP code

### ISSUE THREAD

**Issue by ObamaTheLlama114** [prisma/prisma2-docs#3605]
We need to understand that if we want to delete a file, can we make it a 410?

**Comment by janpio** [comment]
There is not really any effective difference between a file being 404 (does not exist) and 410.

**Comment by ObamaTheLlama114** [comment]
I added information about the 410s to [the Notion docs](https://www.notion.so/prismaio/Writing-docs-728d18ff145b412381ffa01165401e8c)
