### ISSUE TITLE
Determine where we want images stored. 

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3614]
Research, gain consensus, and then document [in our internal docs] our decision.
--Cloudinary, Yes or No?
--A single /images dir, or images in same dir as file?
--Is the image optimization that Vercel 4 provides good enough to not have to consider the complexity of Cloudinary?

**Comment by zachtil** [comment]
Keep images as peer files to MDX files.
* `deployment/`
   * `deploy-to-netlify.mdx`
   * `deploy-to-cfw.mdx`
   * `image1.png`
   * `image2.png`
 
If the images grow to be more than the MDX files in a directory, create an `images/` folder and store all images there.

- `deployment/`
    - `images/`
        - `image1.png`
        - `image2.png`
        - …
        - `image20.png`
    - `deploy-to-netlify.mdx`
    - `deploy-to-cfw.mdx`

This is in contrast to having a centralized, top-level `images/` folder which would lead to having to create these kinds of image paths: `../../../images/pdp-screenshot1.png`.

**Comment by zachtil** [comment]
Until we find a better alternative, we'll move all images out of Cloudinary and will be storing them on GitHub.

**Comment by zachtil** [comment]
Because image file names have SEO impact (descriptive filenames are going to work better as keywords and ranking higher on those), the goal here is to also come up with a good convention for filenames.

**Comment by zachtil** [comment]
The "migration" is ready in a PR: #4236.

One minor issue remains with current Gatsby builds: 
* with Cloudinary, when you click an image, it opens the original image size
* with Gatsby, when you click an image on our Docs page, it opens a lower-resolution (and blurrier) image than what appears on the page.
   * For example: https://docs-git-migrate-from-cloudinary-prisma.vercel.app/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-the-prisma-layer-postgres#511-fix-columns-with-enum-data-types

**Comment by meletj** [comment]
- **Image hosting requirements**
    - Image optimization for responsiveness (based on different screen sizes, on bandwidth, etc.)
    - In Gatsby MDX, we can specify `@width` / `@max-width` on individual images
    - On click, it shows original image size (not lower quality image)
    - Image updates do not lead to the generation of a new filename / URL on upload of updated file
       - With Cloudinary, you cannot overwrite a previously uploaded image. When you upload the same image, it preserves the old image and uploads the new one, with a newly generated ID at the end of the file name. So you have to update the new URL in the image path in the MDX file.

Potentially, the new image hosting helps us to avoid one issue we're seeing with Gatsby, where when you update an image locally (e.g. edit a SnagIt screenshot and save to overwrite the same file), Gatsby does not refresh the image in the local build: #4412 . Every time you update an image, you have to run `npm run clean` to clean the cache (which includes the images), and re-run `npm run dev`.

**Comment by zachtil** [comment]
Image file naming guidelines and local storage locations are described in this PR: #4452

**Comment by zachtil** [comment]
Images will be stored in GitHub alongside MDX files. This is now implemented after the migration of all Cloudinary images to GitHub.
