### ISSUE TITLE
Add a doc to cover using Prisma with Cloudflare Module Workers

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3620]
We need a guide for using Prisma with [Cloudflare Module Workers](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/). 

This could be a new doc, or just a section of an existing doc - this is to be determined.

More information here: https://github.com/prisma/prisma/issues/13771#issuecomment-1204295665

SME: Alexey

**Comment by enqqi** [comment]
Yes Please

**Comment by jharrell** [comment]
Closing in favor of #4218
