### ISSUE TITLE
Create scripts repo

### ISSUE THREAD

**Issue by ObamaTheLlama114** [prisma/prisma2-docs#3627]
We need to make a new repo for our scripts.

**Comment by ObamaTheLlama114** [comment]
@janpio

**Comment by janpio** [comment]
? 

Any org user / employee can create repositories as far as I know.
But also, if the script is about the docs repo, a `/scripts` folder should do the job to be colocated with the actual content and code.

**Comment by ObamaTheLlama114** [comment]
done
