### ISSUE TITLE
Mention how to remove unneeded artifacts (`@prisma/engines`) when using AWS Lambda alone

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#3629]
In our docs (https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda) we mention how to remove unneeded artifacts but only when using the serveless framework, I think we could improve that and mention how to do that when using AWS Lambda alone.

Example: 
1. Create a zip script that only zips what's needed, for example
https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless/lambda/zip.sh
2. Then upload the zip 
```
aws lambda update-function-code --function-name my-function --zip-file "fileb://lambda.zip"
```

_Originally posted by @Jolg42 in https://github.com/prisma/prisma/issues/14485#issuecomment-1220636571_

**Comment by tanberry** [comment]
@zachtil is this one you can add to your stack of work around deployment guides, please? ;-)

**Comment by zachtil** [comment]
Good candidate, yes. Thanks, @tanberry

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
