### ISSUE TITLE
PDP: Data Proxy - connection pool limits

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3633]
Create docs for new connection pool limits parameters that can be set on the Data Proxy connection string.

Linear issue: https://linear.app/prisma-company/issue/TDA-167/connection-pool-limits

> On top of connection string param validation logic that exists:
>
> Adding default value if the user has not supplied a number the default should 60
> 
> A maximum value that number is limited to 240
> 
> _From the linked Linear issue_

**Comment by ankur-arch** [comment]
Outdated.
