### ISSUE TITLE
Consider improving wording around foreign keys

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3643]
Currently we use wording like "the `successorId` foreign key" - consider improving this to make it clearer that the foreign key is the underlying structure in the database. We represent it in Prisma with the `@relation` attribute, which we would place on the `successor` relation field in this example.

Via @do4gr (see Slack message [here](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1656405382112109)):

> I ran into this wording in the docs and it confused me. Maybe we can find a better one. I saw it in multiple spots.
> Here is an example in the context of the following datamodel:
> 
> ```
> model User {
>   id          Int     @id @default(autoincrement())
>   name        String?
>   successorId Int?    @unique
>   successor   User?   @relation("BlogOwnerHistory", fields: [successorId], references: [id])
>   predecessor User?   @relation("BlogOwnerHistory")
> }
> ````
> 
> One relation field must be backed by a foreign key. The successor field is backed by the successorId foreign key, which references a value in the id field.
> What I stumbled over was the successorId foreign key.
> My understanding: (this is not yet a proposal how to phrase this)
> The foreign key is placed on the successorId (relation) scalar field. But we represent it via the @relation attribute which we place on the successor relation field in the datamodel. The foreign key does not have an explicit name in this datamodel, but it would be User_successorId_fk  and not successorId .

**Comment by janpio** [comment]
(A lot of this inpreciseness is because of different people referring to the foreign keys as the _column_, and other meaning the a _constraint_ that is added to that column. And the in Prisma context none of this makes sense, as we have completely different concepts for this.)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
