### ISSUE TITLE
Improve docs on deploying to production

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3649]
Currently we don't have any high-level information on deploying to production, only various special-purpose guides.

[Slack conversation](https://prisma-company.slack.com/archives/C02JV0K2Q31/p1659018773088679):

> Something that came out of the user journey mapping workshop on Tuesday is that we don’t have much in the current docs on going from development to production environments. If you search ‘deploying’ there are a lot of special-purpose guides on e.g. deploying to Netlify, and also one migrations-specific guide on deploying migrations from a local environment, but no big-picture stuff on deployment to production generally (switching connection strings, deploying with a CI/CD pipeline…).

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
