### ISSUE TITLE
Switching tabs in snippets doesn't work in Safari

### ISSUE THREAD

**Issue by MEnnabah** [prisma/prisma2-docs#3669]
It seems not possible to switch tabs in snippets in docs pages in Safari.

I'm on Safari v15.4, with JS enabled and all extensions disabled. I've attached a video and a screenshot that might be helpful.

https://user-images.githubusercontent.com/16809714/186877582-efaa5a5b-1abf-44e4-ae29-b4ddb50ef50f.mov

<img width="1207" alt="Screenshot 2022-08-26 at 13 48 13" src="https://user-images.githubusercontent.com/16809714/186877651-40441905-aeb2-4c44-bdab-d8cd9cdeb123.png">

**Comment by nilubava** [comment]
This no longer happens on Safari and has been fixed.
