### ISSUE TITLE
Our search returns 0 results when looking for a keyword inside a table

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#3671]
On docs search, it seems that we do not index the content of a table. Is it expected?
Example search: “fedora” --> No results for 'fedora'

The page mentioning fedora in the table
<img width="587" alt="Screenshot 2022-08-26 at 12 22 17" src="https://user-images.githubusercontent.com/1328733/186886167-9a3e15e7-4533-4262-8008-d3cef8670088.png">
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#binarytargets-options

**Comment by tanberry** [comment]
Oh this is a good one, thank you @Jolg42 !

**Comment by janpio** [comment]
Does not seem to have worked:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/183673/189723254-703591a9-5ec2-49fe-bb28-2c6033c2527e.png">

**Comment by janpio** [comment]
Still does not work for me: 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/183673/190024959-e8c8a3b6-502e-4acf-9bba-5b573996154d.png">

**Comment by Jolg42** [comment]
Still doesn't work, not sure why it was closed @nilubava ?
https://www.prisma.io/docs/?query=fedora&page=1

**Comment by Jolg42** [comment]
It works! Thanks @nilubava 🙌🏼 
<img width="1029" alt="Screenshot 2023-01-10 at 19 59 33" src="https://user-images.githubusercontent.com/1328733/211638320-81d77c56-9f16-4b2c-aada-3d4db24eb5c6.png">


Sidenote: the table is displayed in a weird long string but maybe it's good enough for now
