### ISSUE TITLE
Document how to use the VS Code extension

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3682]
Update: I've reached out to Joel about this, with a view to covering this in the extension's Readme file. I think the answer is to do a PR on the Readme file in the Prisma Tools repo. 

In particular, the following might not be obvious to users:

- CMD + (or equivalent for other OSes) hover on a field whose type is a model or an enum will show the block in a popup.
- CMD (or equivalent for other OSes) + left click on a field whose type is a model or an enum will bring you to its definition.

See notes in Notion: https://www.notion.so/prismaio/4-3-0-6ef13a8024e24fdcbe13a83227c5c274#c4f011be8d3346a3a46481a5dc816235

I'll add these as tips boxes to the docs. **It might be good to ask our engineers for any additional tips they have for our VSCode extension** - any useful things that might not be obvious to Prisma users.

**Comment by janpio** [comment]
Further documentation on how to use VS Code extension is in README of the extension: https://marketplace.visualstudio.com/items?itemName=Prisma.prisma

**Comment by andrew-walford-prisma** [comment]
I think if we're going to provide notes like this, we should add them to the README. There's no point in putting the same user-facing content in two places. I'll investigate that route.

**Comment by andrew-walford-prisma** [comment]
Joel has updated the Readme, so I consider this material covered. I'll close this issue.
