### ISSUE TITLE
Allow using backticks for `code` in headlines instead of `<inlinecode>`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3683]
Right now when writing documentation you need to use `<inlinecode>` to format text as code, but only in headlines: https://github.com/prisma/docs/search?q=inlinecode

This requirement seems to be an artifact of the behavior of the ToC (list of headlines on the right of the page, "On this page") that can by default not render backtick enclosed text as code.

As `inlinecode` is not standard Markdown, and also not obvious, it is easy to get wrong and leads to additional changes required when contributing to the documentation. It also generally makes creating documentation harder than it could or should be.

We should investigate if it is possible to remove the requirement for `<inlinecode>` and replace it with the ability to use normal backticks to highlight code in headlines as well.

**Comment by nilubava** [comment]
Example page: https://www.prisma.io/docs/concepts/overview/prisma-in-your-stack/fullstack

**Comment by carlagn** [comment]
Replacing `<inlinecode>` tag with ` `` `  from headings works on the parsing for the overall document/page, but it does not for the generated TOC on the right-side of the document. For the toc, the backtick gets ignored, and removed altogether on the parsing.

| prisma.io | #4701 |
| ----- | ----- |
| ![Image](https://user-images.githubusercontent.com/14851246/235661433-ec2337b1-cbf4-48d7-b065-a128ea2179fc.png) | ![Image](https://user-images.githubusercontent.com/14851246/235661476-14ef2e50-69db-48ca-8e75-c684c7c0e52e.png) |

**Comment by nilubava** [comment]
@carlagn to document this in Notion and then close the issue

**Comment by carlagn** [comment]
https://www.notion.so/prismaio/Heading-inline-code-highlight-ff748b1b0aac4ea8a9808bad1415194f?pvs=4
