### ISSUE TITLE
Doc branch compilation speed

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3695]
See note below for 02 Sept 2022. This might not be an issue now.

Docs branches currently take a long time to build. This is not much of a problem in day to day work, because we can go away and work on something else and come back. However, it's quite a big problem on release day. For example, I had to resolve a merge conflict late on release day, which then triggered a rebuild. This was even before I could hit merge, which also takes time. This held @ruheni up on the release notes.

Is there any way to speed up the build?

Note:

@janpio  has tripled the number of build slots, so queueing time is reduced. See [Slack thread on this](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1661875636420889). However, the builds still take a long time.

Update 02 Sep 2022:

When I look at the build times, 8m is about the longest, and most are much quicker than that. So perhaps it was the queuing aspect (which is better since the slot increase) that made the build times seem subjectively long. This might not be an issue now.

![image](https://user-images.githubusercontent.com/105220540/188176946-5faa0ca4-adaa-4eb0-b640-ee620fe48829.png)

**Comment by nilubava** [comment]
@andrew-walford-prisma closing this since its not an issue anymore. Feel free to reopen in case you encounter this again
