### ISSUE TITLE
Docs site timeouts

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3696]
Occasionally when I visit a docs page, the page fails to load. A refresh fixes this. I don't remember seeing this before we moved to Vercel. I'll add more information to this ticket as I encounter the error.

It's happened to me twice in the last three or four days.

**Comment by janpio** [comment]
I can +1 that, reported multiple times in #docs.

**Comment by keerlu** [comment]
Another report here: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1662995224632909

**Comment by nilubava** [comment]
I cannot seem to reproduce this randomly, so I guess it should be associated with some external factors. Please ping me or the webdev channel in case you encounter this next time

**Comment by janpio** [comment]
We can not rely on that, often it is ~30 seconds in the middle of the night (see my past posts in #docs).
It happens often enough to multiple people to be a _real_ thing that we probably should invest in some monitoring.

**Comment by nilubava** [comment]
Yes, setting up monitoring is a good idea. We have also updated the packages in the repo, so we can expect better performances. Here is the issue for monitoring set up: https://github.com/prisma/docs/issues/3864
