### ISSUE TITLE
Docs build stability under Vercel

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3697]
Often when we build a branch, Vercel throws an error. When it's happened to me, Vercel has reported many broken links. However, these links were on pages I hadn't changed in the branch, neither had I changed the destination pages. A rebuild fixes the issue. @janpio has also encountered this issue.

This not only directly slows down the process of working on docs, but the rebuild impacts on other work, because our rebuild takes up server resources.

I can't link to an example, because my affected branches are now deleted, but when it happens again, I'll link to it here.

**Comment by janpio** [comment]
A good source for ideas where this happend is the [#feed-docs-vercel-failures internal Slack channel](https://prisma-company.slack.com/archives/C03RZE59A3U).

**Comment by keerlu** [comment]
[This Slack thread](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1660678574939409) has some examples of deployments with broken links
