### ISSUE TITLE
Data model: make the example and text match

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3706]
The [data model page](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model) has had various sections [like composite types](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-composite-types) added which are not reflected in the example at the top. 

Need to include everything in the example, or otherwise make it clearer that the same example is not used throughout

**Comment by keerlu** [comment]
Related thing to fix: https://github.com/prisma/docs/issues/1753

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
