### ISSUE TITLE
Clarify when to use `npx` prefix in front of Prisma commands

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3715]
Our current choice is to use e.g. `npx prisma db push` in how-to material, but just `prisma db push` in the CLI reference, because people may be calling it globally or using e.g. `yarn`. Need to decide whether to keep doing this. It's difficult:

- if we leave the prefix off, people copy the command and it doesn't work, which is bad for beginners
- if we just add `npx` (the most common choice), that's great for those users but no good for `yarn` or `pnpx`
- if we add all three as options in the command it's clearer but still doesn't copy correctly, and also people could use yet other options
- if we leave the prefix off but make a note about it somewhere, people might not see the note.

**Comment by keerlu** [comment]
Some internal Slack discussion [here](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1662049247105999)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
