### ISSUE TITLE
Explain PrismaPromise in the docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3716]
We explain `PrismaPromise` in a tutorial (and the associated concepts of await, then and thenable), but not in the main docs. As a good docs principle, information shouldn't appear uniquely in tutorials. 

IMO we should explain this in our reference materials somewhere.

We explain it in the bullet list in [this section](https://www.prisma.io/docs/concepts/components/prisma-client#3-use-prisma-client-to-send-queries-to-your-database).

**Comment by Jolg42** [comment]
I think this is a duplicate of https://github.com/prisma/docs/issues/1695 & https://github.com/prisma/docs/issues/800
