### ISSUE TITLE
Theme: enhance documentation about using Prisma middleware

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3732]
To be prioritized against other work.. is a nice-to-have at this point.

We have some docs about our middleware (query hooks), and we show three scenarios where it might be useful to implement them. These are not fully supported, prime-time features, but rather potentially helpful options.
Some areas where we could improve the docs:
-- implement option 4 in the list in Issue #2508
-- add info about using the "three slash comment" as a way to export data (See this [Grain recording]( https://grain.com/app/recordings/6f7cea1b-8e55-4423-aa95-2555de89cd4c), at about 5:20)
-- ??

We would need to decide if we are going to openly talk about the DMMF, though, if we go too far down this path.

**Comment by tanberry** [comment]
@andrewicarlson is a good SME for this topic, and @andrew-walford-prisma has already documented some middleware content.

**Comment by andrewicarlson** [comment]
We can add some documentation and context around Middleware, but given the DMMF is a private API that is subject to change without warning, we should not add any DMMF-specific guidance.

**Comment by ankur-arch** [comment]
I'm closing this issue as we suggest the usage of [Prisma Client extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions) instead of middlewares and don't want to document content regarding DMMF.
