### ISSUE TITLE
Upserts - docs need to provide guidance on usage

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3733]
There are some issues with upserts that might not be bugs per se, but require user caution. Examples:

- You should set a higher isolation level
- You should set a unique constraint

See https://www.notion.so/prismaio/Upsert-and-concurrent-operations-In-the-query-engine-44e9729ec05b453ba91930576c7c48e4

We need some guidance in the docs (if we don't already have it) on this. 

Client team will reach out to Andrew on this.

SME: Dan

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
