### ISSUE TITLE
Relational Queries

### ISSUE THREAD

**Issue by UltronOne** [prisma/prisma2-docs#3741]
I've read the documentation on relational Queries and was wondering if a Query like: "Find all songs with title x and include a boolean e.g true if the relation x exists and false if not. I couldn't find anything about that. Is there anything that would support a use case like that?

**Comment by ruheni** [comment]
Hey 👋

This might be the guide you're looking for: [Finding an entity based on the existence of a relation](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/finding-entities-based-on-relation). Let me know if this answers your question. You can use the example query as a base for adding more filters to your query. 🙂

I'll go ahead and close this for now. Feel free to reopen the issue if you'd like any further clarification
