### ISSUE TITLE
Document Prisma Logging, Prisma Call

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3752]
https://github.com/prisma/prisma/issues/11329

Gist: We log a "Prisma Client call" that is the internal representation, not necessarily what the user has in their code (as that would be impossible in pure logging).

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
