### ISSUE TITLE
Consider fixing issue with "Show CLI results" button

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3755]
If we fix this, it might involve finding all instances of the Show CLI results button and removing/replacing it in cases where it doesn't apply.

From Jan:

"The "Show CLI results" link/button on hidden output does not make sense in many cases.
Here for example it shows/hides the data that the query produces, nothing related to the CLI at all. This is just wrong https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#nested-reads"

Link to Slack thread: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1662966003038179

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
