### ISSUE TITLE
Google SEO, headings, and search results in docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3774]
Some Google searches don't find the obvious page in our docs. This seems to be due to headings. For example, if we want people to find our upsert material when they search for "prisma upsert" then we might need a page titled upsert. See Jan's example screenshots in the thread linked to below.

Of course, this has big ramifications for the docs structure, because we might want to split out key topics into their own pages to help SEO. Zach suggested we look for the most popular search topics to help use decide which topics might need their own pages to help SEO (if indeed we decide to do this).

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1662663282925219

This task initially then, is to research, and decide what we want to do, if anything. And if we do, then create tasks to identify and split out specific content. It doesn't have to be done as part of our main IA effort - it can be done later.

Docs team needs more info about how this works - hopefully we can get SEO briefing soon, and can raise this.

**Comment by janpio** [comment]
> For example, if we want people to find our upsert material when they search for "prisma upsert" then we might need a page titled upsert.

This is not correct. If we want a section link being highlighted on Google, it might be beneficial (but def not necessary) to have a section with that headline. That is _very_ different and should not lead us to prioritize creating pages for Google vs. what makes sense for our users.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
