### ISSUE TITLE
CLI Reference: add links to the full schema

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3789]
Within each section about a specific operator/parm/command in our CLI Reference docs, we provide examples of how that command can be used. However, sometimes it is useful to look at the example and then look at the full schema upon which the example is based, so that you can see a bigger context.

Jan has suggested adding links to the full schema (which is already at the very top of the page) under each parm/command/operator.

See [full thread in Slack](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1663267104720369).

**Comment by zachtil** [comment]
Off the top of my head, because the schema.prisma contents will be tied to a specific database, it might be useful to also include:

* database + version

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
