### ISSUE TITLE
Fix shortlinks (pris.ly) in Upgrade Guides

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#3796]
Our upgrade tool from P1 to P2+ has some [pris.ly](http://pris.ly/) links that seem to have gotten lost along the way:
https://pris.ly/d/upgrade-from-prisma-1
https://pris.ly/d/upgrading-the-prisma-layer
[ slack thread](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1663330010569019)

**Comment by janpio** [comment]
I think this was resolved?
