### ISSUE TITLE
Last example of "Relations in the Prisma Client" is wrong.

### ISSUE THREAD

**Issue by prufrock123** [prisma/prisma2-docs#3797]
The last example of Relations in the Prisma Client section (https://www.prisma.io/docs/concepts/components/prisma-schema/relations#relations-in-the-prisma-client) says the following:
```
const updateAuthor = await prisma.user.update({
  where: {
    id: 20,
  },
  data: {
    posts: {
      connect: {
        id: 4,
      },
    },
  },
})
```

> Sets the authorId to 4 on the Post record where the id is 20

This is the opposite of what it's doing. It's actually taking a post with ID of 4 and updating its authorId field to "20" (the User with id of 20).

Elsewhere in the documentation (https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#connect-or-create-a-record), this almost exactly same query is formulated correctly:

> You can connect  an existing record to a new or existing user. The following query:
1 - Connects an existing post (id: 11) to an existing user (id: 9)
2 - Adds a new related post (title: "My new post title")

```
const getUser = await prisma.user.update({
  where: {
    id: 9
  },
  data: {
    posts: {
|      connect: {
|        id: 11
|      },
      create: {
        title: "My new post title"
      }
    }
  }
})
```

**Comment by prufrock123** [comment]
re-upping

**Comment by ruheni** [comment]
Hey 👋

Thanks for pushing for this change in the docs. This should be resolved. I'll go ahead and close the issue, but feel free to reopen it if there are any adjustments you'd like us to make 🙂

<img width="483" alt="CleanShot 2023-05-04 at 00 29 44@2x" src="https://user-images.githubusercontent.com/33921841/236064569-6851450b-a09e-4ad8-8f30-6fb1145e49e5.png">
