### ISSUE TITLE
Improve discoverability of `Prisma.DbNull`/`Prisma.JsonNull`

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma2-docs#3800]
We should make the [documentation about `Prisma.DbNull` and `Prisma.JsonNull`](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values) more discoverable.

The title of the section refers to "Filtering by null values", but the same also applies to create, insert and upsert operations (only `Prisma.AnyNull` is only used for filtering). This is, in fact, stated in the referenced section of the documentation, however it is hard to find.

This leads to confusion by our users who report expected and intended behavior as a bug: https://github.com/prisma/prisma/issues/9247

**Comment by tanberry** [comment]
Thanks @aqrln, yes we definitely need to improve this; I even had trouble finding it. @ObamaTheLlama114 (William on Docs team) and I might ping you with some questions soon.

**Comment by ObamaTheLlama114** [comment]
Background slack thread [here](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1665755417115009)
