### ISSUE TITLE
Document batching logic better

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3802]
https://www.prisma.io/docs/guides/performance-and-optimization/query-optimization-performance#solving-the-n1-problem is currently our only "documentation" of the batching optimization that Prisma Client and Engine are doing to some queries. In reality it is more a use case where that batching is very useful though.

We should have a page or section "Batching in Prisma Client" that explain how Prisma Client is automatically doing something to improve the performance.

Internal discussion: https://prisma-company.slack.com/archives/C016KUHB1R6/p1662657490157129

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
