### ISSUE TITLE
Follow-ups from Migrate reorganisation

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3805]
Separate to the reorg there are a few leftover comments on the existing text from @tanberry that I want to investigate before editing.

![image](https://user-images.githubusercontent.com/3910386/191212913-7253a958-d35f-4f5f-b169-d9de47393298.png)
![image](https://user-images.githubusercontent.com/3910386/191212985-08b7c3e1-9081-406f-87df-9786dc99a79f.png)
![image](https://user-images.githubusercontent.com/3910386/191213771-56e05d83-3006-4ba0-bc91-5da926305bd4.png)
![image](https://user-images.githubusercontent.com/3910386/191213290-7b23dfe3-86f3-4e72-88b5-6e79ee45f585.png)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
