### ISSUE TITLE
Update doc about "push" in "Scalar list method" 

### ISSUE THREAD

**Issue by tamhac2001** [prisma/prisma2-docs#3806]
The doc said: "You cannot push a list of values - only a single value." but I think you can already push a list of values already
The reference in my project:
![image](https://user-images.githubusercontent.com/58587966/191289486-81637a62-1e3d-47c7-a759-fe325835f630.png)
Compare to the reference in the doc:
https://github.com/prisma/docs/blob/main/content/400-reference/200-api-reference/050-prisma-client-reference.mdx#reference-26

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
