### ISSUE TITLE
Consider improving our descriptions of filter conditions.

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3813]
@janpio reports that our docs are confused/confusing on some of the filter conditions. They don't clearly differentiate `not` and `NOT`, and so on.

The filter conditions material might need to be substantially reorganized, and we might need to write some definitions of some filter conditions that the docs currently don't define. There are also some specific minor issues he's highlighted, such as links going to the wrong place. See the Slack thread for details.

Slack thread: 

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1663861444496519

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
