### ISSUE TITLE
Investigate whether we list the supported index sort orders in the docs. If not, add it; if so, improve its findability

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3814]
Anywhere in the docs, do we list the values for the sort order of database indexes, that can be defined in PSL?

If not, we should add a list. If we do, IMO we should link to it from [this section](https://www.prisma.io/docs/concepts/components/prisma-schema/indexes#configuring-the-index-sort-order-with-sort)

Slack discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1663869060205839

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
