### ISSUE TITLE
On custom model and field names page, consider adding line highlighting in the code examples

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3815]
IMO, the examples on https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/use-custom-model-and-field-names would be a bit easier to follow if we highlighted the relevant lines. For example, in the section https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/use-custom-model-and-field-names, the changed lines in the second code block could be highlighted.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
