### ISSUE TITLE
Incorrect description of push method in Prisma Client Reference

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#3824]
The [push](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#push) method describes that only a single value can be pushed at a time. But it seems that we can push multiple values in the latest Prisma version.

In Prisma version `4.3.0` with PostgreSQL database pushing multiple values is possible. We can update the description to reflect the same.

Example Schema:
```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model test {
  id    Int      @id @default(autoincrement())
  array String[]
}
```

Snippet:
```typescript
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn'],
});

async function main() {
  await prisma.test.create({
    data: {
      array: ['1'],
    },
  });

  await prisma.test.update({
    where: {
      id: 1,
    },
    data: {
      array: {
        push: ['2', '3'],
      },
    },
  });
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

**Comment by nikolasburk** [comment]
Seems like this has been fixed by now: 

<img width="545" alt="image" src="https://github.com/user-attachments/assets/5b0b2e3b-4288-42e8-8fa1-f9c4ce692f91">
