### ISSUE TITLE
Document new error code P2034

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#3825]
https://github.com/prisma/prisma-engines/commit/911f8bae8f9b08719066939ba0aaff82c1fe4a50

Update by Andrew, 12-oct-2022:
- Jan has added the error code itself in a separate PR (this is merged)
- We need to document the actual usage in the context of isolation level docs/transactions. See comment here: https://github.com/prisma/prisma/issues/9678#issuecomment-1259873693

**Comment by janpio** [comment]
First simple PR that document just the error code and message: https://github.com/prisma/docs/pull/3827

Left is actual usage in context of isolation level docs of transaction etc.

**Comment by andrew-walford-prisma** [comment]
See Jan's writeup here: 

https://github.com/prisma/prisma/issues/9678#issuecomment-1259873693
