### ISSUE TITLE
Redo `referentialIntegrity`/`relationMode` docs

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#3832]
We will open a draft PR of the rework

We have a todo list here https://www.notion.so/prismaio/How-do-we-GA-the-referentialIntegrity-preview-feature-8a656fe445ae4a69ad19c5000e5c7191#42c77d7fcfc042fc8291093937683153

**Comment by janpio** [comment]
Discussion and PR: https://prisma-company.slack.com/archives/C02EQD1EWAF/p1666038102472539

**Comment by Jolg42** [comment]
Notion with all what needs to be documented about the feature (to be reviewed)
https://www.notion.so/prismaio/Relation-Mode-What-needs-to-be-documented-3ff385e25c7d4ba2bd3a1032e6547c43
