### ISSUE TITLE
Docs about disambiguating relations should clarify that the name of the relation needs to be unique

### ISSUE THREAD

**Issue by piedrahitapablo** [prisma/prisma2-docs#3840]
Hi, first of all, thanks for building Prisma, it's really amazing and a joy to work with. 

I just had an issue disambiguating relations because I named multiple relations (on different models) with the same name, like this:

```
model User {
  ...

  createdNodes       Node[]       @relation("createdBy")
  updatedNodes       Node[]       @relation("updatedBy")
  createdWorkspaces  Workspace[]  @relation("createdBy")
  updatedWorkspaces  Workspace[]  @relation("updatedBy")
}

model Node {
  ...

  createdById String    @db.Uuid
  updatedById String    @db.Uuid
  createdBy User @relation("createdBy", fields: [createdById], references: [id], onDelete: Cascade)
  updatedBy User @relation("updatedBy", fields: [updatedById], references: [id], onDelete: Cascade)
}

model Workspace {
  ...

  createdById String    @db.Uuid
  updatedById String    @db.Uuid
  createdBy User @relation("createdBy", fields: [createdById], references: [id], onDelete: Cascade)
  updatedBy User @relation("updatedBy", fields: [updatedById], references: [id], onDelete: Cascade)
}
```

this caused a bunch of weird typing issues, like requiring both `createdById` and `createdBy` when using a nested `create`. After looking at the docs example for a while and seeing that the generated types were referring to another model I realized that maybe the relation names should be unique, but I think that having a clarification in the docs will help other people to get there faster.

Thanks!

**Comment by piedrahitapablo** [comment]
Also, I'm not sure if things like this should be validated when generating the types to prevent that from happening at all.

**Comment by janpio** [comment]
Absolutely. Either that (not validate), or it should not be a problem in the first place (so the problems you are seeing could be a bug). Can you open an issue in `prisma/prisma` about this and link to it here? Thanks.

**Comment by piedrahitapablo** [comment]
Hey @janpio, I was going to do that but I wanted to get a small repo to reproduce it, and turns out it was a bug in version 4.0.0, I was not able to reproduce it using 4.4.0, so I think we can close this one, what do you think?

**Comment by janpio** [comment]
Absolutely! Thanks for updating us.
