### ISSUE TITLE
Document denylist of model names

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#3844]
A bunch of model names are not allowed in the Prisma schema because they cause trouble with duplicated type names of our generated types. The denylist should be documented in the docs.

More info in this issue: https://github.com/prisma/prisma/issues/12469

**Comment by janpio** [comment]
Note, most of these _should_ not be blocked, which is why we are tracking this as a bug. If we document this, we need to make sure to point that this is a temporary limitation and link to the issue.
