### ISSUE TITLE
JSON null filtering examples is incorrect

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma2-docs#3845]
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values

Context: https://github.com/prisma/prisma/discussions/14675

```ts
prisma.log.create({
  data: {
    meta: Prisma.JsonNull,
  },
})
```
should be
```ts
prisma.log.create({
  data: {
    meta: { equals:  Prisma.JsonNull },
  },
})
```

It is same for other occurances

**Comment by ruheni** [comment]
The example has been fixed and should be functional.
