### ISSUE TITLE
Interactive transactions (client changes)

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3849]
This feature will go into preview in the near future and then GA after that.  

iTX will work in conjunction with the Data Proxy. @zachtil  is going to handle the documentation on this. 

SME: Dan, Alexey

See: https://www.notion.so/prismaio/Interactive-Transactions-supported-in-Data-Proxy-cba564a8e37348078f0242b555a95fe0

Board for engineering work: https://github.com/orgs/prisma/projects/84

**Comment by heymartinadams** [comment]
That’s awesome, @andrew-walford-prisma! I was just thinking how I’d like to combine Prisma Data Proxy with interactive transactions, then was sad to find out that that wasn’t (yet) possible.

Starting at what version can we use iTX in combination with PDP?

**Comment by andrew-walford-prisma** [comment]
Hi @heymartinadams . Sorry - I was a bit too definitive when I gave version numbers in the issue description. We do plan to release this feature in preview, and then GA in the near future, but it is likely to be later than 4.6/4.7.

**Comment by zachtil** [comment]
We've released iTX with Data Proxy in Preview in [4.6.0](https://github.com/prisma/prisma/releases/tag/4.6.0).
