### ISSUE TITLE
Scope of Improvement in describing default value of DateTime type?

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#3861]
A user reported on a GitHub Discussion: [#15686](https://github.com/prisma/prisma/discussions/15686)

> We started off using the default DateTime type suggested by Prisma, without giving it a second thought. This translates to TIMESTAMP(3) for PostgreSQL.They all get converted to UTC timezone and do not specify the timezone themselves anymore. If we try to create Dates in our FE from them these dates will automatically be assumed to be in the local timezone, and not UTC. To specify them as UTC we either need to manually change the string to append a Z, making them valid ISO strings, or to shift the time zone manually. Obviously we'd like to avoid that.
> 
> We ended up changing all the types in our db to DateTime @db.Timestamptz(3).
> 
> Maybe this is fine but we just got a little surprised to having such issues using the default DateTime. I'd expect to be able to do basic things, like simply creating dates from string, without having to first make sure I picked the right type of DateTime and not just the default. I figured I'd open a discussion here in case there is something we got wrong or this is of interest to the Prisma team. 

Opening this Issue just in case we think we can add this in the docs.

**Comment by nikolasburk** [comment]
Closing this as not planned in an effort to clean up the docs issues 🙏
