### ISSUE TITLE
Improve documentation about optional/required relations

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#3875]
Improve the documentation for optional/required relations [here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-one-relations#required-and-optional-1-1-relation-fields) and [here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations#required-and-optional-relation-fields-in-one-to-many-relations):

- Currently we use required/mandatory/non-optional interchangeably and should pick one
- Figure out how to describe relations - the relation itself vs. its parts (relation field and relation scalar)

Details from @janpio below, also see [Slack thread](https://prisma-company.slack.com/archives/C01TM7UM83Y/p1665385201163339):

> While talking to [@jkomyno](https://prisma-company.slack.com/team/U039N8RJLHW) last week I realized something:
> Our documentation around "optional" and "mandatory/non-optional/required" relation (fields) is a bit confusing:
> https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-one-relations#required-and-optional-1-1-relation-fields

> > Required and optional 1-1 relation fields
> In a one-to-one relation, the side of the relation without a relation scalar (the field representing the foreign key in the database) must be optional:
> ...
> However, you can choose if the side of the relation with a relation scalar should be optional or mandatory.
> [https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations#required-and-optional-rela[…]s-in-one-to-many-relations](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations#required-and-optional-relation-fields-in-one-to-many-relations)
> Required and optional relation fields in one-to-many relations
> The list side of a 1-n relation is always mandatory. On the other side of the relation, the annotated relation field and relation scalar can either both be optional, or both be mandatory.

> Note the bold terms: Required, optional and mandatory.
> Note the italic terms: Relation field(s), relation scalar.
> So our documentation is about the field in the relation and its properties.
> That shows 2 challenges for me:
> Day to day we actually talk more about "optional relation" and "non-optional/required/mandatory relation" - instead about the "relation field". That is quite a disconnect.
> The terminology around option/non-optional/mandatory/required seems interchangeable.
> (When researching this I also realized that we are ordering the optional and mandatory relations different for 1:1 and 1:n in our docs https://github.com/prisma/docs/pull/3858/files)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
