### ISSUE TITLE
Consider improving the self relations docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3877]
From the user feedback in this call log:
https://prisma.productboard.com/insights/notes/all-notes/notes/27266684

"Docs for self relations
* Need to use two fields for relation but why and how does it work? Would be great to improve this. Is this mandatory? Why is the relation exactly the same?
* Misguiding in docs: why would you want to pick explicit over implicit many-to-many"

**Comment by janpio** [comment]
(second bullet is not about self relation)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
