### ISSUE TITLE
Transactions docs: investigate why we only cover some database types at the end

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3878]
In https://www.prisma.io/docs/concepts/components/prisma-client/transactions#supported-isolation-levels, at the very end, we only link out to PostgreSQL, MS SQL Server, and MySQL. Why not the other database types?

Find out why, and consider adding links to information for the other database types.

**Comment by janpio** [comment]
I aksed the same before in the PR, ~~I think it was before we use the default for some or something like that~~ it was because other two only support 1 and you can not configure anything.

**Comment by andrew-walford-prisma** [comment]
> I aksed the same before in the PR, ~I think it was before we use the default for some or something like that~ it was because other two only support 1 and you can not configure anything.

Yep, I saw that this morning. I've done a tidy up on the page, to remove the content duplication, but otherwise it's good.
