### ISSUE TITLE
Mine Garren's OCC doc for material to improve our OCC docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3880]
In this doc, Garren explains in detail how OCC works. https://www.notion.so/prismaio/How-OCC-works-7e54faef816b4ed19f00f6dd1d98b5b5

We might want to bring some of this material into our docs.

This might overlap with https://github.com/prisma/docs/issues/3881

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
