### ISSUE TITLE
Add docs on unique constraints

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3881]
See Jan's comment here: https://github.com/prisma/prisma/issues/9678#issuecomment-1259873693

Also see comment here: https://prisma-company.slack.com/archives/C040E1UMBD5/p1664302380890449?thread_ts=1664230183.328229&cid=C040E1UMBD5

This might overlap with https://github.com/orgs/prisma/projects/31?fullscreen=true

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
