### ISSUE TITLE
Second-level parent in sidebar menu has no indication that it contains children pages

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3943]
Just noticed that if you have a second-level parent, there’s no immediate indication that that has nested children pages, in other words, the expand/collapse control is not available. You need to click the parent entry to figure out there are nested children pages under it:

This occurs here:
PR: https://github.com/prisma/docs/pull/3934
Vercel preview: https://docs-git-cp-2701-create-manage-projects-prisma.vercel.app/data-platform/projects

We have this functionality across other places in Prisma ORM docs.

Tests:
* Tried adding <Subsection /> to the `index.mdx` page. Expectedly, this only added the links for the children pages to the parent page.

**Comment by janpio** [comment]
Slack conversation: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1666689127288729

**Comment by zachtil** [comment]
Research: https://www.notion.so/prismaio/Docs-issue-Second-level-parents-lack-Expand-Collapse-button-e73abc972d614a3cae606d073260812d#dfdb1986673f4d9f9fd9dc728a233147

**Comment by nilubava** [comment]
#4386
