### ISSUE TITLE
Update Upsert docs

### ISSUE THREAD

**Issue by garrensmith** [prisma/prisma2-docs#3952]
We need to add more information to our upserts page https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#upsert

The first section would add information about handling Unique Key Constraint errors. This can be added at any time. 
A rough section to add would be something like this:

If there are many concurrent Prisma upserts, this can lead to an upsert operation throwing a unique key constraint error. 
A Prisma Upsert works by first performing a read operation using the `where` clause in the Upsert operation to see if that Row or document exists in the database. If it does not then it will create that row. If it does exist it will update it. When two or more upsert operations are performed at the same time, there could be a race condition where both operations do not see the row and try and create the row. One of the operations will succeed and create the new row and the other operation will fail and return a `Unique Key Constraint` error. In most cases, the application code can receive this error and then try the upsert operation again and it should update the row.

**Comment by garrensmith** [comment]
We will also be adding support for Native Upsert support for `Postgres`, `sqlite` and CockroachDB` https://github.com/prisma/prisma-engines/pull/3257 in the next release. This is via the `ON CONFLICT .. UPDATE` sql command https://www.prisma.io/dataguide/postgresql/inserting-and-modifying-data/insert-on-conflict

We need to add documentation around this. Something like:
For specific upserts, Prisma will optimise the query to use the sql command `INSERT .. ON CONFLICT (constraint) Update`. This will work in the following conditions:

1. The data connector supports it - Sqlite, Postgres and CockroachDB

1. The create and update arguments do not have any nested queries. It only works when the upsert is updating one Model/table
1. There is only 1 unique field in the where clause. If a Model has many unique fields defined for it, it will only work if the where clause contains only 1 of those unique fields. For example with a schema of:
  
```
      model TestModel {
              id Int @id
              num1 Int
              field String @unique
              email String

              @@unique([id, num2])
          }
```
   
   If the upsert query is like this:

 ``` js
     prisma.testModel.upsert({
       where: {
         field: "a-unique-value
       }, 
       create: {
        id: 1,
        num1: 1,
        field: "a-unique-value",
        email: "test@example.com"
        },
       update: {
          email: "updated@example.com"
        }

      });
```

Prisma will use the native upsert. But if we have a query with multiple unique in the where clause:

```js
prisma.testModel.upsert({
       where: {
         field: "a-unique-value,
         num: 1,
         id: 1
       }, 
       create: {
        id: 1,
        num1: 1,
        field: "a-unique-value",
        email: "test@example.com"
        },
       update: {
          email: "updated@example.com"
        }

      });
```

This it will use Prisma's upsert instead of the database's upsert functionality. 

1.  The unique field defined in where clause has the same value as defined in the create arguments
 
For the same schema as above, if the unique field defined in the where clause has a different value to the same unique defined in the create clause then it will not use the database's upsert functionality. For example this query:

```js
     prisma.testModel.upsert({
       where: {
         field: "a-unique-value
       }, 
       create: {
        id: 1,
        num1: 1,
        field: "a-unique-value",
        email: "test@example.com"
        },
       update: {
          email: "updated@example.com"
        }

      });
```
Will work because the `field` in the `where` clause is `"a-unique-value"` and the `field` in the `create` is also `"a-unique-value"`. But this query would use Prisma's upsert instead of the database:

```js
prisma.testModel.upsert({
       where: {
         field: "a-unique-value
       }, 
       create: {
        id: 1,
        num1: 1,
        field: "a-different-value",
        email: "test@example.com"
        },
       update: {
          email: "updated@example.com"
        }

      });
```
because the `field` in the `where` clause is `"a-unique-value"` and the `field` in the `create` is `"a-different-value"`

**Comment by andrew-walford-prisma** [comment]
Thanks Garren - I'll work on this next week.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
