### ISSUE TITLE
Improve the queryRaw docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3954]
When a user writes some invalid SQL and passes it with queryRawUnsafe, it isn't clear to the user whether it's their own error or a bug in Prisma. In our docs, we cover considerations for raw queries:
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#considerations

However, the docs maybe aren't as clear as they could be in this situation.

Serhii recently looked into this. [Here's his writeup](https://www.notion.so/prismaio/Syntax-error-reporting-for-raw-queries-269e10fa757144bb8ade00f0427f7442).

### Things we could improve
Serhii recommends that the doc would be better if we did the following:
- Explain that the [considerations](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#considerations) also apply to the `Prisma.sql` helper
- Add more examples of `Prisma.sql` usage, to make it clearer why `Prisma.sql` is needed. Serhii suggests mining the [SQL template tag](https://www.npmjs.com/package/sql-template-tag) docs for examples, such as nested queries and dynamic AND.

### Possibly clarify the difference between `queryRaw` and `queryRawUnsafe`

Soph thinks the doc could be clearer in differentiating `queryRaw` and `queryRawUnsafe`. 

Here's Serhii's explanation:

"Regarding queryRaw and queryRawUnsafe difference: unsafe variant just accepts a string as an input, no matter how it is formed, safe handles templating itself."

queryRawUnsafe:

```
const id = "1"
// this is just a regular template string, JS handles all substitutions, at the end we have a valid sql string 
const query = `SELECT * FROM table WHERE id="{id}"`
// produces SELECT * FROM table WHERE id="123"

prisma.$quaryRawUnsafe(query)
```

queryRaw:

```
const id = 123
// In this case, Prisma.sql decides how to do the substitutions, and it forms prepared statement instead of a plain string, which in this case ends up being invalid
const query = Prisma.sql`SELECT * FROM table WHERE id="{id}"`
// produces { sql: 'SELECT * FROM table WHERE id="$1", values: [123] } object, which is not what we wanted: it will always query for  the record with id="$1" instead of "123"

prisma.$queryRaw(query)
```

### Resources
See:
- Slack discussion: Slack discussion: https://prisma-company.slack.com/archives/C02FZENHD4N/p1666723091468889
- Original user issue: https://github.com/prisma/prisma/issues/15472 
- Serhii's writeup of the problems with user errors and raw queries: https://www.notion.so/prismaio/Syntax-error-reporting-for-raw-queries-269e10fa757144bb8ade00f0427f7442
- SQL template tag docs: https://www.npmjs.com/package/sql-template-tag

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
