### ISSUE TITLE
`tagged-template-helpers` anchor doesn't update side location indicator

### ISSUE THREAD

**Issue by Druue** [prisma/prisma2-docs#3955]
The link to [`Prisma.sql`](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers) does not provide a location indicator to the side. This is on the [raw database access](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access) page but happens regardless of already being on the page or not.

This is on Firefox v106.0.1 (64-bit) MacOS

https://user-images.githubusercontent.com/29753584/198074005-28443b90-1b1b-45e1-bb72-9dd668d56063.mov

**Comment by nilubava** [comment]
@carlagn Maybe related to https://github.com/prisma/docs/issues/4627 ?

**Comment by carlagn** [comment]
@nilubava not _quite_ related. Basically the `prisma.sql` link brings you to a section inside `Unsupported types`, but the tocDepth defined for this page doesn't include the section it links to, only its parent (Unsupported types), so it doesn't get highlighted. I'll look into it. An easy fix would be to expand `tocDepth` here for example.
