### ISSUE TITLE
Schema at the Quickstart page not working

### ISSUE THREAD

**Issue by neznayer** [prisma/prisma2-docs#3962]
## Describe bug

When following instructions on the "quickstart" page, the migration step 
`npx prisma migrate dev --name init`
gives the error:
`Error: Couldn't find a datasource in the schema.prisma file`

## How to reproduce
Just follow instructions on the `Quickstart` page.

## How to fix that

Add the `datasource` to the top of the `schema.prisma` content, so it would become

```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

**Comment by janpio** [comment]
Isn't the page supposed to show what to _add_ to the file, and after `prisma init` it should already have a `datasource` and `generator` block?

**Comment by neznayer** [comment]
@janpio Yes, it supposed to do so and I'm a stupid, because I missed the `prisma init`  step. Issue closed 😅

**Comment by janpio** [comment]
Well, no one is ever stupid if it is easy enough to miss something like that.

Maybe we need to make this clearer a bit, that this is a diff to the file or that the other command is really important. @nikolasburk might have an idea.
