### ISSUE TITLE
Search  for "Unique key constraint errors on upserts" does not return any result

### ISSUE THREAD

**Issue by meletj** [prisma/prisma2-docs#3979]
Inconsistent search results, when trying to search for this page https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#unique-key-constraint-errors-on-upserts

Search: 
“Unique key constraint errors on” - takes you to the right section (https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#unique-key-constraint-errors-on-upserts), as expected
“upserts” - results about upserts returned, as expected
“Unique key constraint errors on upserts” - no results returned!

**Comment by janpio** [comment]
> “Unique key constraint errors on” - takes you to the right section ([prisma.io/docs/reference/api-reference/prisma-client-reference#unique-key-constraint-errors-on-upserts](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#unique-key-constraint-errors-on-upserts)), as expected

Note how this actually only returns content of the paragraph, not the headline itself. So the "Unique key constraint errors on" is not actually the one from the headline, but because there are similar words used in the text.

Weird.

**Comment by janpio** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/183673/212104680-ba7e02e6-0c50-4e5f-a513-0fee122bf12b.png">
Pretty weird that we have this text there even @andrew-walford-prisma
