### ISSUE TITLE
Document the problem and workaround for VSCode not recognizing changing types after generate

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3981]
Slack discussion: https://prisma-company.slack.com/archives/CKCQQGXJM/p1667383986796029

We should mention it:
- In the docs
- In the README

We do mention it in the docs, but in the context of preview features:
"If you are using Visual Studio Code and the Preview feature is not available in your .ts file after generating the client, run the TypeScript: Restart TS server command."

We probably need to find a better place for this - maybe a short troubleshooting article, linked to from elsewhere as appropriate.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
