### ISSUE TITLE
The Prisma Client API reference is overloaded with content - consider splitting it into separate pages

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#3999]
The Prisma Client API reference page is overloaded. We should probably split it into separate pages - and we need to decide how urgent this is.

## Problems

- The heading levels are excessive - if we are getting to level 5, that's a sign that there's too much content in the page.
- This page is so big that it's slowing down the docs build. We probably need to divide it out into multiple pages. See Slack thread: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1668535632567839
- We are also getting build log warnings about the rendered page being over 500K. We should keep pages below this size. This page as rendered HTML is apparently greater than 2MB.
- This particular page is taking 40 seconds every build just at one stage of the build process. Along the way, it's causing two timeouts that each trip at 15s. See the Slack thread for screenshots from Nilu.

## Prognosis

IMO we should judiciously split out some of the material - e.g. the stuff at the very bottom which is supplementary - into separate pages. Also review anything that is heading level 5 or below.

But we also should also break the page up to lighten the server load. This is probably an easier task, because it doesn't require as much refactoring. We can split out each major section into a sub-page. 

Note - we already plan to spin out the material about "database upserts" - into a "Prisma under the hood" page. A docs issue for this is to be created.

Another problem is that there are many duplicate headings, because they relate to keywords in different operation types. For example, `isnot` has two headings, under relation filters and composite types respectively. But when you go to one of these, it's not clear which section it's in because the page is so long. If the in-page TOC scrolled, this would mitigate the problem, but I personally don't like the lack of in-page signposting. Breaking the page up would help with this.

## Considerations

If we split the page, how will this impact any existing PRs on the current page?

### Discussion outcome

Zach’s proposal: landing page with table (we will need to decide how granular to make any splits that we do)

Andrew to investigate next sprint

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
