### ISSUE TITLE
any way to run on windows? docker maybe?

### ISSUE THREAD

**Issue by gotexis** [prisma/prisma2-docs#4]
I would really like to use this stuff!

Please, do you have any official recommendation for me to test on windows?

**Comment by onpaws** [comment]
NB: I haven't tried this personally.
If I were you, I'd consider investigating [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). 
Probably Ubuntu will have what this needs. Just a hunch. 
You may be able to get away WSL v1, but if you're willing to be a bit on the edge, v2 came out pretty recently and is expected to be better. I think for v2 you may have to opt into the Windows 10 Insider program, the so-called 'Fast Ring'

**Comment by matthewmueller** [comment]
Hey thanks for bringing this up! We'll be working to make Prisma work on windows for 1.0 release. We'll be tracking this issue here: https://github.com/prisma/prisma2-docs/issues/4
