### ISSUE TITLE
Document "Prisma Query Engine under the hood"

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4001]
Jan suggests it would be good to have a new page called something like "Prisma Query Engine under the hood". It would explain some of the implementation details that we currently don't cover in the docs.

This page would be to help advanced users understand what happens behind the scenes, so they can write better performing queries, for example.

One section we already have that could go into this page is "Prisma upserts versus native database upserts". The material from the corresponding section in the Client API reference could be moved there.

We could also have a section about "How Prisma does SQL queries". JOINs and nested queries and pagination could be some topics here.

See discussion in this thread: https://prisma-company.slack.com/archives/C03V1UE750D/p1666795190504629

Where we move details into this page from a docs page, we should link from that page to the new page/heading.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
