### ISSUE TITLE
Docs state (incorrectly) that adding a full-text index in Postgres will improve performance

### ISSUE THREAD

**Issue by dickfickling** [prisma/prisma2-docs#4002]
Title says it all, really. The docs currently state that adding a full-text search index in Postgres will improve performance, but those indexes aren't actually used, so any effort creating them is wasted right now. Probably we should just remove that section from the docs, or add a big bold caveat that following those instructions won't actually do anything to speed up your queries?

I'm happy to push a PR updating the docs, just want some guidance on which change to make (e.g remove the section altogether or add a caveat warning)

Docs link: https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#postgresql-1
Github issue showing that indexes are not being used: https://github.com/prisma/prisma/issues/8950#issue-980473627
Slack conversation about this: https://prisma.slack.com/archives/CA491RJH0/p1666896107795639

**Comment by dickfickling** [comment]
cc @floelhoeffel as I know you're working on this functionality

**Comment by janpio** [comment]
Removing this section is a valid next steps for now.
