### ISSUE TITLE
Fix <inlinecode> in <Admonition> to use default font size 14px and not 16px as it appears larger than regular text

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4019]
# Overview

There is a discrepancy in the styling of inline code snippets with backticks `` and <inlinecode> when added to `<Admonition>`, the latter has larger font size than regular body text.

Slack convo: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1667910235702469

## MDX code overview

<img width="719" alt="2022-11-08_14-33-46" src="https://user-images.githubusercontent.com/103522279/200565504-5d071083-b6c9-43eb-a81b-7b9d15f79880.png">

## **Code snippet with backticks in body text has font size 14px:**

<img width="1461" alt="2022-11-08_14-28-50" src="https://user-images.githubusercontent.com/103522279/200565462-926f6ee9-be29-45a0-8ce1-aab64f285212.png">

## **Code snippet with `<inlinecode>`in `<Admonition>` has font size 16px:**
<img width="1461" alt="2022-11-08_14-29-18" src="https://user-images.githubusercontent.com/103522279/200565496-81fd49c1-06bd-4752-aa08-7b2b5e977424.png">

**Comment by nilubava** [comment]
This has already been fixed with some other latest changes.
