### ISSUE TITLE
Investigate adding links to Help articles in Prisma Docs

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4025]
The Support team are drafting Help articles which Prisma Docs team can look at and investigate how to link to these from Prisma Docs.

* How to view parameters in query logs?
* How to turn an implicit many-to-many relation into an explicit many-to-many relation?
* How to connect to PostgreSQL in Google Cloud using Prisma?
* How to generate initial migrations for baselining without resetting the database?

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
