### ISSUE TITLE
Document `SetNull` validation introduced in `prisma@4.6.0`

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma2-docs#4035]
In the "Referential Actions" page, we should mention that, starting from `prisma@4.6.0`, defining a Prisma schema with a `SetNull` referential action referencing a non-nullable field is no longer valid.

Consider the following Prisma models:

```prisma
model SomeUser {
  id      Int      @id
  profile Profile?
}

model Profile {
  id     Int      @id
  user   SomeUser @relation(fields: [userId], references: [id], onUpdate: SetNull, onDelete: SetNull)
  userId Int      @unique
}
```

The `@relation` in `Profile` is not valid anymore, as the referenced field (`user_id`) has a non-nullable type (`Int`).

We have decided to add this new Prisma validation as, with the scenario above, all databases would fail with a validation error at the database level (which would result in a Prisma migration error). The only exception is Postgres, which accepts `SET NULL` referential actions, but would fail at runtime once such action is triggered by a change in a referenced row.

The new validation error message is:

> Error parsing attribute "@relation": The `onUpdate` referential action of a relation must not be set to `SetNull` when a referenced field is required.
> Either choose another referential action, or make the referenced fields optional. 

Here's an example of a valid Prisma schema using `SetNull` appropriately:

```prisma
model SomeUser {
  id      Int      @id
  profile Profile?
}

model Profile {
  id     Int       @id
  user   SomeUser? @relation(fields: [userId], references: [id], onUpdate: SetNull, onDelete: SetNull)
  userId Int?      @unique
}
```

Please check out the [internal notion](https://www.notion.so/prismaio/Validation-of-SET-NULL-referencing-non-optional-fields-71325e2c6d764e38aec94f16bf2db66f) for additional context.

**Comment by ankur-arch** [comment]
Hi @jkomyno,

I believe this is already addressed in the [documentation here](https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/referential-actions#setnull). Hence, I'm closing this issue.

Thank you!
