### ISSUE TITLE
SEO: fix the `metaTitles` in the docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4044]
`metaTitles` are important for Google SEO. We have some issues with the `metaTitles` in our docs:

- We have four pages with a blank `metaTitle`: we should add one, even if it's the same as the `title`. 
- Some pages have no `metaTitle` - e.g. some style guide pages. 

Update: I used the following command to search for files:

`grep --include="*.mdx" -L -r  "metaTitle"`

This returned the following list (it's pretty short - this will be an easy fix):

- ./400-reference/100-system-requirements.mdx
- ./200-concepts/100-components/02-prisma-client/000-working-with-prismaclient/115-connection-pool.mdx
- ./200-concepts/100-components/250-preview-features/050-client-preview-features.mdx
- ./200-concepts/100-components/250-preview-features/080-cli-preview-features.mdx
- ./200-concepts/100-components/01-prisma-schema/06-relations/300-many-to-many-relations.mdx
- ./200-concepts/100-components/01-prisma-schema/06-relations/100-one-to-one-relations.mdx
- ./200-concepts/100-components/01-prisma-schema/06-relations/400-self-relations.mdx
- ./200-concepts/100-components/01-prisma-schema/06-relations/500-troubleshooting-relations.mdx
- ./200-concepts/100-components/01-prisma-schema/06-relations/200-one-to-many-relations.mdx
- ./200-concepts/100-components/01-prisma-schema/08-features-without-psl-equivalent.mdx
- ./200-concepts/100-components/01-prisma-schema/07-names-in-underlying-database.mdx
- ./200-concepts/100-components/01-prisma-schema/09-indexes.mdx
- ./200-concepts/100-components/03-prisma-migrate/100-supported-types-and-db-features.mdx
- ./200-concepts/100-components/03-prisma-migrate/300-prisma-migrate-limitations-issues.mdx
- ./300-guides/050-database/820-multi-schema.mdx
- ./300-guides/050-database/800-production-troubleshooting.mdx
- ./300-guides/050-database/300-seed-database.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/index.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/150-team-development.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/165-enable-native-database-functions.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/050-add-prisma-migrate-to-a-project.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/200-troubleshooting-development.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/160-baselining.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/170-customizing-migrations.mdx
- ./300-guides/050-database/100-developing-with-prisma-migrate/168-include-unsupported-database-features.mdx
- ./300-guides/050-database/400-prototyping-schema-db-push.mdx
- ./300-guides/050-database/700-patching-production.mdx
- ./300-guides/200-deployment/150-deploy-database-changes-with-prisma-migrate.mdx
- ./300-guides/100-performance-and-optimization/index.mdx
- ./300-guides/100-performance-and-optimization/100-prisma-client-transactions-guide.mdx
- ./300-guides/100-performance-and-optimization/150-connection-management/200-configure-pg-bouncer.mdx
- ./800-data-platform/850-billing/07-payment-method-and-billing-information.mdx

Files with a blank metaTitle:

- /100-getting-started/02-setup-prisma/index.mdx
- /200-concepts/100-components/05-prisma-cli/index.mdx
- /200-concepts/200-database-connectors/index.mdx
- /300-guides/600-general-guides/100-database-workflows/05-foreign-keys/index.mdx

**Comment by janpio** [comment]
What happens if a page has no `metaTitle`? Does it fall back to ues the `title` in the meta tag?

**Comment by jharrell** [comment]
Resolved in Docusaurus docs
