### ISSUE TITLE
Vercel builds fail consistently with `ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4085]
Vercel builds (both preview and production ones) fail randomly with the following error:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /vercel/path0/api/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/vercel/path0/api/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

### Production build from Nov 18, 2022

https://vercel.com/prisma/docs/2HN7ESUdJTXeZs7rZnwgVcQ36u7T

### Preview build from Nov 18, 2022

https://vercel.com/prisma/docs/GZkXcpkhiucQi8pyRrqMw8aiNy2D

**Comment by keerlu** [comment]
Another example: https://vercel.com/prisma/docs/6bVApmL8pJLeQLpRCtgzwwT4dX2w

**Comment by zachtil** [comment]
Another example: https://vercel.com/prisma/docs/Cj3NK5iXL6DTB8cWQFo9KuCaWRCM

**Comment by zachtil** [comment]
Another example: https://vercel.com/prisma/docs/7EupAJmHmx5SzEHExB8N2FvL4BYv

**Comment by zachtil** [comment]
One more example from Nov 23, 2022: https://vercel.com/prisma/docs/FL4or1m2A71ni4DZWru8F9W5Stg6

**Comment by meletj** [comment]
currently, disabled caching seems to resolve these but caching helps us with shorter build times so we need to fix the issue and reenable this)

**Comment by nilubava** [comment]
This particular issue has been resolved, so we will create a new issue for disabling the `gatsby clean` command in the build process: https://github.com/prisma/docs/issues/4201
