### ISSUE TITLE
Link checker should also check for broken anchor links

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4100]
Background: https://prisma-company.slack.com/archives/C02JV0K2Q31/p1669030503322899

Currently open issues for broken anchor links:

- [4092](https://github.com/prisma/docs/issues/4092)
- [4093](https://github.com/prisma/docs/issues/4093)
- [4094](https://github.com/prisma/docs/issues/4094)
- [4095](https://github.com/prisma/docs/issues/4095)
- [4096](https://github.com/prisma/docs/issues/4096)
- [4097](https://github.com/prisma/docs/issues/4097)
- [4098](https://github.com/prisma/docs/issues/4098)

**Comment by Jolg42** [comment]
See related issue about pris.ly link checker that could benefit of that as well, some suggestion to try there 
https://github.com/prisma/pris.ly/issues/60

**Comment by janpio** [comment]
Note that this is about the _internal_ link checker, which checks all the links on all pages of the _future_ state of the docs. Public link checkers would unfortunately not work for that (except if we use the preview deployments).

**Comment by Jolg42** [comment]
These tools need to have a deployment, but it could be a preview deployment or also a localhost version started from the CLI in a GitHub Action.
