### ISSUE TITLE
New help articles (November 2022) - add links to them where appropriate in the docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4107]
Support have created a series of help articles. We might want to link to some or all of these from the docs.

We need to determine which articles we want to link to, and from where in the docs.

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1669056683838809

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
