### ISSUE TITLE
Improve ref actions page

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#4139]
Regarding https://docs-git-feat-referential-actions-exceptions-prisma.vercel.app/concepts/components/prisma-schema/relations/referential-actions#special-cases-for-referential-actions:

> The hierarchy of the headlines is a bit weird not - as the "Special cases ..." is on the same level as the actual ref actions. I think one could fix that by adding a ### Overview in front of the table and introductory sentence, and making the new headline a ####.
> As the symbols of the footnotes are now further away, it might make sense to link them to the headline or the correct bullet if possible.
> Maybe there is even a better way to avoid the symbols now?

**Comment by Jolg42** [comment]
@janpio Can we close this? I see a merged PR attached

**Comment by janpio** [comment]
No, the problem still exists. This was extracted from the merged PR as it would have blocked merging.

**Comment by nikolasburk** [comment]
Closing as not planned 🙏
