### ISSUE TITLE
Post-release task: update 'Special rules for referential actions' docs

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4147]
Reorganise the 'Special rules for referential actions' section added in 4.7.0 as part of PR #4132. Would be nicer to have the footnotes immediately below the table, but have them link out to information in the special rules section below. Also can maybe order the information a bit better.

There's also a separate page on [Special rules for referential actions in SQL Server and MongoDB](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions/special-rules-for-referential-actions) - is this still relevant, and should it be linked to?

**Comment by keerlu** [comment]
There's also an old issue, #2663, that could maybe be closed or done as part of this

**Comment by janpio** [comment]
I think the separate subpage is a different kind of "special". The footnotes are mostly about things that do not actually work as hey should, and we added some warnings to handle that. The others are hard errors because of the specific way these databsaes handles these situations.

**Comment by keerlu** [comment]
I opened #4180 for the special rules page and will deal with that separately.
