### ISSUE TITLE
Update any mentions of "How to set up a free PostgreSQL database on Heroku" article 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4167]
Heroku doesn't offer any free tier DBs any more so we should update the mentions to the article: 

- old link: https://dev.to/prisma/how-to-setup-a-free-postgresql-database-on-heroku-1dc1
- new link: https://dev.to/prisma/set-up-a-free-postgresql-database-on-supabase-to-use-with-prisma-3pk6

Using a global search in the docs content for the old URL should quickly reveal all instances where the old article is mentioned.

**Comment by zachtil** [comment]
To update that in the Deploying to Netlify guide.

**Comment by ruheni** [comment]
Duplicate of https://github.com/prisma/docs/issues/4699 & completed 🙂
