### ISSUE TITLE
It's not clear what format is required for `secret` property in `prisma` config

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [prisma/prisma2-docs#4185]
I've expected to see regex to know `secret` format of requirements written by words.

**Comment by ruheni** [comment]
Hey 👋

Could you share more details on what you're referring to or a page in the docs?

**Comment by janpio** [comment]
Sounds to me this could refer to Prisma 1, which had a `secret` property in the configuration.

Current Prisma does not.

**Comment by ruheni** [comment]
I'll go ahead and close it since we don't support Prisma 1 anymore
