### ISSUE TITLE
No `subscriptions` key mentioned in config description

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [prisma/prisma2-docs#4186]
No `subscriptions` key mentioned in config description [here](https://v1.prisma.io/docs/1.34/prisma-cli-and-configuration/prisma-yml-5cy7/). I am editing [config file JSON schema](https://github.com/SchemaStore/schemastore/pull/2631) and don't know what to do with this key: remove or not.

**Comment by ruheni** [comment]
We currently don't maintain Prisma 1 anymore. I'll go ahead and close the issue
