### ISSUE TITLE
Tracing docs: consider adding suggested information

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4199]
See Tyler's message here: https://prisma-company.slack.com/archives/C02K05SHRAT/p1665683085429849?thread_ts=1665670882.830289&cid=C02K05SHRAT

"we use @opentelemetry/sdk-node rather than sdk-trace-node. sdk-node  does some things automatic that are setup manually in the Prisma docs. It was still as easy as adding in PrismaInstrumentation, but the NodeSDK instance by default adds batching and initializes asynchronously which caused a little bit of confusion when testing things locally. It might be worth considering adding an sdk-node example to the docs and possibly expanding the "My traces aren't showing up" section to mention something about batch processing along with encouraging a "flush" during process exit."

**Comment by janpio** [comment]
I think Honeycomb's default documented example also switched over to this simpler approach.

**Comment by jharrell** [comment]
Closing this in favor of #4108 🙏
