### ISSUE TITLE
Disable the `gatsby clean` command in the build process to improve build time

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#4201]

**Comment by zachtil** [comment]
One Vercel preview build failed today with plenty of broken links: https://vercel.com/prisma/docs/2ogWo7Gy8sLjUHp4aq1oZK7pQ4te

On clicking Redeploy, it built successfully: https://vercel.com/prisma/docs/95AwZaGAxLk6kEDB13MoabMNf7Vo

Does this help @nilubava?

**Comment by zachtil** [comment]
On a lot of other builds from today, we are seeing builds ranging from 2 - 4 min, which seems faster indeed.
