### ISSUE TITLE
Wrong icon alignment 

### ISSUE THREAD

**Issue by vuki656** [prisma/prisma2-docs#4203]
https://www.prisma.io/docs/guides/testing/unit-testing

![image](https://user-images.githubusercontent.com/8104698/205991576-017334b2-b788-4e74-9533-a5a80280cf37.png)

**Comment by mohitmohlia** [comment]
@vuki656 can you assign this to me
adding align-items:center resolves this issue
<img width="1617" alt="Screenshot 2023-04-03 at 3 13 11 PM" src="https://user-images.githubusercontent.com/46368810/229473312-40b41489-fc58-4ec2-bc4a-06a0c12a8431.png">

**Comment by meletj** [comment]
Fixed with the implementation of new admonitions.
