### ISSUE TITLE
Comment with Vercel deploy URLs: Slashes in branch names break the link

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#4210]
Example: https://github.com/prisma/docs/pull/4191

Solution: Replace `/` in branch names with `-`.

**Comment by nilubava** [comment]
@janpio Is this a webdev issue?

**Comment by janpio** [comment]
Yes.

**Comment by nilubava** [comment]
@janpio Could you please explain this issue? AFAIK, there is no problem with `/` in branch names when deploying on Vercel, and the connected PR does not give any context on what the exact issue is

**Comment by janpio** [comment]
We have a GH Actions workflow called "Comment with Vercel deploy URLs". It adds a comment to a PR with preview links to Vercel. For branches with `/` in the name, these URLs are invalid. We need to replace the `/` with a `-` it seems.

Change probably needed here: https://github.com/prisma/docs/blob/73bd7610bb73784a821b8d410dda96e12858687b/.github/workflows/list-changed-pages.yml#LL32C28-L32C28

**Comment by janpio** [comment]
The underlying GH Action did not change. Was this really fixed?

**Comment by janpio** [comment]
Seems happened in weirdly named https://github.com/prisma/docs/pull/4475

Thanks!
