### ISSUE TITLE
Update 'Deploy to Cloudflare Workers' guide

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4218]
Update https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers:
- Bring language up to style guide standard

@ObamaTheLlama114 tested the steps as part of #3188 , so we know that they work.

**Comment by janpio** [comment]
Related: https://github.com/prisma/team-orm/issues/145

**Comment by janpio** [comment]
Explicitly take care of https://github.com/prisma/docs/issues/3620

**Comment by ruheni** [comment]
Can this be marked as complete now since https://github.com/prisma/docs/pull/5377 was merged? 🤔
