### ISSUE TITLE
Improvements to deployment guides

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4270]
When we revisit the deployment guides structure and contents in the future, we can consider doing the following improvements.

* The steps to create a database for each guide can live in a single page from where it can be referenced in each guide.
* Include steps to set up projects in deployment platforms with both Web UI and CLI.

Let's add further improvements to this list.

**Comment by ruheni** [comment]
Closing this as a duplicate of https://github.com/prisma/docs/issues/4721
