### ISSUE TITLE
Add example for mongo db nested json querying to the documentation

### ISSUE THREAD

**Issue by ludralph** [prisma/prisma2-docs#4278]
Currently, in the documentation, there is no example of mongo DB nested JSON querying. 

A user suggested we add an example to the docs to help other users based on this [Slack conversation](https://prisma.slack.com/archives/CA491RJH0/p1669051843892409).

He tried this query but it returned empty data
```js
prismaMongo.webhooks.findRaw({
   filter: {
     webhookBody: {name: 'test'}
 }});
```

The query that worked is 
```js
prismaMongo.webhooks.findRaw({
  filter: {
    'webhookBody.name': 'test'
  }
});
```
We can add it to this [section](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#findraw) of the documentation.

**Comment by ruheni** [comment]
While I agree this would be useful in the docs, we can't exhaust the query examples on the page. Linking to MongoDB's `find` command should be sufficient.
