### ISSUE TITLE
Add note about various native type information.

### ISSUE THREAD

**Issue by ludralph** [prisma/prisma2-docs#4281]
A user, Peter Belbin through this [Slack](https://prisma.slack.com/archives/CA491RJH0/p1670008307160069?thread_ts=1669997451.678439&cid=CA491RJH0) conversation requested that we add documentation about the various native type information - specifically that it's not used by the Client or Query Engine, but that it is used by tooling such as the migration tool. This is based on this question
>hey there!  Can anyone tell me this: is the @db.UnsignedInt identifier that can be applied to the prisma schema column definition only used by the migrate tool, or, is it also used by the prisma client (generated code & engine)?  If it's used by the generated code and runtime, can you point me to some documentation that mentions this?

**Comment by ruheni** [comment]
Hey Raphael 👋

All database native types use the data type that the database provides. 

We document all the Polyfills, i.e., features that are typically not achievable with particular databases or require extensions, on [this page](https://www.prisma.io/docs/concepts/components/prisma-client/database-polyfills)
