### ISSUE TITLE
Amazon Aurora Serverless v2

### ISSUE THREAD

**Issue by IamManchanda** [prisma/prisma2-docs#4291]
Is Amazon [Aurora](https://aws.amazon.com/rds/aurora/) [Serverless](https://aws.amazon.com/rds/aurora/serverless/) [v2](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html) supported by Prisma?

https://www.prisma.io/docs/reference/database-reference/supported-databases

**Comment by janpio** [comment]
We have no signal indicating otherwise, so "AWS Aurora Serverless" includes both versions.
If you try it out and find things that do not work, please open that issue.

**Comment by IamManchanda** [comment]
Got it @janpio ... Thanks for your valuable reply :)
