### ISSUE TITLE
Add Data Proxy `directUrl` property to `datasource` block documentation

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4297]
The Data Proxy is getting a new `directUrl` property to be set in the `datasource` block to allow a direct connection for migrations and introspection. (Currently [this workaround](https://www.prisma.io/docs/data-platform/data-proxy/prisma-cli-with-data-proxy) is being used instead.)

Add this to the [schema reference `datasource` docs](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#datasource).

Relevant links:
- https://www.notion.so/prismaio/Soothing-pain-when-using-introspect-migrate-with-DataProxy-6898978456ea4b4fba2ac77898465e2d#8c974e2753874bf4ae4b10006a87f735
- https://github.com/prisma/prisma-engines/pull/3551

**Comment by amlcodes** [comment]
DIRECT_URL its working for me, but only when hardcoded in schema. at least with dotenv -e ../../.env it is failing everytime. DATABASE_URL is next to it working fine.

**Comment by janpio** [comment]
Can you open a new issue in `prisam/prisma` please @amlcodes? Happy to take a look if we overlooked something. Optimally provide a simple reproduction repository with a project we can jsut run. Thanks!

**Comment by janpio** [comment]
Can you open a new issue in `prisam/prisma` please @amlcodes? Happy to take a look if we overlooked something. Optimally provide a simple reproduction repository with a project we can jsut run. Thanks!

**Comment by amlcodes** [comment]
looks like it resolved in 4.10.1! much appreciation to you all. This fixes the worst bits of DX i've had to make a equally poor workaround for, and makes prisma entirely flawless for me now. thank you!
