### ISSUE TITLE
Link to new Jetbrains plugin

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4314]
Jetbrains recenrtly published an [official Prisma plugin](https://plugins.jetbrains.com/plugin/20686-prisma-orm), we should add this here: https://www.prisma.io/docs/guides/development-environment/editor-setup#jetbrains-ide

<img width="817" alt="Screenshot 2022-12-29 at 14 24 58" src="https://user-images.githubusercontent.com/4058327/209959014-8a3c55f9-61c3-46b2-b628-1f3ce0eea96c.png">

[Link to Slack convo](https://prisma.slack.com/archives/C01739JGFCM/p1672304342053169)

**Comment by ruheni** [comment]
The docs have been updated with the official plugin. Going ahead and closing the issue.
