### ISSUE TITLE
Consider clarifying the term "artifacts" in our docs

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4318]
In our docs, we use the term "artifacts" a few times. It's also used in the Prisma CLI output. It seems to mean slightly different things each time:

- [Database elements](https://www.prisma.io/docs/concepts/components/prisma-migrate/db-push#choosing-db-push-or-prisma-migrate)
- [Database elements?](https://www.prisma.io/docs/reference/api-reference/command-reference#migrate-deploy)
- [Files?](https://www.prisma.io/docs/concepts/components/prisma-migrate/migrate-development-production#create-and-apply-migrations) - there are a couple of instances on this page

Instead of saying "artifacts", should we spell out what we mean in each case? Or is it clear enough already?

See reply from Jan about this: https://prisma-company.slack.com/archives/CEYCG2MCN/p1671723495546119. Basically, the first item in the list above is not Prisma-specific and means "things that could exist in a database". The last one is Prisma-specific and it means "things that could be created by a generator defined in a Prisma schema". 

Also, information from Joël:

> `migrate reset`
> 
> This command deletes and recreates the database, or performs a ‘soft reset’ by removing all data, tables, indexes, and other artifacts.

Databases can contain a lot of “things”, some that Prisma understands and some not. and here a reset of the database would get rid of anything present.

> `--skip-generate`	Skip generation of artifacts such as Prisma Client

Here it’s in the context of generators, where a generator could do pretty much anything, Prisma Client is one and when triggered creates files on the filesystem. But community generators can do anything they want in their own generator.

From Jan:

> I think in this case it might be better just to say that "execution of generators is skipped" - becaue that is what it does. It does not run prisma generate under the hood. That those can create artifacts is correct, but not really the important bit of the db push (or other) documentation.
> 
> So if we find a better way to express this, we can get rid of the term "artifact" there completely maybe.

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
