### ISSUE TITLE
Serverless: guide needed for Esbuild

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4323]
We don't have a guide about how to use Prisma with Esbuild, and we need one.

- [Slack conversation](https://prisma-company.slack.com/archives/CUXLS0Z6K/p1671719432776239)

It appears that [for Webpack and Parcel](https://www.prisma.io/docs/concepts/components/prisma-client/module-bundlers) we simply link to the official docs, and that might be sufficient for Esbuild. But we will still want to check that the official docs work as-is on a Prisma project - that's why my estimate for this task is quite large.

But we also need to consider: what about other bundlers - are they supported at all? Or perhaps they work without a plugin?

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
