### ISSUE TITLE
Nanoid default value

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma2-docs#4363]
This just got merged: https://github.com/prisma/prisma-engines/pull/3556

We should document it in a similar way as we document cuid et.al. To here:

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#cuid

ping @rintaun

**Comment by janpio** [comment]
Here is a list of all the places where we mention `uuid()` and `cuid()` in relevant ways:
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#cuid
https://www.prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#using-functions
https://www.prisma.io/docs/concepts/components/prisma-client/database-polyfills
https://www.prisma.io/docs/concepts/components/prisma-schema/features-without-psl-equivalent#when-to-use-a-database-level-function
https://www.prisma.io/docs/concepts/components/prisma-migrate/supported-types-and-db-features

That should give you enough places to mention `nanoid()` @rintaun

**Comment by rintaun** [comment]
@janpio thanks for looking all of those places up! I hope to be able to get to this tomorrow after work

**Comment by Jolg42** [comment]
Note: this is blocked by some work that still needs to happen but is currently not planned, see https://github.com/prisma/prisma/issues/17199

**Comment by ankur-arch** [comment]
Hi @pimeys 👋,

Thank you for opening this issue! We're in the process of tidying up our documentation-related issues. Since this is still blocked by #17199, I’ll be closing it for now. Rest assured, we’ll have the info in the docs once #17199 is merged.

Appreciate your understanding! 🙏
