### ISSUE TITLE
PDP: Landing page improvements

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4372]
Currently, PDP seems to have two landing pages:

- https://www.prisma.io/docs/data-platform
- https://www.prisma.io/docs/data-platform/about

The first page is what we link to from the top-level PDP section in Prisma Docs. That page contains no content and only lists the contents of the sections. Naturally, that page though receives a lot more pageviews.

Solutions

1. Change the PDP top-level docs link to point to https://www.prisma.io/docs/data-platform/about.
2. Update the actual landing page contents with current information from the About page + updated information for PDP.

**Comment by ankur-arch** [comment]
This is outdated
