### ISSUE TITLE
Explore lost-pixel tool for visual regression testing

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#4404]
> Explore the tool and since our Browserstack/Percy contract is up for renewal end of March this year (just got another email of our totally unhelpful sales rep), It would be amazing if we could migrate to Lost Pixel before that date. 

https://prisma-company.slack.com/archives/C04HV772KS7/p1673258634330399

**Comment by meletj** [comment]
@nilubava please make sure to check against open issues with Percy. So we can see if lost pixel fixes these. 
https://github.com/prisma/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22topic%3A+percy%22

**Comment by meletj** [comment]
Percy's contract will end on 31 March 2023. Finalize Docs implementation with lost-pixel during that time incl. informing wider team and providing training/how to.
