### ISSUE TITLE
Using connect and create in a 1-1 relation 

### ISSUE THREAD

**Issue by ludralph** [prisma/prisma2-docs#4417]
A user finds the documentation on using connect and create in 1-1 relations confusing as can be seen in this [slack conversation](https://prisma.slack.com/archives/CA491RJH0/p1669323754250099)

This would also require clarity around the use of UncheckedCreateInput 

Possible place: dedicated section or under “Nested Writes": https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries

**Comment by TasinIshmam** [comment]
The user's confusion was not really about 1:1 relation but instead about mixing fields from`UncheckedInput` and `Input` types in a very complex schema. The complexity of the schema created confusion more than anything else. 

I don't think it makes sense to duplicate the queries in the Nested Writes section with 1-1 relations, as the syntax is nearly identical and conveys no meaningful new information. Furthermore, 1-1 relations are a fairly "niche" use case.  

Clarification about `UncheckedInput` types is provided in #4645. 

@nikolasburk is it okay to close this issue?

**Comment by nikolasburk** [comment]
Yes, sounds reasonable. Feel free to close 👍
