### ISSUE TITLE
Update SQL snippet for views page

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4418]
The current `CREATE VIEW` snippet will not work on MySQL. Investigate whether it can be written in a way that works on all supported databases.

Some context in Slack conversation [here](https://prisma-company.slack.com/archives/C04A45D6BNY/p1673950409407189?thread_ts=1673909526.607709&cid=C04A45D6BNY).

**Comment by keerlu** [comment]
I did some brief investigation last week and rewriting to have one SQL statement that works on all of them does not look promising, as Postgres requires the `"`s that MySQL doesn't like.

I think this would also apply to most of our example SQL statements, which are often written for Postgres only, so this is likely to be a wider topic than just the views page.

**Comment by sabinadams** [comment]
After some research, Postgres automatically lower-cases names that aren't surrounded by _quotes_. So `UserInfo` would turn into `userinfo`. `Profile` would be `profile`. 

MySQL does not have this problem. It _does_ allow you to wrap names in _backticks_, but does not support wrapping names in _quotes_ like Postgres requires. Postgres does not support _backticks_. 

Looking like the only way to write a query like this that works on both would be to use lower-case names, but that goes against our naming convention suggestions.

Seems the solution would be to either:

1. Have a tabbed view on every query showing _Postgres_, _MySQL_, _MongoDB_ syntaxes
2. State somewhere in the docs to be wary that SQL-based code examples default to Postgres syntax

**Comment by nikolasburk** [comment]
Let's add a note that we use Postgres by default as a SQL dialect about this to the style guide here: https://www.prisma.io/docs/about/prisma-docs/style-guide/schema-models

Also mention that depending on context, different SQL dialects might be available via the tech switcher on top of the page or tabbed code blocks.
