### ISSUE TITLE
Get started/set up Prisma/Start from scratch/MongoDB can't finish tutorial

### ISSUE THREAD

**Issue by student-ops** [prisma/prisma2-docs#4445]
I followed the steps in /Get started/set up Prisma/Start from scratch/MongoDB.

I got the following error
``` error message in vscode
Type '{ comments: { createMany: { data: { comment: string; }[]; }; }; }' is not assignable to type '(Without<PostUpdateInput, PostUncheckedUpdateInput> & PostUncheckedUpdateInput) | (Without<...> & PostUpdateInput)'.
  Object literal may only specify known properties, and 'comments' does not exist in type '(Without<PostUpdateInput, PostUncheckedUpdateInput> & PostUncheckedUpdateInput) | (Without<...> & PostUpdateInput)'.ts(2322)
```
I think this may be due to the missing comment element in the Post model of the prisma schema.

**Comment by ruheni** [comment]
Hey 👋

Thanks for raising this. Your hunch is correct. The `Comment` model was removed from the guide. I've linked to the PR that updates the Getting Started guide. This should be merged soon. 🙂

**Comment by student-ops** [comment]
I forgot about it for a while, but thanks for picking it up.✌
