### ISSUE TITLE
Troubleshooting docs for `next.js` work

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4448]
SME: Pierre

Docs might be needed for this - check with Pierre.

**Comment by andrew-walford-prisma** [comment]
FAO @mcbethio

**Comment by mcbethio** [comment]
@sabinadams another one andrew was working on.
@millsp is your point of contact regarding this one.

**Comment by janpio** [comment]
We are not sure if this has impact yet, we do have a workaround but are still figuring out if it works and is the right one to document.

**Comment by janpio** [comment]
Stub for content PR created: https://github.com/prisma/docs/pull/4521
