### ISSUE TITLE
Data Proxy CLI solution mistake 

### ISSUE THREAD

**Issue by dskiba** [prisma/prisma2-docs#4453]
Hi! I think there is some mistake on the page - https://www.prisma.io/docs/data-platform/data-proxy/prisma-cli-with-data-proxy#solution

This script wouldn't work, since yarn or npm can't read '.env' variables and set them to the DATABASE_URL
```js file=package.json highlight=5,6;add
{
  ...,
  "scripts": {
    "generate-client": "prisma generate --data-proxy",
    "migrate-deploy": "DATABASE_URL=\"$MIGRATE_DATABASE_URL\" prisma migrate deploy",
    "dev": "DATABASE_URL=\"$MIGRATE_DATABASE_URL\" prisma migrate dev",
  }
}
```

In the end you would get error like this one
```sh
Error validating datasource `db`: You must provide a nonempty URL. The environment variable `DATABASE_URL` resolved to an empty string.
```

**Comment by janpio** [comment]
That is correct, you would need to also use `dotenv-cli` to actually load the `.env` file first.

We are fortunately working on a proper feature to replace this hack though which should be released with the next release of Prisma CLI.

**Comment by TasinIshmam** [comment]
This has been fixed with [`directUrl`](https://www.prisma.io/docs/data-platform/data-proxy/prisma-cli-with-data-proxy#set-a-direct-database-connection-url-in-your-prisma-schema).
