### ISSUE TITLE
https://www.prisma.io/docs is down

### ISSUE THREAD

**Issue by SorenHolstHansen** [prisma/prisma2-docs#4459]
https://www.prisma.io/docs is down, getting

<img width="1470" alt="Screenshot 2023-01-27 at 10 41 36" src="https://user-images.githubusercontent.com/54755687/215055621-ec80823d-c409-40c9-b91b-4bb2ef22c910.png">

**Comment by nilubava** [comment]
@SorenHolstHansen It is back up now, thanks for noticing and reporting this 👍
