### ISSUE TITLE
Consider clarifying/correcting our docs on mapping dates

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4461]
In our public-facing Slack, a user has asked for more clarity (or possibly a correction) about mapping dates in our docs. He didn't say which doc/s specifically he was looking at.

[User's thread
](https://prisma.slack.com/archives/CA491RJH0/p1671466241108729?thread_ts=1671463298.838409&cid=CA491RJH0)

[Our Internal Slack discussion](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1673469213271289)

Someone needs to investigate whether our docs are misleading or incomplete on this and fix.

Lucy notes that our new [type system guide](https://www.prisma.io/docs/guides/database/prisma-type-system#native-type-mappings) might be useful. It uses DateTime and @db.Date as an example . It might be sufficient to cover this subject, or it might be a good resource when you update any other pages for this ticket.

**Comment by TasinIshmam** [comment]
Closing this because there's nothing actionable. The user did not clarify what part of the documentation confused him, and the existing documentation, to the best of my knowledge, is accurate.
