### ISSUE TITLE
The select dropdown menu for official site has overlapping issue

### ISSUE THREAD

**Issue by xJkit** [prisma/prisma2-docs#4471]
https://www.prisma.io/client

## The Select UI is good on mobile:
![CleanShot 2023-01-30 at 11 18 12](https://user-images.githubusercontent.com/18704345/215380331-f5e46758-e8f4-46a9-b31c-0c814179599b.jpg)

## However, it's overlapped by the next select component on desktop:
![CleanShot 2023-01-30 at 11 18 23](https://user-images.githubusercontent.com/18704345/215380435-cf795791-63f6-4865-8c8b-f2ee57ffdb22.jpg)

**Comment by nilubava** [comment]
Hi @xJkit Thanks for noticing this and opening an issue. We have transferred this issue to our Web dev team and will update you once it is fixed.

**Comment by nilubava** [comment]
Hi @xJkit This issue has been fixed.
