### ISSUE TITLE
`prisma studio` does not actually support `directUrl`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#4492]
Via https://github.com/prisma/docs/pull/4377/files we changed the documentation in 4.10.0 to say that `directUrl` can be used to use CLI commands when using `url = "prisma://..."`. That is actually not true for `prisma studio` so we should add that as a special case. We can mention there that when they are using `prisma://...` they already have a PDP project and can use the Data Browser.

**Comment by ruheni** [comment]
This has been documented here: https://www.prisma.io/docs/data-platform/data-proxy/prisma-cli-with-data-proxy#:~:text=prisma%20studio%20currently%20doesn%27t%20support%20the%20directUrl%20property.
