### ISSUE TITLE
Missing custom 404 pages

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#4496]
https://docs.google.com/spreadsheets/d/18mSh18_PfDP7wn8Y2y_aj9M9GU3RB0Nu/edit?usp=sharing&ouid=103180279849721400399&rtpof=true&sd=true

**Comment by carlagn** [comment]
Nilu [17 hours ago](https://prisma-company.slack.com/archives/D03EJ4CDNAZ/p1677774093125279?thread_ts=1677773950.744389&cid=D03EJ4CDNAZ)

> Yes, this is something which happened after our change in vercel directory settings for docs project. I have asked them in the shared channel if they have a solution for this, but they havent replied yet. I will ping him again directly

**Comment by meletj** [comment]
Slack convo in #shared-vercel https://prisma-company.slack.com/archives/CBP68USAX/p1674822575566699

**Comment by nilubava** [comment]
For dataguide too

**Comment by nilubava** [comment]
Status update: Opened a support ticket and Vercel team is looking into this currently

**Comment by meletj** [comment]
Fixed by move to Docusaurus
