### ISSUE TITLE
Fonts Size Issue in Docs Search Component

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#4540]
The results of search query have increased font size.

<img width="1379" alt="Screenshot 2023-02-23 at 12 40 01 AM" src="https://user-images.githubusercontent.com/13049676/220740325-f74d8b91-3b3f-4bfb-8d9f-b488324cb873.png">

**Comment by nurul3101** [comment]
One thing that I noticed is that font size gets bigger if search is triggered from home page: https://www.prisma.io/docs/
But if search is triggered from any other subpage then font size is normal. For example triggering search from here: https://www.prisma.io/docs/reference/database-reference/connection-urls will keep the font size as expected.

**Comment by janpio** [comment]
Can confirm the bug:
https://www.prisma.io/docs?page=1&query=test
<img width="923" alt="image" src="https://user-images.githubusercontent.com/183673/220880494-e8edefb6-b932-40d6-9617-bc021ce4bca0.png">
https://www.prisma.io/docs/reference/database-reference/connection-urls?query=test&page=1
<img width="933" alt="image" src="https://user-images.githubusercontent.com/183673/220880534-86ddb2d5-6c6f-413d-9ff6-25fd2929c74d.png">
