### ISSUE TITLE
Clarify what are Checked and Unchecked Types and the difference between them.

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#4552]
We created checked and unchecked type for models in the schema file. We should have an explanation on what's the purpose of them.

We can clarify that “Unchecked” input types allow you to perform some operations that prisma considers “dangerous”, like directly writing foreign keys and we allow you to choose either a “safe” or an unchecked input type when doing operations like create, update.

**Comment by TasinIshmam** [comment]
Hey @nurul3101  would it be possible to provide a bit more context or the user question/support ticket that led to the creation of this issue?

**Comment by janpio** [comment]
No user question necessary. We have checked (normal API with connecting relations etc) and unchecked types (set the foreign key value directly), and those are not properly documented yet.
