### ISSUE TITLE
Typo on www.prisma.io/planetscale page

### ISSUE THREAD

**Issue by alumpe** [prisma/prisma2-docs#4587]
I just wanted to inform you about a small typo on the https://www.prisma.io/planetscale page. In the paragraph regarding "Prisma & PlanetScale best practices" there is written "fefining indices" instead of "defining indices".  
I didn't find that page as part of the docs or any other public repo, so I couldn't make a pull request myself and posted it here.

**Comment by janpio** [comment]
Thanks for the report, that is a currently private repo - and I quickly fixed that. Should be live in a few minutes.
