### ISSUE TITLE
TOC scrolling underline breaks because of not-in-TOC-included headlines

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#4627]
Details: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1680183795248509

**Comment by meletj** [comment]
Problem: When scrolling through https://www.prisma.io/docs/concepts/components/prisma-schema/features-without-psl-equivalent the right hand sidebar underlining behaves weird. Initially the first link is underlined, but when you scroll down a bit nothing is underlined. Only when you then get to the next top level headline the link for that one is underlined again. And at the end the headline disappears already without ever highlighting the last link.

Reason: Only visible headings are taken into account for the IntersectionObserver here. https://github.com/prisma/docs/blob/bd99f48a19dc88f8f0e254d38dbf5216189e2e89/src/components/toc.tsx#L106

**Comment by meletj** [comment]
When fixed, update this page accordingly https://www.prisma.io/docs/about/prisma-docs/docs-components/frontmatter#tocdepth

**Comment by nilubava** [comment]
Reopening because the new [PR](https://github.com/prisma/docs/pull/4690) for this is still open and has unresolved comments  

Also, maybe related? : https://github.com/prisma/docs/issues/3955

**Comment by carlagn** [comment]
@nilubava [on closer inspection](https://github.com/prisma/docs/issues/3955#issuecomment-1542312696), no 😓

**Comment by nilubava** [comment]
Okay, so let us close the original issue by merging the PR then
