### ISSUE TITLE
Link checker: Log output of redirects

### ISSUE THREAD

**Issue by meletj** [prisma/prisma2-docs#4628]
Suggestion for the link checker: 
It would be nice if it could output (only as warning, not as error) internal links that do not directly link to a valid page but trigger a **redirect**.
We should update these when we rename pages, but right now that is a super manual process to find them.

**Comment by nilubava** [comment]
Refer to this [convo](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1681480156271919?thread_ts=1681466903.856869&cid=C5Z9TH6N9) for the script idea
