### ISSUE TITLE
ORM query: example for field == null

### ISSUE THREAD

**Issue by jelmd** [prisma/prisma2-docs#4667]
There is nowhere mentioned, how to ORM query a table for entries having a certain field set (i.e. NOT NULL).

**Comment by ruheni** [comment]
Hey 👋🏾 

> how to ORM query a table for entries having a certain field set (i.e. NOT NULL).

Could you clarify your statement? Do you mean creating a filter for a query for records in a table whose value is `null` or querying for records whose field is not null?

This query returns all records whose `content` field is `null:
```
const posts = await prisma.post.findMany({
  where: {
    content: null
  }
})
```

This query returns all records whose `content` field is not null:

```
const posts = await prisma.post.findMany({
  where: {
    content: { not: null }
  }
})
```

Does this answer your question? We'll add this to our documentation. 🙂

**Comment by jelmd** [comment]
Yes, perfect :)
