### ISSUE TITLE
Broken Links in Prisma Migrate docs

### ISSUE THREAD

**Issue by cosileone** [prisma/prisma2-docs#4675]
Customizing Migrations docs sections found here
https://www.prisma.io/docs/concepts/components/prisma-migrate/migrate-development-production#customizing-migrations

Has broken links to guides in text which should be fixed:
>Refer to [Customizing migrations](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations) for examples.

(broken link should be https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/customizing-migrations)

and 

>See: [Team development with Prisma Migrate](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/team-development) .

(broken link should be https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/team-development)

**Comment by ruheni** [comment]
Hey 👋🏾 

Thanks for raising this. We re-organized some of the content and set up redirects. The broken URLs should redirect you to the correct pages now. 🙂
