### ISSUE TITLE
New doc table of contents don't have all the headings

### ISSUE THREAD

**Issue by Arlen22** [prisma/prisma2-docs#4683]
### Bug description

Most of the Prisma documentation is missing the individual item headings in the table of contents. For instance, the [filter conditions and operators](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#filter-conditions-and-operators) section does not list the individual operators. This makes it difficult to find them and then only if you know they're there, whereas before it was very simple and easy to explore. 

Some kind of browser setting would be fine. 

### How to reproduce

NA

### Expected behavior

NA

### Prisma information

NA

### Environment & setup

NA

### Prisma Version

NA

**Comment by ruheni** [comment]
Hey 👋

Could you clarify what you mean? You can access the individual operators from the Table of Contents, but you would have to scroll. If that's what you're referring to, then It would make sense for the table of contents to automatically scroll once you land on a given section on the page.

Let me know if this is what you're referring to. :) 

![CleanShot 2023-04-21 at 14 43 49@2x](https://user-images.githubusercontent.com/33921841/233639278-f23fa940-0731-4c89-a467-bc7257380d10.png)

**Comment by Arlen22** [comment]
It didn't look like that when I posted it. Looks like it got fixed. The page I linked originally now looks correct.
