### ISSUE TITLE
Are `cuid()` and `uuid()` valid for MongoDB in the Prisma schema reference?

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4766]
In the Prisma schema reference, we provide examples for default ID values for MongoDB using `cuid()` and `uuid()`. Is that valid?

e.g. here: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#cuid

<img width="534" alt="image" src="https://github.com/prisma/docs/assets/4058327/138ebb09-8155-49a7-9e68-e12e1a96e829">

Isn't the _only_ valid option for MongoDB using `@default(auto())`?

**Comment by ruheni** [comment]
Yes, it's valid (tested it out)

The difference is that with `auto()`, the database will handle id generation, and with `cuid()`, and `uuid()`, Prisma Client will generate the ids
