### ISSUE TITLE
@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

### ISSUE THREAD

**Issue by Daim-Nickel-Penny** [prisma/prisma2-docs#4769]
# Issue with Prisma Client Initialization on AWS Elastic Beanstalk

## Project Configuration

- **Framework**: NestJS
- **ORM**: Prisma
- **Deployment platform**: AWS Elastic Beanstalk

## Issue

When deploying my NestJS application using Prisma ORM to AWS Elastic Beanstalk, I encounter an error stating `@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.`

## What I Have Tried

1. Followed the instructions given in the [Caveats when deploying to AWS platforms](https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-elastic-beanstalk).
2. Added the Prisma CLI package to project dependencies instead of devDependencies, and ran `npm install` to update the `package-lock.json`.
3. Set the AWS Elastic Beanstalk `NPM_USE_PRODUCTION` environment property to `false` to install devDependencies on AWS Elastic Beanstalk instances.

Despite these steps, the issue persists. 

Any help would be greatly appreciated.

**Comment by jharrell** [comment]
Hi @Daim-Nickel-Penny,

If you're still experiencing this issue, could you please open an issue in the [prisma/prisma](https://github.com/prisma/prisma) repository? This will help us determine whether it's a documentation issue or a bug and address it accordingly.

Thank you for your understanding!
