### ISSUE TITLE
Cards in "Reference"-section on prisma.io/docs are highlighted when hovered but are not clickable

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4810]
Maybe it's just me but I find this UX at the bottom of the [docs landing page](https://www.prisma.io/docs) is a bit confusing. 

If I hover over a card, it gets higlhighted and thus tells me it's clickable. However, when I click nothing happens. I need to either click the arrow or one of the bullets to navigate to another page.

without hover:
<img width="256" alt="image" src="https://github.com/prisma/docs/assets/4058327/9efaccb0-a250-4627-a421-19b2360f4e49">

with hover:
<img width="265" alt="image" src="https://github.com/prisma/docs/assets/4058327/a259736d-2d9f-4540-991f-84368c6a57a6">

**Comment by nilubava** [comment]
@nikolasburk We are planning on revamping the docs homepage this quarter anyway, and this will be addressed soon

**Comment by meletj** [comment]
Closing as stale since we've updated the Docs landing page.
