### ISSUE TITLE
Best practice for instantiating PrismaClient with Next.js breaks instanceof

### ISSUE THREAD

**Issue by Schmavery** [prisma/prisma2-docs#4818]
If I follow the advice in the [Best practice for instantiating PrismaClient with Next.js](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices) docs page, it seems to prevent instanceof checks from working when I do error checking as described on the [Handling exceptions and errors](https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors) page.

I suspect what may be happening is that the exceptions created by the cached PrismaClient are a different type (though the same name) as the ones that I import (like Prisma.PrismaClientKnownRequestError). I've tried to figure out some way to cache the namespace as well, but haven't had any success and wanted to see if anyone else had run into this problem.

Specifically, if you set up a project using the example code in those docs, the error won't get caught after a dev refresh:

db.ts
```typescript
import { PrismaClient } from '@prisma/client'

const globalForPrisma = global as unknown as {
  prisma: PrismaClient | undefined
}

export const client =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: ['query'],
  })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
```

test.ts
```typescript
import { Prisma } from '@prisma/client';
import { client } from './db';

try {
  await client.user.create({ data: { email: 'alreadyexisting@mail.com' } })
} catch (e) {
  if (e instanceof Prisma.PrismaClientKnownRequestError) {
    // The .code property can be accessed in a type-safe manner
    if (e.code === 'P2002') {
      console.log(
        'There is a unique constraint violation, a new user cannot be created with this email'
      )
    }
  }
  throw e
}
```

Maybe there's a way to access these types directly from a prismaclient instance?

**Comment by Schmavery** [comment]
Another option would be to add something like [this `is()` function](https://orm.drizzle.team/docs/goodies#compare-objects-types-instanceof-alternative) that Drizzle provides.

**Comment by jharrell** [comment]
Hi @Schmavery,

Just wanted to follow up and see if you're still experiencing this issue. We've recently updated our pages, and the suggested code has been revised, so the problem may now be resolved.

Did you manage to find a workaround in the meantime? If not, we encourage you to try the updated code. Please let us know if you continue to face any issues—we're here to help!

Thank you for your patience, and we look forward to your feedback.
