### ISSUE TITLE
Prisma 5: upgrade guide

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#4848]
Similar to https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4
We need an Upgrade to Prisma 5 page that lists all the breaking changes and what users need to do (upgrade path).
It will be useful to have it linked in the release notes, similarly as in https://github.com/prisma/prisma/releases/tag/4.0.0 release notes.

Currently, I'm working to make an exhaustive list on Notion here: https://www.notion.so/prismaio/Breaking-changes-in-Prisma-5-1b96eaf74b16467e8d87523825d48f42#4f892485853d4b0a9c815f42ee4470ef

Though many things are not ready yet, if you want to start working on this, there are some parts that can be started now, and I can help to list these.

**Comment by jharrell** [comment]
Working through the upgrade guide, our docs [here](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types?query=composite%20type&page=1#finding-records-that-contain-composite-types-with-find-and-findmany) will need to be updated if they haven't already
