### ISSUE TITLE
Add `Next` button at the end of the page

### ISSUE THREAD

**Issue by AhmedBaset** [prisma/prisma2-docs#4875]

**Comment by ruheni** [comment]
Hey @A7med3bdulBaset, could you share the page that you would like us to add the button to?

**Comment by AhmedBaset** [comment]
@ruheni 
I mean navigation button to all pages in the docs
like so:
![Screenshot](https://github.com/prisma/docs/assets/82659015/4ae43cb3-02d9-4a20-a43f-4ad961e634d6)

**Comment by 21stPhenom** [comment]
I totally agree with your suggestion @A7med3bdulBaset . I just came here to raise a similar issue, but i had to check if anyone had done so in the past. @ruheni There should be "Next" and "Previous" buttons at the end of each page on the documentation to allow easy navigation to the next and previous topics respectively.

At the moment, navigating those documents without these buttons is a hassle, as you have to scroll all the way up before selecting the next or previous  topic.

**Comment by meletj** [comment]
@AhmedBaset We recently updated our Docs, and they now include a "previous" and "next" button at the end of each page.
