### ISSUE TITLE
Add an option to create an "external link item" in the sidenav

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4877]
It would be great if in the sidenav, it was possible to add an "external link item" so that we can send people to external resources directly from the docs. 

More context in this internal [thread](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1686304966190199): 

<img width="481" alt="image" src="https://github.com/prisma/docs/assets/4058327/7e5a3916-3ec4-4eea-8bd1-88cdc943fe78">

**Comment by meletj** [comment]
See the experiment from Alex here: https://github.com/prisma/docs/pull/4817 with the examples projects. 
The ask would then be for the playground (as it is an external link).

**Comment by nilubava** [comment]
Blocked: Look into other options (maybe in Quickstart?) @meletj

**Comment by jharrell** [comment]
@nikolasburk still required?

**Comment by nikolasburk** [comment]
Def would be nice to have but in our efforts to clean up issues, I'll close this one for now.
