### ISSUE TITLE
TOC highlights first item in the case of large TopBlock paragraphs where headings are not displayed yet

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#4905]
Context: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1686595863282829

**Comment by carlagn** [comment]
Are we looking into adding the topBlock heading to our right-side TOC then? cc @nilubava @meletj @janpio

**Comment by janpio** [comment]
🤷 I just highlighted the problem. No idea what the solution is here, sorry.

**Comment by nilubava** [comment]
May need some design input for the chevron :)

**Comment by nilubava** [comment]
@meletj to review the PR

**Comment by nilubava** [comment]
How to remove highlight on the first toc item when it is scrolled up. @carlagn
