### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by thakursaurabh1998** [prisma/prisma2-docs#4920]
I am getting incorrect or missing password error because the @fortawesome packages being installed are part of a private registry `npm.fontawesome.com`.
If that's the case, how do I run the docs locally?

**Comment by ankur-arch** [comment]
I'm closing this issue as the FONTAWESOME required token has been removed from our docs, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
