### ISSUE TITLE
Bug: Inline code rendered in different font

### ISSUE THREAD

**Issue by meletj** [prisma/prisma2-docs#4923]
When using the docs I regularly have the visual problem that code being rendered with a different font:
(Windows, newest Chrome)

![image](https://github.com/prisma/docs/assets/70962362/fcf941d9-2d40-407d-acf4-fcfb632e4064)

Reported by @janpio

**Comment by nilubava** [comment]
Check after removal of tailwind from lens

**Comment by nilubava** [comment]
Related issue: #4995
