### ISSUE TITLE
SQL Server `Json` is documented, but does not exist

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#4935]
Confusion around about our Json support for SQL Server:

[prisma.io/docs/reference/api-reference/prisma-schema-reference#json](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#json)
[prisma.io/docs/reference/api-reference/prisma-schema-reference#microsoft-sql-server-7](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#microsoft-sql-server-7)

But:

https://github.com/prisma/prisma/issues/7417 (I confirmed this manually)
https://github.com/prisma/prisma/issues/6843
It seems to not actually be implemented.

Why do we document otherwise?
(Our SQL Server page is not helpful here: [prisma.io/docs/concepts/database-connectors/sql-server#type-mapping-between-microsoft-sql-server-to-prisma-schema](https://www.prisma.io/docs/concepts/database-connectors/sql-server#type-mapping-between-microsoft-sql-server-to-prisma-schema))

**Comment by fcablik** [comment]
It seems like this confusion is going on for a longer period of time.. Is there going to be an implementation of Json type support? Or should I get used to saving my Json data as text (string) in prisma?

**Comment by itpropro** [comment]
@janpio as JSON is natively supported in MSSQL for a while now (back to MSSQL 2016), will there be an update to Prisma?
https://learn.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver16

**Comment by jharrell** [comment]
@itpropro hey there! This is an issue around our documentation, not the engine of Prisma ORM. The issue around support for JSON in Prisma ORM can be found here: https://github.com/prisma/prisma/issues/7417

**Comment by itpropro** [comment]
> @itpropro hey there! This is an issue around our documentation, not the engine of Prisma ORM. The issue around support for JSON in Prisma ORM can be found here: [prisma/prisma#7417](https://github.com/prisma/prisma/issues/7417)

Thanks for your reply @jharrell, but that issue is already open for over 3 years and there doesn't seem to be a status on that. Any chance you or someone else from the prisma team can give a statement on the two most important MSSQL issues, which are Managed Identity/Token support (#13853) and JSON support (#7417)?
Thank you!

**Comment by jharrell** [comment]
@itpropro hi again!

Unfortunately, I don't have much information on those issues. I do not think they are planned for at least the coming quarter, perhaps longer.

**Comment by itpropro** [comment]
> @itpropro hi again!
> 
> Unfortunately, I don't have much information on those issues. I do not think they are planned for at least the coming quarter, perhaps longer.

That's quite sad to hear, but thanks for coming back anyway!
