### ISSUE TITLE
Create a resource that shows how to use Client extensions to implement a raw SQL query

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4947]
When a query isn't possible in the native Prisma Client API, users often need to use raw SQL. Thanks to PCEs, they can now create their own query methods on `PrisamClient` though that abstract away the SQL. We should provide an example of that (either in the docs or in the PCE examples repo).

**Comment by janpio** [comment]
We have a _lot_ of GH issues asking for specific APIs in Client that we do not have yet. Maybe we can use one/some of these as the example. (usually labelled with `topic: client api`)
