### ISSUE TITLE
Document behaviour of `OR` and whether the order of conditions matters

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4996]
This currently isn't documented and it's not clear whether the order should matter or not. In this case it led to confusion: https://github.com/prisma/prisma/discussions/19979

**Comment by janpio** [comment]
(We should actually reproduce and understand this, and decide if this is a bug in our query/command generation instead of something that needs to be documented)

**Comment by nikolasburk** [comment]
Yes, you're absolutely right! I created this issue during our Support sync yesterday and we said that before it gets documented, we should figure out whether it's a feature or a bug (and if it's a bug, then close this `docs` issue and create a new issue in `prisma/prisma` instead 👍 ) but I failed to add this to the issue — so thanks for adding it! 🙏
