### ISSUE TITLE
Remove deprecated rejectOnNotFound from docs

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#4999]
main/content/400-reference/200-api-reference/050-prisma-client-reference.mdx

**Comment by janpio** [comment]
Note: Definitely not remove, we only have 1 docs and majority of users will use an older Prisma in the beginning, and a lot of users will for a loooong time. Instead we need to de-emphasize it as much as possible. (Move lower, "legacy" page, maybe a collapsible `<details>` or something like that.) I am not sure if we have ever really removed anything and how we handled that.
