### ISSUE TITLE
Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.ts(2345)

### ISSUE THREAD

**Issue by jelmd** [prisma/prisma2-docs#5021]
Unfortunately the query log statement shown on https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging#event-based-logging is not typesafe - ts rejects it with `Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.ts(2345)`.

The page should include a variant, which can be used in typescript w/o any errors as well.

**Comment by nikelborm** [comment]
Might be fixed in https://github.com/prisma/prisma/pull/24133

**Comment by nikolasburk** [comment]
Hey there 👋 thanks a lot for opening this issue! I just tried to reproduce it with the snippet from the docs section you linked:

```ts
const prisma = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
    {
      emit: 'stdout',
      level: 'error',
    },
    {
      emit: 'stdout',
      level: 'info',
    },
    {
      emit: 'stdout',
      level: 'warn',
    },
  ],
});

prisma.$on('query', (e) => {
  console.log('Query: ' + e.query);
  console.log('Params: ' + e.params);
  console.log('Duration: ' + e.duration + 'ms');
});
```

However, I didn't see a type error in VS Code:

<img width="264" alt="image" src="https://github.com/user-attachments/assets/62fde60c-9c4b-45b7-9f7b-d18da43679d5">

I'm closing this issue as already resolved. In case you're still seeing this problem, feel free to re-open with more specifics about how I can reproduce the error.
