### ISSUE TITLE
Multi line headline with code formattext text has too little line-height

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5026]
This is how it looks right now:
<img width="403" alt="image" src="https://github.com/prisma/docs/assets/183673/0a0aba88-ae03-46f2-9c3f-cb538e31ce9b">

This is how it could look with some line-height:
<img width="374" alt="image" src="https://github.com/prisma/docs/assets/183673/a50e9638-3d56-4ef6-8858-e9183a47f774">

**Comment by meletj** [comment]
@carlagn looks similar to https://github.com/prisma/docs/issues/2870
