### ISSUE TITLE
Dismissing search results does not update URL

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5027]
https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing?query=alias&page=1#filter-groups-with-having

When you load this page you will have the search overlay (have to scroll up to actually see it).
When you dismiss the search overlay, the URL stays the same - which menas when you share it hey do not actually get the correct link with the anchor, but a search result.

**Comment by kuluruvineeth** [comment]
@janpio i would like to fix this, but i did not understand the issue, could you please add more details.
