### ISSUE TITLE
TOC with specified depth as summary on top of page

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#5031]
Suggestion from @janpio : A component that can render a table of contents of specific depth inside a page - 
Our right hand TOC is nice in some ways, but often it would help to also be able to give an overview inside the page similar to Notion's /table of contents

(One could for example use it to show all levels of headlines in a collapsed-by-default `<details>` to make things more discoverable)

Slack Message: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1686827052330789

**Comment by nikolasburk** [comment]
Closing as not planned 🙏
