### ISSUE TITLE
Accessibility issues in diff highlights

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma2-docs#5036]
When highlighting certain lines as removed or added in code snippets, they are only highlighted as red or green correspondingly, but there's no other indication except color. This poses a problem for people with color blindness, or with certain accessibility settings (e.g., I know some people who made their phone screens grayscale because they claimed it improved their sleep and reduced distractions).

As for colorblind users, here's an example of how the diff highlights look for users with deuteranopia (according to Firefox devtools):
![](https://user-images.githubusercontent.com/4923335/252628656-472147f7-28c3-48ab-a5b1-75ea1ba02f0c.png)

Additionally, it doesn't currently encode any information for screen readers for users with more serious vision impairments.

Color shouldn't be the only thing that conveys important information, there should be some explicit symbols like small `+` and `-` signs to the left.

**Comment by nilubava** [comment]
Blocked for future consideration

**Comment by ankur-arch** [comment]
Hey there 👋 , I'm closing this issue as it seems @aqrln's feedback has been incorporated into our updated [docs](https://www.prisma.io/docs/accelerate/caching#time-to-live-ttl) site.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/20946c2b-e405-4350-acd4-644965b683f1">
