### ISSUE TITLE
Line highlights break YAML code snippets

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma2-docs#5037]
When highlighting a line as "normal", "added" or "removed" in a code snippet, if the line contains a leading dash, it disappears. See examples:

<img width="685" alt="image" src="https://github.com/prisma/docs/assets/4923335/b3e48b34-241f-4b16-8419-8edf7b205f2e">
<img width="649" alt="image" src="https://github.com/prisma/docs/assets/4923335/f3df7a7b-7118-48b0-9265-d3cf5d041abe">

**Comment by janpio** [comment]
Example: https://github.com/prisma/docs/pull/5010/files#r1259673183

**Comment by nurul3101** [comment]
Closing as this issue is resolved
