### ISSUE TITLE
Clarify null / undefined

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5041]
How Prisma treats `undefined` is potentially dangerous: https://github.com/prisma/prisma/issues/20169
We have a page about it, but it is not very good: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined

We should fully understand what _is_, what that means, and what implications it has - and then make sure this documenation page covers all of it and explains it to users, including the potnetial danger.

**Comment by nikolasburk** [comment]
Same as #5135
