### ISSUE TITLE
Mention `_relevance` in fulltext search docs

### ISSUE THREAD

**Issue by joshribakoff-sm** [prisma/prisma2-docs#5045]
## Problem

Information about ranking search results is not surfaced in the docs for fulltext search here https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search

Instead it is fragmented and only documented here, not very discoverable.
(https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#sort-post-by-relevance-of-the-title)

## Suggested solution
The fulltext search docs should at least give a high level overview of all features related to fulltext search, even if it just links to other parts of the docs that better document each of the features. It is easy to falsely conclude that Prisma is not capable of basic search ranking (which makes fulltext search support in Prisma appear pretty useless to be frank, when in fact it is more useful and robust that the docs would seem to suggest)

**Comment by mohitmohlia** [comment]
@joshribakoff-sm can i work on this issue ? please guide me how to fix this

**Comment by miketromba** [comment]
> It is easy to falsely conclude that Prisma is not capable of basic search ranking (which makes fulltext search support in Prisma appear pretty useless to be frank, when in fact it is more useful and robust that the docs would seem to suggest)

I, too, came to this conclusion. It took a lot of digging to find this issue and realize that the `_relevance` feature exists.

**Comment by joshribakoff-sm** [comment]
@mohitmohlia  I am not a maintainer, don't know 🤷

**Comment by janpio** [comment]
If anyone wants to work on this and create a PR, please go ahead. The docs pages have "Edit this page" links on the bottom right, and the whole docs codebase is available at https://github.com/prisma/docs. Just make the changes and send a PR.
