### ISSUE TITLE
Document usage of `QUERY_BATCH_SIZE` for Postgres

### ISSUE THREAD

**Issue by huzaifahj** [prisma/prisma2-docs#5059]
## Problem

I bumped into the issue recorded here: https://github.com/prisma/prisma/discussions/7389

Due to the opaque error we get from Prisma from these connection issues (`ECONNREFUSED`), it would be good to document that, for PostgreSQL, setting this environment variable is helpful. Bonus points for detecting a query with many relations included (normally the root cause) and adding a note to the error message from Prisma Client?

**Comment by janpio** [comment]
You should not need to use this environment variable. If there is a problem that necessitates its use, please open a bug report issue so we can fix the underlying problem. Thanks.

**Comment by jkomyno** [comment]
Hi @huzaifahj, I agree with @janpio. Also, if you open a new issue, please be sure to use [this template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml) and to specify the version of Prisma you're running on and the exact steps to reproduce the problem you're facing. Thank you!

**Comment by ankur-arch** [comment]
Hey @huzaifahj  👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏. 

I'm closing this issue as we don't suggest using that environment variable to resolve connection issues. Usually, we recommend:
- To reuse PrismaClient instances if possible
- Use external connection poolers
- Increasing connection pool size

Here's a page with most of our suggestions and [details](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool) on this.
