### ISSUE TITLE
cuid safe maximum length

### ISSUE THREAD

**Issue by ghost** [prisma/prisma2-docs#5060]
In the cuid remarks sections, the docs say:

> Since the length of cuid() output is undefined per the cuid creator, a safe minimum field size is 30 characters, in order to allow for enough characters for very large values. If you set the minimum field size as less than 30, and then a larger value is generated by cuid(), you might see Prisma errors such as Error: The provided value for the column is too long for the column's type.

I believe the docs should say:

> Since the length of cuid() output is undefined per the cuid creator, a safe maximum field size is 30 characters, in order to allow for enough characters for very large values. If you set the maximum field size as less than 30, and then a larger value is generated by cuid(), you might see Prisma errors such as Error: The provided value for the column is too long for the column's type.

Notice where I've changed the word "minimum" to "maximum".

**Comment by ghost** [comment]
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#cuid

**Comment by janpio** [comment]
I think the "minimum" means that anything 30 or more works.
I think you want to express that the "maximum size" needs to be set to 30 at least.

Do I understand correctly?

**Comment by ghost** [comment]
Hey @janpio.

> I think the "minimum" means that anything 30 or more works.

I suppose that's correct, albeit confusing (to me, at least.) My brain interprets it as minimum maximum length.

> I think you want to express that the "maximum size" needs to be set to 30 at least.

I believe the paragraph intends to suggest a safe maximum length for cuid fields.

Couldn't it simply say: "Cuids can be as long as 30 characters, so a safe maximum length for cuid fields is 30 characters"?

Or we could delete the paragraph and state the maximum length of Prisma-generated cuids, leaving users with all the information they'll need should they want to enforce a maximum length constraint.

**Comment by janpio** [comment]
I opened a PR that just removed any usage of "minimum", and I think leaving out "maximum" as well is the best idea: https://github.com/prisma/docs/pull/5064
