### ISSUE TITLE
Add information on escaping connection strings to individual DB subpages

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5067]
follow up from #2750

**Comment by nikolasburk** [comment]
@jharrell just to confirm because the issue title isn't super clear:

This issue is about an explanation for how to _escape_ special characters in connection strings, right? And we need to document it for each DB connector (`mysql`, `postgresql`, ...) because it may work differently per DB?

**Comment by jharrell** [comment]
I think the issue is 
1. How to escape specific characters
2. which characters need to be escaped.

Both of these can differ per DB connector.
