### ISSUE TITLE
Document `by` shortuct for `groupBy`

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma2-docs#5082]
We've implemented shortcut for `by` argument of `groupBy` queries in prisma/prisma#20296. Now, if you want to group by a single field you don't need an array.

We need to document it. `groupBy` is documented on 2 pages:

- https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#group-by
- https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#groupby

**Comment by Jolg42** [comment]
Related to https://github.com/prisma/prisma/issues/20261
