### ISSUE TITLE
Document shorthand syntax for query options

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#5101]
Example shorthand syntax:
```ts
const groupUsers = await prisma.user.groupBy({
  by: 'city'
})
```

Alternative/ regular syntax:

```ts
const groupUsers = await prisma.user.groupBy({
  by: ['city']
})
```

TODO:

- [ ] Identify all shorthand & create a page that summarizes it
- [ ] Cleanup/ update pages that document query shorthand by linking to the new page

**Comment by nikolasburk** [comment]
Closing this as not planned 🙏
