### ISSUE TITLE
Confusing docs

### ISSUE THREAD

**Issue by willhackett** [prisma/prisma2-docs#5113]
There are a lot of docs condensed into this page, and one in particular is extremely important to subsequent functionality.

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#database-upsert-query-criteria

An `upsert` operation occurring that doesn't meet this criteria (which is easy to do accidentally without reading this) will result in conflicts in more complex systems.

This really needs to be clearer.

**Comment by nikolasburk** [comment]
Hey @willhackett 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏

> An `upsert` operation occurring that doesn't meet this criteria (which is easy to do accidentally without reading this) will result in conflicts in more complex systems.

Can you elaborate a bit more on that? What kind of conflicts are you referring to? Do you have a concrete suggestions what the docs should say here?

**Comment by nikolasburk** [comment]
I'm closing this issue due to lack of info. Feel free to re-open it with a specific request for what kind of information you'd like to see 🙏
