### ISSUE TITLE
Code block overflows when used in an admonition component

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#5114]
Example page: https://www.prisma.io/docs/concepts/database-connectors/sql-server

<img width="1214" alt="CleanShot 2023-07-31 at 15 15 14@2x" src="https://github.com/prisma/docs/assets/33921841/06729d32-fcd8-45f9-97b6-bb838a834ead">

**Comment by nilubava** [comment]
Fixed.
