### ISSUE TITLE
Fix transactions documentation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5123]
We have these pages supposed to document transactions
- https://www.prisma.io/docs/concepts/components/prisma-client/transactions
- https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide
- https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#transaction

It is really confusing how this is documented, especially between the first two links (and why the third does not actually contain any real documentation).

We should figure this out and clean it up, so that our users can actually understand Prisma transactions.

**Comment by nikolasburk** [comment]
Closing since we did a major restructuring of the docs last year that should have made this more clear 🙏
