### ISSUE TITLE
Exclude images from `list-changed-pages.yml`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5125]
https://github.com/prisma/docs/blob/main/.github/workflows/list-changed-pages.yml

Images are not super useful to check on the preview deployment, and also usually do not need to be redirected.
Example where this has negative effects that these are currently not filtered out: https://github.com/prisma/docs/pull/5117#issuecomment-1659041486

**Comment by nikolasburk** [comment]
@jharrell I believe this has been fixed with the re-implementation of the docs, right? If no, feel free to re-open this so we can take another look 🙏
