### ISSUE TITLE
Improved documentation about `undefined` behavior to be able to link to in issues

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5135]
https://github.com/prisma/prisma/issues/11718 is a good example where a user is (rightfully) confused, and instead of being able to link to an existing docs page @millsp wrote an extensive comment himself: https://github.com/prisma/prisma/issues/11718#issuecomment-1664813677

This `undefined` behavior is important enough that it should be 100% clear in a page called `undefined` and be linked to from the places where it is relevant (so in filters and so on).

**Comment by nikolasburk** [comment]
This should be covered by the `strictUndefinedChecks` preview feature and content on this page: https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/null-and-undefined#null-and-undefined-in-queries-that-affect-one-record
