### ISSUE TITLE
Links with multiple words are not broken into multiple lines because of `display: inline-block;`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5138]
https://docs-git-jharrell-issue5087-prisma.vercel.app/guides/deployment/serverless/deploy-to-aws-lambda
<img width="552" alt="image" src="https://github.com/prisma/docs/assets/183673/452f0ab9-ced3-4011-8c04-60317ae1687b">

Should be:
<img width="612" alt="image" src="https://github.com/prisma/docs/assets/183673/bca81d08-7d15-46b8-9db9-1adc17d8c4a7">

Achieved by disabling a style:
<img width="237" alt="image" src="https://github.com/prisma/docs/assets/183673/34f04e62-cf35-4930-ab18-a97feedae22f">

via https://github.com/prisma/docs/pull/5096

**Comment by nurul3101** [comment]
This seems to be resolved now.
