### ISSUE TITLE
Small improvements to Netlify guide

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5165]
### Explain binary target

I really like this section! The only info that I think we should add is what does `"rhel-openssl-1.0.x"` mean exactly?  A short inline explanation of what this value is, what it means and _why_ we need to put it there would be helpful I think.

<img width="547" alt="image" src="https://github.com/prisma/docs/assets/4058327/ad3bd18a-4a1f-4974-99d6-d9b8bcd8cadf">

### Fix terminal output

The code block is broken, the `DATABASE_URL ` and `postgresql://postgres:__PASSWORD__@__HOST__:__PORT__/__DB_NAME__ |` should probably be next to each other but instead are rendered with a line break.

<img width="556" alt="image" src="https://github.com/prisma/docs/assets/4058327/016ab197-1d53-4014-9baf-bae3feaabb1a">

**Comment by jharrell** [comment]
2nd issue was resolved by @nilubava. Thank you Nilu!

Explaining binaryTargets a bit more.
