### ISSUE TITLE
Client extensions: Use `prisma` as variable name and instantiate example code snippets using `new PrismaClient()`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5167]
https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions

For example, this code snippet:

```ts
const xprisma = prisma.$extends({
  name: `signUp`, // Optional: name appears in error logs
  model: {        // This is a `model` component
    user: { ... } // The extension logic for the `user` model goes inside the curly braces
  },
})
```

should be rewritten to:

```ts
const prisma = new PrismaClient().$extends({
  name: `signUp`, // Optional: name appears in error logs
  model: {        // This is a `model` component
    user: { ... } // The extension logic for the `user` model goes inside the curly braces
  },
})
```

or this one: 

```ts
// First of all, store your original Prisma Client in a variable as usual
const prisma = new PrismaClient()

// Declare an extended client that has an extensionA and extensionB
const prismaAB = prisma.$extends(extensionA).$extends(extensionB)
```

to:

```ts
// Declare an extended client that has an extensionA and extensionB
const prisma = new PrismaClient
  .$extends(extensionA)
  .$extends(extensionB)
```

**Comment by janpio** [comment]
Why?

(I agree, but wonder about your reasoning)

**Comment by nikolasburk** [comment]
Fundamentally it's about teaching our users "the right way of doing things"™️ and also the way that will most likely match what their actual setups look like.

In their setup, they'll most likely only want a single Prisma Client instance that they use throughout the app. If we teach them the `xprisma = prisma.$extends(...)` approach, they'll have two Prisma Client instances and there might arise confusion as to:
- when to use which instance
- connection management (because each instance has its own connection pool)

**Comment by janpio** [comment]
No new connection pool, it's the same engine: https://prisma-company.slack.com/archives/C043X6JBND6/p1692658459536809?thread_ts=1692657821.385329&cid=C043X6JBND6

But the "when to use which instance" is indeed valid and my motivation to agreeing.
(As long as the other use case is still explicitly documented)
