### ISSUE TITLE
Dark mode using darkreader: Minimal temp solution

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#5178]
Context: https://prisma-company.slack.com/archives/C05N11FHPK4/p1692255116934309

Use [darkreader](https://www.npmjs.com/package/darkreader) to implement a minimal effort dark mode on the docs pages.

Design work needed: 

- Code blocks bg
- Toggle switch
- icons in homepage + github icon in navbar

**Comment by jharrell** [comment]
@nilubava is this resolved by the new dark mode release?
