### ISSUE TITLE
Layout Bug: Cookie bar buttons aren't on the same line

### ISSUE THREAD

**Issue by DavidHancu** [prisma/prisma2-docs#5180]
![image](https://github.com/prisma/docs/assets/68247375/3e38da30-db92-4edd-a10b-857bdfdc3fb7)

**Comment by kuluruvineeth** [comment]
- Looks Like issue is fixed, as it is not reproducible
<img width="1435" alt="Screenshot 2023-08-20 at 6 52 35 PM" src="https://github.com/prisma/docs/assets/47528651/3dec7bef-4641-4b0b-8bc6-936a3cd629ec">
