### ISSUE TITLE
Update PDP docs to account for new `--no-engine` client option

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5185]
In 5.2, we are releasing a `--no-engine` option for Prisma Client. In addition, the correct engine to use will be inferred from the connection string (`prisma://` is routed to PDP, `postgres://` is routed to a library engine, etc)

We should update our PDP documentation to show that `--accelerate` and `--data-proxy` are no longer needed, but `--no-engine` can help reduce deployed app size.

**Comment by ankur-arch** [comment]
[Closing](https://www.prisma.io/docs/orm/reference/prisma-cli-reference#options-1) as it already exists.
