### ISSUE TITLE
Update references to `rhel-openssl` engine with explanation

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5186]
When we ask our users to add `rhel-openssl-1.0.x` to `binaryTargets` we should explain what that means.

**Comment by nikolasburk** [comment]
Does this refer to a specific part of the docs, @jharrell ?

**Comment by jharrell** [comment]
@nikolasburk I don't remember but I suspect this is in regards to the Lambda docs

**Comment by nikolasburk** [comment]
Thanks, makes sense! I found this [section](https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-aws-lambda#define-binary-targets-in-prisma-schema) in the docs: 

<img width="551" alt="image" src="https://github.com/user-attachments/assets/2de128e1-0fe4-4286-b599-8566159d82e9">

What additional information do you think would be useful here?
