### ISSUE TITLE
Aggregate API reference options list and reference types do not match

### ISSUE THREAD

**Issue by yaroslavkrutiak** [prisma/prisma2-docs#5194]
[https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#aggregate](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#aggregate) options list and reference types should be the same. Otherwise, it leads to misunderstandings

**Comment by nikolasburk** [comment]
Hey @yaroslavkrutiak 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏

It seems like this has been resolved by now, so I'm closing this issue, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
