### ISSUE TITLE
Add Amplication to the Real-world & production-ready example projects with Prisma

### ISSUE THREAD

**Issue by souravjain540** [prisma/prisma2-docs#5219]
There is a list of Real-world & production-ready example projects with Prisma on the doc's site.

[Amplication](https://amplication.com) is a good example to add.

**Comment by nurul3101** [comment]
@souravjain540 I would recommend adding a PR in our prisma-examples repository 🙏 

https://github.com/prisma/prisma-examples?tab=readme-ov-file#real-world--production-ready-example-projects-with-prisma
