### ISSUE TITLE
Add more typecasting examples for `$queryRaw`/`$executeRaw`

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma2-docs#5222]
Since 4.x, when using raw queries, we require type casts to appropriate types in certain cases. Our [docs page on this](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#postgresql-typecasting-fixes) mention only a simple case and we have users confussed about more [complicated cases](https://github.com/prisma/prisma/issues/14978).

We should improve our docs and provide at least couple of examples for `IN`/`Prisma.join` queries. Both soltions  [here](https://github.com/prisma/prisma/issues/14978#issuecomment-1246753681) and [here](https://github.com/prisma/prisma/issues/14978#issuecomment-1307766093)  work for this case.

**Comment by nikolasburk** [comment]
We should understand how typecasting plays with TypedSQL, and if still relevant, tackle this issue.

**Comment by nikolasburk** [comment]
Closing this as not planned 🙏
