### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by LionyxML** [prisma/prisma2-docs#5243]
It looks like in this file from docs:
https://github.com/prisma/docs/blob/e05fed7d5839bba2eb9b31938d5a22d2b7c6d9cd/content/300-guides/500-other/880-troubleshooting-orm/100-help-articles/400-nextjs-prisma-client-dev-practices.mdx#L36

it should've been:
```ts
const prisma = globalForPrisma.prisma ?? prismaClientSingleton()
```

**Comment by ruheni** [comment]
Yes. It seems so. I'll go ahead and fix it! Thanks for raising this.
