### ISSUE TITLE
Migration history conflicts

### ISSUE THREAD

**Issue by w1zart** [prisma/prisma2-docs#5244]
In the 'Migration troubleshooting in production' docs (https://www.prisma.io/docs/guides/migrate/production-troubleshooting#migration-history-conflicts) it's said that `prisma migrate deploy` issues a warning if an already applied migration has been edited. However, the warning doesn't seem to be shown anywhere. 
Did I misunderstand something, or maybe should enable some special log level?

**Comment by ruheni** [comment]
Thanks for raising the question. I've tried it out and can confirm that `prisma migrate deploy` didn't return any warning. I've forwarded this question to our engineering team and will get back to you on this once I get a response 🙂

**Comment by Jolg42** [comment]
So we stopped warning with https://github.com/prisma/prisma/pull/12381, issue is https://github.com/prisma/prisma/issues/9829
Since `3.12.0`

We only surface an edited migration in migrate dev with this log now
`The migration `date_name` was modified after it was applied.`

**Comment by w1zart** [comment]
Thank you for such a quick response and action!
