### ISSUE TITLE
"Database Features Matrix" in homepage not linked to any page

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#5283]
https://www.prisma.io/docs/reference/database-reference/database-features

https://www.figma.com/file/aTK3UuDkVlld0G1q0ik9fw/Docs-Website?type=design&node-id=2102-1679&mode=design&t=KburZ5ZLKDIKn9Wz-0

**Comment by meletj** [comment]
This page https://www.prisma.io/docs/orm/reference/database-features should be linked from the 'Database feature matrix' text on prisma.io/docs 
<img width="1299" alt="Screenshot 2024-04-24 at 21 00 06" src="https://github.com/prisma/docs/assets/70962362/03dfe3eb-244f-4f91-bc21-9231bd106dd9">
