### ISSUE TITLE
Error reference improvement — Provide high level error names for the codes

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#5284]
Example error code + name
```ts
P1000 — IncorrectDatabaseCredentials
```

Source: https://github.com/prisma/prisma-engines/blob/main/libs/user-facing-errors/src/common.rs

[Internal thread](https://prisma-company.slack.com/archives/C4GCG53BP/p1693997028882629)

**Comment by nikolasburk** [comment]
Closing as not planned 🙏
