### ISSUE TITLE
Dark theme breaks some code highlights

### ISSUE THREAD

**Issue by Adomas-Alimas** [prisma/prisma2-docs#5285]
Hi, 

awesome to have a dark theme in docs but currently there is an issue with some of the highlighted code examples because the highlight ant text colour is the same.

One of the page examples: 
https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination

Here are the screenshots of how the highlights look:
<img width="743" alt="Screenshot 2023-09-06 at 16 26 09" src="https://github.com/prisma/docs/assets/39675293/c342b1ca-0210-4877-a3fe-64ca3674cd92">

If I select the highlighted code I can see it:
<img width="743" alt="Screenshot 2023-09-06 at 16 28 02" src="https://github.com/prisma/docs/assets/39675293/7fdaa9ec-765f-4be3-a707-d5e58774063a">

**Comment by jharrell** [comment]
@Adomas-Alimas I believe this should now be resolved. Could you check?

**Comment by Adomas-Alimas** [comment]
Yup, looks great!
