### ISSUE TITLE
Update Accelerate docs and instruct to opt-out of Next.js caching

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5312]
Add a note under:
- https://www.prisma.io/docs/data-platform/accelerate/current-limitations
- https://www.prisma.io/docs/data-platform/accelerate/faq
- https://www.prisma.io/docs/data-platform/accelerate/getting-started#prerequisites

**Comment by ankur-arch** [comment]
@nikolasburk here's an update on this and I think we can close this. 
My initial understanding of Accelerate not being affected by Next.js caching has been correct.

As `PrismaClient` is used in the API route handler and Accelerate uses a POST request, requests are not automatically cached. Read more [here](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#caching-data). 

> Next.js caches all fetch requests using GET and POST requests on the client, and it doesn't automatically cache POST requests on the server (API route handlers) 

![image](https://github.com/prisma/docs/assets/64993082/01faec15-a4ac-4fb9-9eb9-9601110caacd)

**Comment by nikolasburk** [comment]
Got it, thanks!
