### ISSUE TITLE
Algolia: Code examples are not indexed

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#5322]
Missing search results:
<https://www.prisma.io/docs?page=1&amp;query=_min> (1 page) vs. <https://github.com/search?q=repo%3Aprisma%2Fdocs%20_min&amp;type=code> (2 pages)
Seems code examples are not indexed.

[Slack Message](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1695020408261459)

**Comment by ankur-arch** [comment]
Closing this as this seems to be outdated.
