### ISSUE TITLE
Theme Switch

### ISSUE THREAD

**Issue by dennemark** [prisma/prisma2-docs#5323]
Hi,

Prisma docs dark mode is great! But right now sun is shining on my screen and its difficult to read 🙈. I could not find a theme switch though... 😅
If its not a big issue, maybe its nice to add a button next to the github link on upper right

**Comment by meletj** [comment]
@dennemark We've recently added a Dark/Light mode button, so you switch as you please. 🌚

**Comment by dennemark** [comment]
Haha so nice, works awesome! New docs look great! Now I just need to wait for some sun to have a reason to switch the theme 😅
