### ISSUE TITLE
code blocks on iPhone8 looks bigger

### ISSUE THREAD

**Issue by nilubava** [prisma/prisma2-docs#5328]
iPhone 8 has weird code block font size. Check out any page with code blocks

Slack conv: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1694780554736299

**Comment by nilubava** [comment]
Test browserstack devices to see which version it happens.

**Comment by nikolasburk** [comment]
@nilubava do you know by any chance (or have a quick way of checking) if this is still an issue?

**Comment by gniting** [comment]
Relates to reading code blocks on a phone. Not a priority for now.
