### ISSUE TITLE
fix: Broken link in deployment guide

### ISSUE THREAD

**Issue by jshikanova** [prisma/prisma2-docs#5333]
Broken link in this section of the docs https://www.prisma.io/docs/guides/deployment/caveats-when-deploying-to-aws-platforms#deleting-prisma-engines-that-are-not-required

Exact line - https://github.com/prisma/docs/blob/d336c33cb9357767b30cba96c1be088063eaaa2f/content/300-guides/200-deployment/650-caveats-when-deploying-to-aws-platforms.mdx#L55

I'm not sure, but possible working link may be this one: https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless/lambda/zip.sh

**Comment by janpio** [comment]
Probably now part of a script, e.g. https://github.com/prisma/ecosystem-tests/blob/13e74dc47eababa5d3c8f488b73fe7fc8bffead7/platforms-serverless/lambda/run.sh#L16
