### ISSUE TITLE
Document how to use `allModels` with result extensions

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#5341]
Internal thread: https://prisma-company.slack.com/archives/C043X6JBND6/p1695035021464319

Related GH issue: https://github.com/prisma/prisma/issues/17512#issuecomment-1722919548

**Comment by nikolasburk** [comment]
We have documented how to use `$allModels` here: https://www.prisma.io/docs/orm/prisma-client/client-extensions/model#add-a-custom-method-to-all-models-in-your-schema
