### ISSUE TITLE
Sections in code unreadable in darkmode

### ISSUE THREAD

**Issue by ankur-arch** [prisma/prisma2-docs#5376]
1. https://www.prisma.io/docs/guides/deployment/edge/deploy-to-deno-deploy#steps

<img width="729" alt="image" src="https://github.com/prisma/docs/assets/64993082/c70e05f4-46e9-4c73-bcb5-9981c7544e99">

**Comment by nikolasburk** [comment]
I assume this has been fixed by now. If not, feel free to re-open the issue @ankur-arch 🙏
