### ISSUE TITLE
Docs code snippet not working; Invalid `prisma.product.create()` invocation, Error validating datasource

### ISSUE THREAD

**Issue by ayushsgithub** [prisma/prisma2-docs#5390]
This is the code snippet from [docs](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices) is giving errors and I couldn't figure it out how to solve it.
![Screenshot 2023-10-23 125832](https://github.com/prisma/docs/assets/120788538/a62e0749-eedc-46af-93cf-2e6a5cef1aa6)
See this instantiating:
![Screenshot 2023-10-23 130027](https://github.com/prisma/docs/assets/120788538/808b4abf-a308-4626-ba7c-fee5278d47b1)
And the error:
![Screenshot 2023-10-23 130141](https://github.com/prisma/docs/assets/120788538/800b1571-1e2e-464a-b8bd-39cf6f965e61)

**Comment by nikolasburk** [comment]
Hey there 👋 the issue seems to be related to the wrong connection URL being used. I'm closing this issue because it's unrelated to the actual content of the docs 🙏  please feel free to open other issues in the future.
