### ISSUE TITLE
Add logos to more database guides

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5423]
This is cool:
<img width="540" alt="image" src="https://github.com/prisma/docs/assets/183673/a04013b1-feda-4796-b8d8-d64d9a4e2fe1">
<img width="562" alt="image" src="https://github.com/prisma/docs/assets/183673/6e89f0a7-ca00-4352-98fd-c00a888ed16d">

Let's do that for more of these guides:
<img width="175" alt="image" src="https://github.com/prisma/docs/assets/183673/f43b4a14-2cad-4de7-847d-87a7ed076e14">

**Comment by nikolasburk** [comment]
Closing as not planned 🙏
