### ISSUE TITLE
Must the CI/CD modify a running database on production/dev/etc environment?

### ISSUE THREAD

**Issue by lfdominguez** [prisma/prisma2-docs#5425]
https://github.com/prisma/docs/blob/334d8e61c7073b986d7a7886d274b6887f1b8ad5/content/300-guides/200-deployment/550-deploy-database-changes-with-prisma-migrate.mdx#L9

I think that this is a bad advice, because the database migrations must be done on runtime. If you use the build time for this:
1 - The database must be public available to the agent of the CI/CD
or 2 - If not public, must be done with a VPN
or 3 - The CI/CD agent must be deployed where can access to the database
or 4 - I think that the build process of an app can't modify in any aspect the deployed environment.

**Comment by lfdominguez** [comment]
I think that must specify that is on Delivery time, not include the CI part.

**Comment by nikolasburk** [comment]
Hey Luis 👋 thanks for opeining this issue! I'm aware that the issue has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏 

> I think that this is a bad advice, because the database migrations must be done on runtime. 

I just double-checked internally and our Engineering team and it doesn't seem like we want to recommend migrations as a best practice. Here's the reasoning from one of our engineers:

> It's unclear what the app should do if the migrations fail. Does it start anyway or fail to start, causing an outage?
> What happens if multiple app versions are active at once with different stages of schema evolution?
> Separating into CI forces you to consider that the app must be backwards or forwards compatible since the migrations must be run as a separate step before or after app deployment. This is critical in the event migrations fail for any reason and gives you more confidence in how you can safely roll back. Coupling it with a runtime deployment usually leads to devs assuming that everything will work perfectly and they'll never need to roll back their app.

I'm closing this issue, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
