### ISSUE TITLE
Text does not line break

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5428]
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#mongodb
<img width="535" alt="image" src="https://github.com/prisma/docs/assets/183673/960054ac-a6b8-4179-bbb2-08b054911532">

That links does not fully need to be in a new line.

**Comment by jharrell** [comment]
As of the migration to Docusaurus, this is resolved.
