### ISSUE TITLE
Custom image component for use in MDX

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma2-docs#5433]
We'd like to have a custom image component which we could define custom styling for alignment like we do on this page. The regular img HTML tag

<img src="https://uploads.linear.app/174abb15-118d-4cd8-8b3f-b48a9aacdbf8/a6b04b23-3965-4320-8c0b-0b1691490c82/1288eabf-a9bf-4dcd-9a52-42963472a1f4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE3NGFiYjE1LTExOGQtNGNkOC04YjNmLWI0OGE5YWFjZGJmOC9hNmIwNGIyMy0zOTY1LTQzMjAtOGMwYi0wYjE2OTE0OTBjODIvMTI4OGVhYmYtYTliZi00ZGNkLTlhNTItNDI5NjM0NzJhMWY0IiwiaWF0IjoxNzI1NDM0OTk3LCJleHAiOjMzMjk1OTk0OTk3fQ.OpBzOKHzydiuBxIQXvOS-Iqg6GeU9xJNOK3uUvg-aec " alt="image.png" width="719" height="341" />

**Comment by nilubava** [comment]
@ruheni Could you please elaborate on how this component should be? Use the issue template if needed

**Comment by ruheni** [comment]
We'd like to have a custom image component which we could define custom styling for alignment like we do on this page. The regular img HTML tag

![image](https://github.com/prisma/docs/assets/33921841/9958aa95-7728-48c8-bfd5-ab37555ecf79)


Context on the Slack thread
![CleanShot 2023-11-14 at 15 25 28@2x](https://github.com/prisma/docs/assets/33921841/226055ea-2161-4b45-b2cd-86b40da3f4bc)
doesn't render correctly on first load.

**Comment by nikolasburk** [comment]
Closing this as not planned since no real use cases for this came up besides the Turso logo, which I'm also [suggesting](https://github.com/prisma/docs/pull/6421) to remove from the docs now to keep the page a bit cleaner:

<img width="557" alt="image" src="https://github.com/user-attachments/assets/a0b0ace7-0c7a-4078-8ec9-1a4423a6379a">
