### ISSUE TITLE
[DEV-14] Create docs for SafeQL + extensions

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5435]
Aimed at explaining PostGIS

<sub>From [SyncLinear.com](https://synclinear.com) | [DEV-14](https://linear.app/prisma-company/issue/DEV-14/create-docs-for-safeql-extensions)</sub>

**Comment by jharrell** [comment]
This is a test

**Comment by nikolasburk** [comment]
@jharrell this doesn't seem to be a "real" issue asking for some docs changes, right? I'm closing it, feel free to re-open if you think this was a mistake 🙏
