### ISSUE TITLE
Fix wrong `Date` scalar type mentioned in the MongoDB native type mapping

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5483]
See this discussion: https://github.com/prisma/prisma/discussions/21911

**Comment by janpio** [comment]
Part of https://github.com/prisma/docs/pull/5446/

**Comment by nikolasburk** [comment]
Seems like this has been resolved already: 

<img width="332" alt="image" src="https://github.com/user-attachments/assets/e89aefab-a1fa-416f-8d83-925530315c54">
