### ISSUE TITLE
Doc search UI element is very slow

### ISSUE THREAD

**Issue by olivierlacan** [prisma/prisma2-docs#5485]
At first I thought this may be a Safari-specific issue (although that'd be a little surprising) but the search feature on the doc site is very slow in my experience over the past few weeks. My teammate @ktlpro has experienced the same issues in Firefox.

I frequently: 
- open the search with `/`, start typing, and no input occurs (no focus event on the field)
- click on the search input, and it instantly loses focus
- when the search input is focused (and expanded), I start typing a search term only to have it disappear on type as autocompletion results stream in
- when results have appeared, scrolling leads to the entire expanded search result view to disappear although it hasn't reset, it's just hidden and thankfully reappears with the previous state

More rarely: 
- when clicking on results, I'm occasionally taken to a page that seems entirely unrelated to the search term or result I was shown. That one's harder to reproduce.  

These issues hinder the experience of searching the excellent Prisma docs enough that I end up relying more on search engine results than the in-app search. While that's fine the weighing of the full-text search is useful so I'd recommend prioritizing improvements here.

**Comment by meletj** [comment]
@olivierlacan Thank you for raising this issue. We've recently made some updates to our search and I'd love to know if you're still experiencing the same issues.

**Comment by nikolasburk** [comment]
Hey @olivierlacan 🙌  since our re-implementation of the docs site using Docusauros, the UX issues you've mentioned should've been fixed.

> when clicking on results, I'm occasionally taken to a page that seems entirely unrelated to the search term or result I was shown. That one's harder to reproduce.

We're aware that the search results aren't always ideal and are planning to tackle this soon, thanks for pointing this out as well!

I'm closing this issue as "already fixed", feel free to open another one with other specific problems about search (or our docs in general)in the future 🙏
