### ISSUE TITLE
Document how to correctly use `@default` for JSON columns

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma2-docs#5494]
JSON values in `@default()` should be quoted:

```prisma
history Json @default("[]")
```

See prisma/prisma#22063.

That makes sense with the way JSON is handled one the engine side, however, for TS users this is not as obvious, as they always receive JSON as a parsed values. I haven't found explicit mention of this in either JSON or `@default` documentation.

**Comment by applemate** [comment]
I tried this, and the default value still null. Not the array we wanted.

**Comment by nikolasburk** [comment]
Created the PR for this here: https://github.com/prisma/docs/pull/6121
