### ISSUE TITLE
Is the linked cuid spec up to date and correct? Or has the selected implementation been changed?

### ISSUE THREAD

**Issue by bambery** [prisma/prisma2-docs#5516]
On the page https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#cuid
the ["cuid spec" which is linked to was deprecated](https://github.com/paralleldrive/cuid) at the start of 2023 for security reasons, which [can be confirmed on the NPM page for this package](https://www.npmjs.com/package/cuid).

Is the information in the doc still correct, that the old, known-insecure spec is still being used? I poked around in the repos for a few minutes and found apparently mixed results.

I found one package.json claiming to use cuid 3.0.0 (the deprecated one):
https://github.com/prisma/prisma-client-extensions/blob/4b7fe4549121a8d1eb73499230f84dd1b91733ba/model-filters/package.json

But according to ["data model" doc](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model): "Use a Prisma-level function. For example, `cuid()` and `uuid()` are provided by Prisma's [query engine](/concepts/components/prisma-engines/query-engine) for all connectors." 
And this appears to be using another implementation, which depends on the cuid2 library
https://github.com/prisma/prisma-engines/blob/f2e5886144b9dcd9774a6799317e94d76904001a/Cargo.lock#L874

I have already hit my max time on researching this issue, but it would be nice to have clarification.

**Comment by nikolasburk** [comment]
Hey @bambery 👋 

> Is the information in the doc still correct, that the old, known-insecure spec is still being used?

Yes, that information is still accurate.

The `cuid()` function has not been updated yet to use `cuid2`.

I hope this helps, let us know if you have further questions or think that we should clarify our documentation 🙏
