### ISSUE TITLE
Get Started: Parts of example code aren't properly visible in dark mode

### ISSUE THREAD

**Issue by iamashay** [prisma/prisma2-docs#5521]
In the Getting Started section, I found a lot of examples where some parts of the code weren't noticeable because of font colour and the background. Everything seems fine in Light mode, the problem is when I have the Dark mode turned on.

The 'user' property isn't visible in Dark Mode. I thought it was a blank space until I selected the text. 

## Start From Scratch/Relational Database:

![image](https://github.com/prisma/docs/assets/7845033/a0e0f438-625a-4e01-8adc-22d67076071f)
Link: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/querying-the-database-typescript-postgresql#write-your-first-query-with-prisma-client

![image](https://github.com/prisma/docs/assets/7845033/e72f25a8-a196-438d-af9c-1210d4c5b9e3)
Link: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/querying-the-database-typescript-postgresql#write-data-into-the-database

## Start From Scratch/MongoDB:
'allUsers' also has a bad styling here.
![image](https://github.com/prisma/docs/assets/7845033/6c3708df-34a0-4b06-9cb4-4b166abdb78e)

Link: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/querying-the-database-typescript-mongodb#write-your-first-query-with-prisma-client

**Comment by meletj** [comment]
@iamashay Thanks again for flagging up these issues. We have pushed some improvements earlier this year to our dark mode and these readability issues are now fixed 😃
