### ISSUE TITLE
Update nav bar 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5527]
As shown in the design Preview: https://www.notion.so/prismaio/Docs-nav-bar-8d99cfd7d9c748e6bd1b169e648f231f?pvs=4

![image](https://github.com/prisma/docs/assets/4058327/9f4b8d4b-4f55-4178-94d8-2275cb834c3e)

```[tasklist]
### Tasks
```

**Comment by meletj** [comment]
See design in figma: https://www.figma.com/file/aTK3UuDkVlld0G1q0ik9fw/Docs-Website?type=design&node-id=1565-2815&mode=design&t=h361GjiCRaCSUjH1-4

Changes: 
- left align navigation
- add login button going to console
