### ISSUE TITLE
Documentation about connection pool timeout misleading

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5535]
> The default connection pool timeout is 10 seconds. If the query engine does not process a particular query within that time, it throws an exception and moves on to the next query in the queue.

This is incorrect. The connection pool timeout includes fetching a connection from the pool, not the processing of the query.

Here is a more correct statement:

> The default connection pool timeout is 10 seconds. If the query engine does not get a connection from the connection pool within that time, it throws an exception and moves on to the next query in the queue.

**Comment by janpio** [comment]
The "more correct" statement is not correct at all.
