### ISSUE TITLE
Confusing Text for extensions

### ISSUE THREAD

**Issue by sakgoyal** [prisma/prisma2-docs#5551]
This is quite confusing. Can this be re-written to be more clear please?
https://www.prisma.io/docs/orm/prisma-client/client-extensions/model
![image](https://github.com/prisma/docs/assets/19929553/d94ffcd4-38e6-4403-848d-9986a5d891ab)

**Comment by nikolasburk** [comment]
Thanks for raising this @sakgoyal 🙌  this was also brought up in #5621 and was just fixed via #6401
