### ISSUE TITLE
Developer freindly Doc for solving Error when running prisma+mongodb with connection string with no database name

### ISSUE THREAD

**Issue by Osmanity** [prisma/prisma2-docs#5562]
### Bug description

HI, Im integrating prisma & mongodb and got a problem when following the documentation [here](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/connect-your-database-typescript-mongodb), for more developer friendly experience doc, it would be helpful to update it, see the image included for how

### How to reproduce

1. Go to Doc guide for set up prisma + mognodb, [here](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/connect-your-database-typescript-mongodb)
2. Follow the step-by-step guide for integrating Prisma into your project.
3. Start by creating a basic database cluster on MongoDB.
4. Access the Atlas dashboard for MongoDB management.
5. Navigate to the 'Database' tab.
6. Establish a connection to the database using the provided drivers.
7. Incorporate the database connection string into your application's code.
8. ![prisma_doc](https://github.com/prisma/prisma/assets/83875991/507f8bf8-e076-463b-b370-f08a7c4da422) Note that MongoDB Atlas generates an environment link which, crucially, lacks the database name.  generate env link without the Database name
9. Commonly, users copy the provided MongoDB environment key directly into their project's .env file, assuming it is complete.
10. The error message displayed is: "
```
Error: 
Invalid prisma.blog.findMany() invocation: Raw query failed. Code: unknown. Message: Kind: Command failed: Error code 8000 (AtlasError): empty database name not allowed.
```

### Expected behavior

To enhance the developer-friendly aspect of prisma documentation, it would be beneficial to add a concise, highlighted notice, perhaps with an exclamation mark, advising developers to include the database name when copying the environment variable for the MongoDB URL link. This addition would significantly improve the clarity and usability of prisma documentation, see image for where the information could be placed:
![prisma_doc_2](https://github.com/prisma/prisma/assets/83875991/5e88ab43-61b9-4616-9765-cbcbe9965844)

### Prisma information

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
...

### Environment & setup

- OS: Windows, win32, x64
- 
- Database: MongoDB 
- Node.js version: v18.18.2

### Prisma Version

  Prsima: 5.7.1

**Comment by ademondev** [comment]
I just had the exact same problem, you see different things in the prisma docs and mongodb actual connection url. It's not highlighted enough

**Comment by rajojon23** [comment]
I faced the same issue, but I think this can easily be avoided by just making the error and its root cause a bit clearer.

**Comment by ecomerciostore** [comment]
same error here? any solution yet?

[Nest] 58923  - 06/22/2024, 12:14:30 AM   ERROR [GroupsActions] Object:
{
  "status": "error",
  "message": {
    "name": "PrismaClientKnownRequestError",
    "code": "P2010",
    "clientVersion": "5.15.1",
    "meta": {
      "modelName": "Groups",
      "code": "unknown",
      "message": "Kind: Command failed: Error code 8000 (AtlasError): empty database name not allowed\n\tat 0923b1cc06b679cdd24cd1891486c2fb/atlasproxy/session_proxy.go:741\n\tat 0923b1cc06b679cdd24cd1891486c2fb/atlasproxy/session_proxy.go:1656\n\tat 0923b1cc06b679cdd24cd1891486c2fb/atlasproxy/session_proxy.go:1228\n\tat 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/proxy_session.go:369\n\tat 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/proxy_session.go:118\n\tat 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/session.go:220\n\tat 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/server.go:384\n\tat src/runtime/asm_arm64.s:1197, labels: {}"
    }
  },
  "data": null,
  "action": "groups-setup-error"
}

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "null".

**Comment by ecomerciostore** [comment]
I just found here, when create a mongodb atlas, they do not give us a fully url connector, the database is not set
so we need to added the database name in the url connector like

`mongodb+srv........mongodb.net/DATABASE_NAME?retry,,,,,,,`

solved.

**Comment by dima8528** [comment]
> Я только что нашел здесь: при создании атласа mongodb они не предоставляют нам полный URL-коннектор, база данных не установлена, поэтому нам нужно добавить имя базы данных в URL-коннектор, например
> 
> `mongodb+srv........mongodb.net/DATABASE_NAME?retry,,,,,,,`
> 
> решено.

Спасибо, помогло

**Comment by rafael-bit** [comment]
Try updating your database password and try again, this error is classic in mongoDB

**Comment by shaishab316** [comment]
its simple, mongodb atlas design just to connect a connection poll, 
mongodb native npm package first connect this poll, then poll.getDB(database_name).getCollection() like this.
but in monogoose the get database form connection url. like this prisma also infer database name form database url, 

so,, first copy mongodb atlas connection string, then add a path its a database name/,, eg: mongodb+srv://........mongodb.net/[DATABASE_NAME]

its not a bug, you need to know the concept.
