### ISSUE TITLE
Strange rendering of "What this helpful?"-section

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5571]
I was seeing a strange UI issue where on first load of (some?) docs pages the “Was this helpful?” section is weirdly expanded. 

A reload fixed it. 

This was on `Chrome Version 120.0.6099.129 (Official Build) (x86_64)`.

![image](https://github.com/prisma/docs/assets/4058327/b7f5b290-1596-4fd4-aac1-235333b349c9)

**Comment by meletj** [comment]
Marking as stale as we removed the 'Was it helpful' widget.
