### ISSUE TITLE
Scroll Restoration

### ISSUE THREAD

**Issue by broisnischal** [prisma/prisma2-docs#5572]
Whenever I try to read through the docs when I click the next topic when being scrolled at the bottom from sidebar, it automatically scrolls me up with no reason!

**Comment by nikolasburk** [comment]
Hey @broisnischal 👋  we recently rewrote our docs and I believe this should be fixed now (I couldn't reproduce it in Chrome `Version 130.0.6723.92 (Official Build) (x86_64)`)! 

If you still encounter this problem, please feel free to re-open the issue and also share with us which browser you're using 🙏
