### ISSUE TITLE
Strange rendering of a hyperlinked sentence

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5574]
The highlighted sentence [here](https://www.prisma.io/docs/orm/prisma-client/deployment/caveats-when-deploying-to-aws-platforms#aws-rds-proxy) is center-aligned but it's not clear why:

<img width="418" alt="image" src="https://github.com/prisma/docs/assets/4058327/50327388-637d-4463-ba30-aef2b5cb5ed9">

Here is the source for it:

https://github.com/prisma/docs/blob/main/content/200-orm/200-prisma-client/500-deployment/650-caveats-when-deploying-to-aws-platforms.mdx#L19

**Comment by janpio** [comment]
Might be related to this: https://github.com/prisma/docs/issues/5582

**Comment by meletj** [comment]
Not sure it's related to #5582 as the links are now implemented as <a> tags and that link still looks odd.

**Comment by janpio** [comment]
Looks as expected to me now: 
<img width="866" alt="image" src="https://github.com/prisma/docs/assets/183673/ae410c00-a2e8-4ac3-9c58-99ed5f634bd4">
