### ISSUE TITLE
External links are <button> rather than <a>

### ISSUE THREAD

**Issue by aaroncowie** [prisma/prisma2-docs#5582]
External links being implemented with `<button>` elements rather than `<a>` elements results in unintuitive browser behaviour.

<img width="1058" alt="image" src="https://github.com/prisma/docs/assets/3691615/66f26088-026f-4cfb-b38d-599ba1d14b00">

compared to

<img width="1058" alt="image" src="https://github.com/prisma/docs/assets/3691615/ba6c16cd-6dab-46db-8768-b518acae91f4">

This makes it hard to "open in new tab" external links.

I am aware that this is technically unneccessary since that is the default behaviour, however it forces additional mental load on the user to distinguish between internal and external links before clicking.

This also means that command-click on mac or ctrl-click on windows does not work for these links which creates a very confusing experience

**Comment by Tejs1** [comment]
Yes I tried My mouse middle button to open link in new tab And It didn't work. After inspecting It is html `<button/>` rather than html `<a/>`  tag
![image](https://github.com/prisma/docs/assets/67797070/35f62e2c-3483-4559-83ce-99e3b0f7e3af)

**Comment by meletj** [comment]
@aaroncowie Thank you for raising this issue. This has been fixed and external links are implemented as <a> elements.
