### ISSUE TITLE
Prisma console documentation redirect for a 404

### ISSUE THREAD

**Issue by RicardoGEsteves** [prisma/prisma2-docs#5592]
![prisma-bug-404](https://github.com/prisma/docs/assets/30535937/ff1fca75-79ab-4f0c-935a-eb5ac8704d6b)

How to replicate:
- go to console.prisma.io 
- go to [USER] workspace
- click documentation

On console.prisma.io at user workspace if you click on documentation it redirect you to a 404.

**Comment by petradonka** [comment]
Hi @RicardoGEsteves! Thanks for raising the issue. We created a fix, could you check and see if you can still reproduce the problem?

**Comment by RicardoGEsteves** [comment]
> Hi @RicardoGEsteves! Thanks for raising the issue. We created a fix, could you check and see if you can still reproduce the problem?

@petradonka It's fixed! 👍
