### ISSUE TITLE
Handling two databases

### ISSUE THREAD

**Issue by akinyemi2161** [prisma/prisma2-docs#5597]
## Problem

There is no proper documentation on how to handle two databases with prisma

## Suggested solution

The steps should be added to the documentation.

**Comment by nikolasburk** [comment]
Hey @akinyemi2161, could you share a bit more context on this question?

For example, are you talking about two separate DBs with the same schema or different schemas?

**Comment by nikolasburk** [comment]
I'm closing this one for now, please let me know if you have any further questions and feel free to re-open the issue 🙏
