### ISSUE TITLE
Improve documentation about Nested Queries (Follow up to #5615)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5622]
It might be possible that nested `upsert` can also be used on other top-level methods besides `update()`, like `create()` and similar.

If that is the case, it might also make sense to mention and describe that under the "Nested Queries" headline, where currently we directly start listing the queries instead of describing them. Adding that would help users to understand how these nested queries are to be used beyond the limited examples we can provide there.

**Comment by nikolasburk** [comment]
Hey Jan, hope you're doing well 😄 I couldn't figure out which parts in the docs you're referring to here. If you still think this is relevant, feel free to re-open the issue with more info.
