### ISSUE TITLE
Document `transactionOptions` (`maxWait` & `timeout`) now available on the Prisma Client constructor 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#5629]
See https://github.com/prisma/prisma/pull/19592, which needs to be merged first

Example
```ts
    const prisma = new PrismaClient({
      transactionOptions: {
        maxWait: 200,
        timeout: 500,
      },
    })

    const result = prisma.$transaction(async (prisma) => {
      await prisma.user.create({
        data: {
          email: 'user_1@website.com',
        },
      })

....
    })
```

**Comment by nikolasburk** [comment]
This also includes `isolationLevel`, right @Jolg42? But that's it?

**Comment by nikolasburk** [comment]
Working on here: https://github.com/prisma/docs/pull/5654

**Comment by janpio** [comment]
> This also includes `isolationLevel`, right @Jolg42? But that's it?

Yes, where available.

**Comment by nikolasburk** [comment]
this is done via https://github.com/prisma/docs/pull/5654
