### ISSUE TITLE
Link does not have URL preview

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5653]
![image](https://github.com/prisma/docs/assets/183673/70b347fe-d045-4224-b00f-85fa4cae8856)

https://www.prisma.io/docs/orm/prisma-client/queries/full-text-search#:~:text=rows%20containing%20%27dog%27-,For%20the%20full%20range%20of%20supported%20operations%2C%20see%20the,.,-Sorting%20results%20by

Discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1708350791176879

**Comment by meletj** [comment]
Fixed by making links <a> elements
