### ISSUE TITLE
Weird positioning on CockroachDB admonition

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#5660]
<img width="709" alt="image" src="https://github.com/prisma/docs/assets/183673/36f3b327-af61-4a8d-b55d-de967db74f01">

https://www.prisma.io/docs/orm/overview/databases/cockroachdb

The admonition usually should be positioned in the normal text area, not weirdly to the left like this.

**Comment by meletj** [comment]
<img width="941" alt="Screenshot 2024-04-24 at 19 56 06" src="https://github.com/prisma/docs/assets/70962362/f5bbff62-a465-4fd1-8091-b148040a5dd9">
Fixed by the implementation of the new admonitions.
