### ISSUE TITLE
Distinguish between queries and query options by using `()`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5670]
Based on an internal Slack message: 

<img width="459" alt="image" src="https://github.com/prisma/docs/assets/4058327/2bfaaeb6-cdd3-4855-bd08-a1767f0511bf">

Related PR for `groupBy`: https://github.com/prisma/docs/pull/5668

**Comment by janpio** [comment]
Strategy to make this simpler:
1. Replace existing correct usages with `lalala(` (by replacing e.g. `findUnique(` with that string)
2. Turn on case matching in searches to _not_ match for link anchors
3. Go through all the occurrences
4. Undo the `lalala(` change
