### ISSUE TITLE
Update docs to reflect planetscale foreign keys adoption.

### ISSUE THREAD

**Issue by adriangalilea** [prisma/prisma2-docs#5677]
## Problem

[Prisma docs on planetscale](https://www.prisma.io/docs/orm/overview/databases/planetscale) seem outdated now that [Foreign key constraints are now generally available](https://planetscale.com/blog/foreign-key-constraints-are-now-generally-available)

## Doubt that the document might need to address

Is there anything I need to change on my prisma config after enabling that on planetscale?

Thank you.

EDIT: I just noticed the docs rightly refer to being able to enable this feature.

Perhaps this video [Prisma & PlanetScale Best Practices](https://www.youtube.com/watch?v=iaHt5_hg44c) should be refreshed or at least have a comment that reflects it may be outdated.

Also, it's not clear to me what the [limitations they have on this foreign key constraints](https://planetscale.com/docs/concepts/foreign-key-constraints#limitations) have any side-effect to be aware of when setting up this on prisma.

Sorry for closing and re-opening.

EDIT: I just noticed the description update on the video lol

Sorry again.

**Comment by adriangalilea** [comment]
Sorry I just noticed the comments about being able to enable them, I might be a little dense today.

**Comment by janpio** [comment]
All good.

The question about the limitations is a very valid one. I am not aware of any impact on Prisma.
