### ISSUE TITLE
Request for Clarification of How Default connection_limit and pool_timeout is calculated

### ISSUE THREAD

**Issue by NicoHinderling** [prisma/prisma2-docs#5687]
Hello! I am currently working on a web application that uses prisma running on AWS Lambda. Recently we came across a `connection_limit` bottleneck and I learned all about the `connection_limit` and `pool_timeout` details of prisma.

I've read through your existing documents and one thing I'm still unclear about is: how is it decided what these values should default to if not manually provided?

I saw here that the [default pool_timeout](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool#default-pool-timeout) is 10seconds (I couldn't find what default `connection_limit` should be), however I checked and ours is: `connection_limit=10`, `pool_timeout=13`.

I was going to manually set these values going forward so that it's more explicit, but my concern is that these may be getting generated dynamically based off of traffic/scale of the lambda. 

It doesn't seem like that, but I wouldn't want to break it if it is. Hence, I'd love some clarification on this!

Thank you very much!

**Comment by janpio** [comment]
Are you _sure_ your default `pool_timeout` is 13, and not the `connection_limit`? I am not aware of any dynamic calculations for the pool timeout, only for the connection limit - which is documented here: https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool#default-connection-pool-size

**Comment by NicoHinderling** [comment]
My apologies, I had them mixed up, it was `pool timeout: 10, connection limit: 13`

Okay thanks for the clarification!

**Comment by janpio** [comment]
All good, happy I could clarify. (I also took a note that we might need to centralize our docs on this a bit to make it easier to get this overview)
