### ISSUE TITLE
Document how to set a default schema for `pg` and `neon` adapters.

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma2-docs#5722]
When adapters are used, DB connection is configured even before prisma client is created. `schema` query parameter is non-standard and is not recognized by JS drivers. We have a different way of configuring default schema with adapters:

```
const adapter = new PrismaPg(pool, {
  schema: 'myDbSchema'
})
```

this applies only to `pg`, `neon` and `pg-worker` adapters. We need to document this.

**Comment by nikolasburk** [comment]
Done via: https://github.com/prisma/docs/pull/5954/files
