### ISSUE TITLE
Broken indentation on pages

### ISSUE THREAD

**Issue by ankur-arch** [prisma/prisma2-docs#5732]
Text indentation is broken on [https://www.prisma.io/docs/orm/reference/supported-databases](https://www.prisma.io/docs/orm/reference/supported-databases).

This can be reproduced when a text is added without a heading.

For example:

```
<TopBlock> Hello this is a docs page </TopBlock>

Broken indentation

## How to set up a database

This has the correct indentation 
```

**Comment by meletj** [comment]
@ankur-arch Can you take a look again? I think this has been fixed with the recent Docs update.
