### ISSUE TITLE
Error with the update in Best practice for instantiating Prisma Client with Next.js

### ISSUE THREAD

**Issue by rathoreyuvraj19** [prisma/prisma2-docs#5977]
![Screenshot 2023-01-14 104521](https://github.com/prisma/docs/assets/141350177/42c6792a-3d0d-44ba-a45c-083b03cd6b6e)

**Comment by janpio** [comment]
Probably fixed via https://github.com/prisma/docs/pull/5978 already?

**Comment by nikolasburk** [comment]
This has indeed been resolved! If you find another issue with the docs, feel free to open another one in the future @rathoreyuvraj19 🙌
