### ISSUE TITLE
Documentation on omitting fields is incomplete

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#6086]
The page in our docs [about excluding fields from being returned](https://www.prisma.io/docs/orm/prisma-client/queries/excluding-fields) has not been updated with the release of `omitApi`. We should update this page.

**Comment by KeentGG** [comment]
Might also be a good idea to  add `Omit` section on [PrismaClient reference docs](https://www.prisma.io/docs/orm/reference/prisma-client-reference#prismaclient)
