### ISSUE TITLE
Soft delete middleware does not prevent deleteMany in relational query

### ISSUE THREAD

**Issue by noelgoodday** [prisma/prisma2-docs#6091]
The "soft delete middleware" you have [in your docs](https://github.com/prisma/docs/blob/main/content/200-orm/200-prisma-client/300-client-extensions/500-middleware/100-soft-delete-middleware.mdx#step-2-soft-delete-middleware) does not cover when `deleteMany` is used in a relational query as described here: https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#delete-all-related-records.
Please update the docs to warn users that the middleware does not cover all cases of delete or update the docs with a middleware that prevents all deletes (except for the cases stated, e.g., a raw query).

**Comment by janpio** [comment]
Does the current one not cover it?

> Note: This page demonstrates a sample use of middleware. We do not intend the sample to be a fully functional soft delete feature.

**Comment by janpio** [comment]
Ah I see, the `deleteMany` could be easily understood to refer to the nested `deleteMany` operation and not just the `deleteMany()` query that it means and is used in the following example. Quick PR to at least make that clearer: https://github.com/prisma/docs/pull/6093

There might be other clarifications or disclaimers needed.

**Comment by nikolasburk** [comment]
Hey @noelgoodday, do the changes in Jan's PR as well as this one https://github.com/prisma/docs/pull/6122 sufficiently address your concern?

**Comment by noelgoodday** [comment]
@nikolasburk Yes, the changes address my concerns with the documentation. Feel free to close. There's an open question to whether y'all want to update the middleware to also cover those edge cases. We're using this middleware to turn deletes into soft-deletes and are now aware that it doesn't catch all edge cases so we're working around that. It'd be nice if it did though. Leaving that up to you.
