### ISSUE TITLE
Nothing is there on the Tools page

### ISSUE THREAD

**Issue by AnirudhMemani** [prisma/prisma2-docs#6144]
The [tools](https://www.prisma.io/docs/orm/tools) page seems to not contain any content.

![Screenshot 2024-07-06 225456](https://github.com/prisma/docs/assets/46074384/d7f9ac57-22da-4835-9e80-76cfa73deff0)

**Comment by mhessdev** [comment]
This is just how our index pages look on docs. We want to improve this in the future, but this is not technically an issue.
