### ISSUE TITLE
Choose which database we are using

### ISSUE THREAD

**Issue by nik-rev** [prisma/prisma2-docs#6145]
The next.js docs have an option where we can choose whether we are using the app or the pages router.

I was thinking it could be cool if Prisma docs allowed the user to choose which database we are using e.g. PostgreSQL, MongoDB, MySQL

I'm going through the docs currently for the first time and I'm only interested in the PostgreSQL content so I have to skip quite often. I believe UX would be improved if I could just choose "PostgreSQL" and the docs would only include information for PostgreSQL and not MongoDB or others.

**Comment by mhessdev** [comment]
We have considered this in the past. We don't have the resources to tackle this at the moment, but we plan to do this in the future. We are going to close this as it doesn't really align with what an issue is.

**Comment by nik-rev** [comment]
> We have considered this in the past. We don't have the resources to tackle this at the moment, but we plan to do this in the future. We are going to close this as it doesn't really align with what an issue is.

Thanks for the info. I don't know what other place would be appropriate for this kind of discussion, though. **Discussion** tab isn't available.

I was thinking an approach like this could work:
- Create `<DatabaseSection>` component that accepts a `type` prop which can be like `MongoDB`, `PostgreSQL` etc
- This component will hide it's `children` if the `type` matches whatever the user's choice for db is
- Go through all the `content` and cover relevant sections with the component

I think this is the simplest way to do this but idk
