### ISSUE TITLE
Selecting the Language model once prisma has been installed as an extension on Visual studio code 

### ISSUE THREAD

**Issue by smashbrick** [prisma/prisma2-docs#6187]
```
Once installed, make sure to select the appropriate language model to use it within Visual Studio Code.
```

Could we get this added in the docs (docs/content/200-orm/800-more/500-development-environment/100-editor-setup.mdx) ?  I'm sure a senior developer would probably know this but it confused me as a beginner. 

I tried to create a PR, but I do not have permission to do so.

**Comment by smashbrick** [comment]
@jharrell I'm unable to create a PR, so tagging you.

**Comment by jharrell** [comment]
You should be able to fork the repo, make changes on your fork, and then submit those changes in a PR to our repo. 

If you want to try that, please feel free to do so! But regardless, thank you for opening an issue 🙏

**Comment by nikolasburk** [comment]
Hey @smashbrick, I created a PR with your suggestion: https://github.com/prisma/docs/pull/6307

I assumed you wanted to add this sentence in the **VS Code** section, right?

**Comment by nikolasburk** [comment]
@smashbrick I took the liberty to merge the PR. Feel free to open another one if you still think it can be improved 🙏 

> You should be able to fork the repo, make changes on your fork, and then submit those changes in a PR to our repo.

Also, here's an article the explains [how to create a PR](https://opensource.com/article/19/7/create-pull-request-github) in an open-source project 😄
