### ISSUE TITLE
Referential Actions Section: UI breaks when viewing on devices with a width < 560 pixels. 

### ISSUE THREAD

**Issue by mohammednumaan** [prisma/prisma2-docs#6273]
In the `referential actions` sections of the **prisma** docs, the table present in [this secton](https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/referential-actions#types-of-referential-actions) causes an extra white space on the right-hand side of a device with a `width < 560px`. (as show below).

![image](https://github.com/user-attachments/assets/cb65fa5b-807b-4a4a-9494-60e7ed3d4319)

This may cause inconvenience while reading this section on devices with a screen width less than `560px`. A possible fix would be **wrapping** the table in a `div` and setting the div's CSS overflow property to `overflow-x:auto`. This would make the table scrollable in the `x-direction` and making it responsive to devices with a screen width less than `560px`.

Here is what it would like after the fix (note that the table is scrollable):
![image](https://github.com/user-attachments/assets/a414276b-52de-4a4e-979c-67c8a5c7490c)

`Note: I would be happy to work on this issue.`

**Comment by mohammednumaan** [comment]
@jharrell I was wondering if you could lend a hand by taking a quick look at the issue? Thanks!

**Comment by jharrell** [comment]
Hi there, thanks for the ping. I'm getting this entered into our internal issue tracking to make sure we take a look
