### ISSUE TITLE
composite types doc says to run migrate while mongodb doesn't support it

### ISSUE THREAD

**Issue by chiptus** [prisma/prisma2-docs#6292]
on https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/composite-types#:~:text=Suppose%20that%20you%20then%20run%20npx%20prisma%20migrate%20deploy%20to%20deploy%20your%20database%20changes%20and%20regenerate%20your%20Prisma%20Client%20with%20npx%20prisma%20generate.%20Then%2C%20you%20run%20the%20following%20application%20code

The composite types guide is only for mongodb.

it is said to run `npx prisma migrate deploy` and there's a link. the linked page starts with "this is not supported on MongoDB"

should be `npx prisma db push` and a different link.

**Comment by nikolasburk** [comment]
Hey @chiptus, nice catch! Thanks a lot, this has been fixed via: https://github.com/prisma/docs/pull/6306
