### ISSUE TITLE
Missing Vercel deployment instructions

### ISSUE THREAD

**Issue by lnikell** [prisma/prisma2-docs#6299]
Hi, and thank you for the great work on Prisma ORM. After reading the docs, I noticed that [this page](https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-vercel) does not have complete information. It does not explain how the database structure from your codebase will appear on Vercel.

It does not specify the need for a separate CI/CD flow for running migrations or using a vercel-build script in package.json with.
```
"vercel-build": "prisma generate && prisma migrate deploy && next build",
```

**Comment by jharrell** [comment]
@lnikell thanks for the info! Did the provided instructions not work? We have recommended the `postinstall` script so far.

**Comment by nikolasburk** [comment]
I went ahead and expanded the docs according to my understanding of your request @lnikell in this PR: https://github.com/prisma/docs/pull/6310

If I understood correctly, the main point you made was about a more advanced CI/CD scenario where not only Prisma Client needs to be generated but you also want to update the DB schema in the build pipeline, is that correct? Does the PR address your concern?
