### ISSUE TITLE
Add warning about using the extension feature with transactions

### ISSUE THREAD

**Issue by chawes13** [prisma/prisma2-docs#6358]
Extensions that reference the prisma client will execute outside of the context of the transaction. This can lead to very serious bugs – reads can be stale and updates/deletes won't rollback.

It would be very helpful to acknowledge this in the documentation until https://github.com/prisma/prisma/issues/20678 is resolved.

**Comment by nikolasburk** [comment]
Hey @chawes13 👋 thanks a lot for raising this! I fully agree that this should be documented 👍 so I just went ahead and created a PR: https://github.com/prisma/docs/pull/6385

Do the changes and linking bag to the original issue `/prisma/prisma` sufficiently address your concerns? Anything else that you think I should add to the PR?

**Comment by chawes13** [comment]
That PR definitely resolves this issue! Thanks 🙂
