### ISSUE TITLE
Broken Prisma ORM Quickstart link button

### ISSUE THREAD

**Issue by irian-codes** [prisma/prisma2-docs#6408]
Hi! I just wanted to learn about Prisma and I went to the [ORM landing page](https://www.prisma.io/orm), I clicked on 'Quickstart' button but the link is broken (it navigates to [this link](https://www.prisma.io/docs/getting-started/quickstart)). I think the correct link should be https://www.prisma.io/docs/getting-started/quickstart-sqlite or https://www.prisma.io/docs/getting-started/quickstart-prismaPostgres

Just here to inform you about it, have a nice day! 👋

**Comment by mhessdev** [comment]
Hey thanks for this! We just deployed a fix. Very much appreciated 🙏
