### ISSUE TITLE
Broken link to samples

### ISSUE THREAD

**Issue by Maxim-Mazurok** [prisma/prisma2-docs#6440]
Here https://www.prisma.io/typescript#typescript-tabs [Explore on GitHub](https://github.com/prisma/prisma-examples/tree/latest/typescript/script) leads to 404

I think it was moved here: https://github.com/prisma/prisma-examples/tree/latest/orm/script

Couldn't find none of this referenced in this repo, also couldn't find "site" repo in the org, so this seems the closest... Hope this helps, cheers!

**Comment by gniting** [comment]
@Maxim-Mazurok thanks for reporting! 

@jharrell FYI...

**Comment by jharrell** [comment]
@Maxim-Mazurok thanks for the report! These should now be fixed 😊
