### ISSUE TITLE
Prisma Client API reference - `findFirst` - 'Options' table is broken

### ISSUE THREAD

**Issue by 0xdevalias** [prisma/prisma2-docs#6453]
https://www.prisma.io/docs/orm/reference/prisma-client-reference#findfirst

![image](https://github.com/user-attachments/assets/01e156b7-4312-4024-b593-0c3b44dce074)

**Comment by nikolasburk** [comment]
Nice catch, thanks for opening the issue about this @0xdevalias 🙌
