### ISSUE TITLE
algolia.appId which was on .env is now missing

### ISSUE THREAD

**Issue by sirNugg3ts** [prisma/prisma2-docs#6525]
It's not possible at the moment to start a local instance of the docs since the algolia app id and key was on .env , and that was removed on #6490 

` details: [
    {
      message: `"algolia.appId" is required. If you haven't migrated to the new DocSearch infra, please refer to the blog post for instructions: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration`,
      path: [ 'algolia', 'appId' ],
      type: 'any.required',
      context: { label: 'algolia.appId', key: 'appId' }
    }
  ]`

**Comment by jharrell** [comment]
Thanks for the report! Should be resolved here: #6528
